### ISSUE TITLE
Specify build configuration for test target

### ISSUE THREAD

**Issue by iamszabo** [yonaskolb/XcodeGen#1008]
I'm looking for a way to change the build configuration of the test target as by default it's going to be the `Debug`.
```
targets:
  Apple:
    type: framework
    platform: iOS
    sources: 
      - Apple
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: AppleTests
          parallelizable: true
          randomExecutionOrder: true
```
So this will generate an Apple scheme automatically but the config of the test target it's going to be `Debug` but I would like to have `Test`. I tried to override this scheme in a `schemes` section but it seems that I cannot name it in the same way.

Is there any way to change the build configuration or do I need to create a new scheme?

**Comment by iamszabo** [comment]
Literally just found the solution. I had to remove the `scheme` so it won't automatically generate it.

```
targets:
  Apple:
    type: framework
    platform: iOS
    sources: 
      - Apple
schemes:
  Apple:
    build:
      targets:
        Apple: all
        AppleTests: [test]
    test:
      config: Test
      targets:
        - name: AppleTests
```
