### ISSUE TITLE
Generated scheme contains additional (unspecified) targets in Test Action

### ISSUE THREAD

**Issue by ffittschen** [yonaskolb/XcodeGen#1009]
Recently, we are often running into the following build errors (excerpt of hundreds of this kind):

```
error: Multiple commands produce '[...]/DerivedData/[...]/Build/Products/Debug-iphonesimulator/SomeApp.app
duplicate output file '[...]/DerivedData/[...]/Build/Products/Debug-iphonesimulator/SomeApp.app/_CodeSignature' on task: CodeSign [...]/DerivedData/[...]/Build/Products/Debug-iphonesimulator/SomeApp.app (in target 'SomeAppWithExtension' from project 'SomeApp')
```

We have a similar setup as described in #589, so we specify an `AllTests` scheme, in which we specify all of our individual test targets in the test action. The build and run actions contain a reference to our main application target, which is also used as the host application for this scheme.

During our investigations, we discovered that the errors always occur, when the `AllTests` scheme contains an additional application target in the list of targets in the Test Action of the scheme (see screenshot). When running `xcodegen generate` multiple times in a row (10+ times), this additional target is present in the `AllTests` scheme for approximately half of the cases.

We already tried debugging the `SchemeGenerator`, but we could not find the location in which the additional application target is added to the scheme. The `testables`, which are added to the `XCScheme.TestAction` only contain the test targets that we explicilty specify in the `project.yml`. So how are the bottom two entries ending up in the scheme? When opening the generated `xcscheme` file, it doesn't even contain a reference to those bottom two entries. 

Do you have any idea, how the additional target could end up in the scheme?

---

<details>

<summary>project.yml</summary>

```yml
schemes:
  AllTests:
    build:
      targets:
        SomeApp: test
    run:
      executable: "SomeApp"
    test:
      gatherCoverageData: true
      language: en
      region: US
      targets:
        - name: TestTarget1
          randomExecutionOrder: true
          parallelizable: true
        - name: TestTarget2
          randomExecutionOrder: true
          parallelizable: true
        - name: TestTarget3
          randomExecutionOrder: true
          parallelizable: true
        - ...
```

</details>

<details>

<summary>Screenshot</summary>

![Screen Shot 2021-01-18 at 12 10 32@2x](https://user-images.githubusercontent.com/7734806/104909801-b14d7580-5988-11eb-9f77-36eb24481de0.png)

</details>
