### ISSUE TITLE
Template settings overwrites target settings

### ISSUE THREAD

**Issue by fjcaetano** [yonaskolb/XcodeGen#1016]
## Description

Target-specific settings are discarded in favor of template settings

## Expected Behavior

It seems to me that target-specific settings, like `HEADER_SEARCH_PATHS` below, should be added in conjunction to the settings specified in the template. In case of key conflict, target-specific should be favored.

```yaml
targets:
  SomeFramework:
    templates:
      - Framework
    settings:
      HEADER_SEARCH_PATHS:
          - "$(inherited)"
          - (any other paths here)
 
 targetTemplates:
   Framework:
     type: framework
     settings:
       INFOPLIST_FILE: ${target_name}/Info.plist
```

## Observed Behavior

Target-specific settings are being ignored in favor of template settings.
