### ISSUE TITLE
Project w/ 2 app targets loses linked libraries to 2nd app after Xcode modification

### ISSUE THREAD

**Issue by mthole** [yonaskolb/XcodeGen#1017]
I have a moderately complex XcodeGen set up involving multiple internal libraries/frameworks and produces multiple application targets. It works great, until you try to modify the project in Xcode (e.g. by adding a new file). Xcode then ends up stripping the libraries from all but the first application target(!)

## Simplified Reproduction
I've created a simplified example project to illustrate the issue:
[XcodeGenBugExample.zip](https://github.com/yonaskolb/XcodeGen/files/5962519/XcodeGenBugExample.zip)

1. Download the .zip, use `make` to run xcodegen on the 3 included projects
```
➜  XcodeGenBugExample
 make
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/mthole/XcodeGenTest/LibraryA/LibraryA.xcodeproj
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/mthole/XcodeGenTest/LibraryB/LibraryB.xcodeproj
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/mthole/XcodeGenTest/App/App.xcodeproj
```

2. Open the App.xcodeproj, and examine the `App1` and `App2` targets. They both link to the `libLibraryA.a` and `libLibraryB.a` libraries. All is well.

![image](https://user-images.githubusercontent.com/57376542/107590987-7a9d0080-6bbe-11eb-9086-6e03d9f9669e.png)
![image](https://user-images.githubusercontent.com/57376542/107590996-7f61b480-6bbe-11eb-9a9f-f28a3dc4e5ff.png)

3. Go and add a new .swift file to the App target. (Or do a number of other Xcode operations that trigger whatever re-evaluation is happening...). I added `File.swift` to the `App1` and `App2` targets.

4. Examine the `App1` and `App2` targets. Notice that `App2` is now missing both `libLibraryA.a` and `libLibraryB.a`. Sadface!

![image](https://user-images.githubusercontent.com/57376542/107591143-db2c3d80-6bbe-11eb-8a10-9b67b3dc6bcd.png)
![image](https://user-images.githubusercontent.com/57376542/107591150-e1bab500-6bbe-11eb-9891-1dc9ee86b612.png)

###

I've been using Xcode 12.4. If anyone has any ideas, I'm happy to help investigate further here.

**Comment by mthole** [comment]
This seems to be related to `projectReferences`. If I smash everything into a single .xcodeproj, I cannot reproduce this. (That's not a tenable workaround for my real life use case, unfortunately.)

e.g. a project defined like this behaves as expected

```
name: App

options:
  minimumXcodeGenVersion: 2.18
  xcodeVersion: 12.4
  deploymentTarget:
    iOS: 13.0

projectReferences:
  LibraryA:
    path: ../LibraryA/LibraryA.xcodeproj
  LibraryB:
    path: ../LibraryB/LibraryB.xcodeproj

targets:
  App1:
    type: application
    platform: iOS
    sources:
      - path: App.swift
    dependencies:
      - target: LibraryA/LibraryA
      - target: LibraryB/LibraryB
  App2:
    type: application
    platform: iOS
    sources:
      - path: App.swift
    dependencies:
      - target: LibraryA/LibraryA
      - target: LibraryB/LibraryB
```
