### ISSUE TITLE
trailing slash on target include path can cause duplicate folder

### ISSUE THREAD

**Issue by agentef** [yonaskolb/XcodeGen#1021]
Adding the same sources to multiple targets can cause an empty group to show in Xcode when you create different statements, like:

```
target1: 
...
    sources:
          - path: path/to/folder
```

and 

```
target2:
...
    sources:
          - path: path/to/folder/
```
