### ISSUE TITLE
How to add package unit tests to main target

### ISSUE THREAD

**Issue by smeshko** [yonaskolb/XcodeGen#1028]
I have modularised my app into local swift packages and want to add their test targets to the main target, but can't seem to find a way to do that. Previously they were normal frameworks and I had it setup like so: 

```
targets:
  MainApp:
    templates: [Target]
    dependencies:
        [...]
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: Framework1
        - [...]
```
