### ISSUE TITLE
duplicate output file for watch app: on task

### ISSUE THREAD

**Issue by RalfK92** [yonaskolb/XcodeGen#1034]
Hi, i was trying to get xcodegen running for a customer of my company and encountered a problem when i was adding the watch app and the watch extension. We have multiple projects where we have integrated xcodgen without any big issues, but we were not able to fix this problem on our own. So i am asking for help to get this project to build again. 

When i try to build any configVariant, watch or iOS i get this error. When i remove any watch releated configuration the project builds.
![Screenshot 2021-03-08 at 08 49 35](https://user-images.githubusercontent.com/4293838/110302056-1b81ae80-7ff9-11eb-8a9e-dd9a1d2cf238.png)

I removed a view config variants, and replaced some parts for privacy reasons as the yml grows very fast. The xcodegen version i use is 2.18.0.
The yml files are attached below. Let me know if there's anything else you need from us that can help make troubleshooting or fixing this easier. Thanks!

``` yml
###########################################################
#  project.yml 
###########################################################

configs:
  Distribution Debug: debug
  Distribution Release: release
  Production Debug: debug
  Production Release: release
name: projectName
options:
  deploymentTarget:
    iOS: '12.0'
    watchOS: '6'
  generateEmptyDirectories: true
  groupSortPosition: top
  minimumXcodeGenVersion: 2.18.0
  postGenCommand: ./Build-Phases/xcodegen_prebuild.sh
settingGroups:
  baseSettingsGroup:
    base:
      CURRENT_PROJECT_VERSION: 225
      DEVELOPMENT_TEAM: XXXXXXXXXX
      ENTITLEMENTS: projectName/projectName.entitlements
      GOOGLE_SERVICE_INFO_PATH: ${PROJECT_DIR}/${TARGET_NAME}/Firebase/$(PRODUCT_BUNDLE_IDENTIFIER)/GoogleService-Info.plist
      MARKETING_VERSION: 2.3.1
    configs:
      Distribution:
        APP_PRODUCT_NAME: projectName
        CODE_SIGN_ENTITLEMENTS: ${ENTITLEMENTS}
        PRODUCT_BUNDLE_IDENTIFIER: ${BASE_BUNDLE_IDENTIFIER}
      Distribution Debug:
        CODE_SIGN_IDENTITY: Apple Development
        PROVISIONING_PROFILE_SPECIFIER: match Development ${PRODUCT_BUNDLE_IDENTIFIER}
        SWIFT_ACTIVE_COMPILATION_CONDITIONS:
          - DISTRIBUTION
          - DEBUG
      Distribution Release:
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: 'CodeSignIdentity'
        DEVELOPMENT_TEAM: YYYYYYYYYY
        PROVISIONING_PROFILE_SPECIFIER: match AdHoc ${PRODUCT_BUNDLE_IDENTIFIER}
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DISTRIBUTION
      Production:
        APP_PRODUCT_NAME: projectName
        CODE_SIGN_ENTITLEMENTS: ${ENTITLEMENTS}
        PRODUCT_BUNDLE_IDENTIFIER: ${BASE_BUNDLE_IDENTIFIER}
      Production Debug:
        CODE_SIGN_IDENTITY: Apple Development
        DEVELOPMENT_TEAM: XXXXXXXXXX
        PROVISIONING_PROFILE_SPECIFIER: match Development ${PRODUCT_BUNDLE_IDENTIFIER}
        SWIFT_ACTIVE_COMPILATION_CONDITIONS:
          - RELEASE
          - DEBUG
      Production Release:
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: 'CodeSignIdentity'
        DEVELOPMENT_TEAM: YYYYYYYYYY
        PROVISIONING_PROFILE_SPECIFIER: match AppStore ${PRODUCT_BUNDLE_IDENTIFIER}
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
settings:
  base:
    BASE_BUNDLE_IDENTIFIER: bundle.indentifier
    BASE_PATH: projectName
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    SWIFT_VERSION: '5.0'
    TARGETED_DEVICE_FAMILY:
      - 1
      - 2
    VERSIONING_SYSTEM: apple-generic

include:
  - path: xcodegen/project_ios.yml
    relativePaths: false
  - path: xcodegen/project_watchos.yml
    relativePaths: false
```

``` yml
###########################################################
#  project_ios.yml 
###########################################################

targets:
  NotificationService:
    dependencies: 
      - framework: Vendor/ibm-mobile-push/IBMMobilePushNotificationService.framework
        type: library.static
        embed: false
        link: true
    platform: iOS
    settings:
      base:
        TARGETED_DEVICE_FAMILY:
          - 1
          - 2
        SWIFT_OBJC_BRIDGING_HEADER: projectNameNotificationServiceExtension/projectNameNotificationServiceExtension-Bridging-Header.h
        LIBRARY_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR) $(PROJECT_DIR)/Vendor/ibm-mobile-push/IBMMobilePushNotificationService.framework"
      configs:
        Distribution:
          DEVELOPMENT_TEAM: YYYYYYYYYY
          PRODUCT_BUNDLE_IDENTIFIER: ${BASE_BUNDLE_IDENTIFIER}.projectNameNotificationServiceExtension
        Distribution Debug:
          CODE_SIGN_IDENTITY: 'Apple Development: Developer (ZZZZZZZZZ)'
          PROVISIONING_PROFILE_SPECIFIER: match Development ${PRODUCT_BUNDLE_IDENTIFIER}
        Distribution Release:
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: Apple Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc ${PRODUCT_BUNDLE_IDENTIFIER}
        Production:
          DEVELOPMENT_TEAM: YYYYYYYYYY
          PRODUCT_BUNDLE_IDENTIFIER: ${BASE_BUNDLE_IDENTIFIER}.projectNameNotificationServiceExtension
        Production Debug:
          CODE_SIGN_IDENTITY: 'Apple Development: Developer (ZZZZZZZZZ)'
          PROVISIONING_PROFILE_SPECIFIER: match Development ${PRODUCT_BUNDLE_IDENTIFIER}
        Production Release:
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: Apple Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore ${PRODUCT_BUNDLE_IDENTIFIER}
      groups:
        - baseSettingsGroup
    sources:
      - path: projectNameNotificationServiceExtension
      - group: projectNameNotificationServiceExtension
        path: projectName/Resources/MceConfig.json
    type: app-extension
  projectName:
    dependencies:
      - sdk: AdSupport.framework
      - sdk: iAd.framework
      - embed: false
        framework: Vendor/ibm-mobile-push/IBMMobilePush.framework
        link: true
        type: library.static
      - target: NotificationService
      - target: projectName watch
    platform: iOS
    postBuildScripts:
      - inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
        name: Crashlytics
        script: '"${PODS_ROOT}/FirebaseCrashlytics/run"'
    preBuildScripts:
      - name: Build Scripts
        script: '"${SRCROOT}/Build-Phases/_runscripts.sh"'
      - name: Firebase Info Plists
        script: '"${SRCROOT}/Build-Phases/GoogleService_Info_plist.sh"'
    scheme:
      configVariants:
        - Distribution
        - Production
      testTargets:
        - projectNameTests
        - projectNameUITests
    settings:
      base:
        LIBRARY_SEARCH_PATHS: $(inherited) $(PROJECT_DIR) $(PROJECT_DIR)/Vendor/ibm-mobile-push/IBMMobilePush.framework
        OTHER_SWIFT_FLAGS: $(inherited)
        PRODUCT_MODULE_NAME: projectName
        PRODUCT_NAME: $(APP_PRODUCT_NAME)
        SWIFT_OBJC_BRIDGING_HEADER: projectName/projectName-Bridging-Header.h
      groups:
        - baseSettingsGroup
    sources:
      - buildPhase: none
        group: projectName
        path: projectName/Firebase
      - createIntermediateGroups: true
        path: projectName/Sources
      - createIntermediateGroups: true
        group: projectName
        path: projectName/Resources
      - buildPhase: resources
        createIntermediateGroups: false
        group: projectName/Resources
        path: projectName/tessdata
        type: file
      - path: projectName/Info.plist
      - path: projectName/projectName.entitlements
      - buildPhase: none
        group: projectName
        path: project.yml
      - buildPhase: none
        group: projectName/Resources
        path: shared/strings.ini
      - buildPhase: none
        group: projectName/Resources
        path: shared/colors.xml
      - buildPhase: resources
        createIntermediateGroups: false
        group: projectName/Resources
        path: projectName/container
        type: file
      - buildPhase: none
        group: projectName
        path: projectName/projectName-Bridging-Header.h
    type: application
  projectNameTests:
    dependencies:
      - target: projectName
    platform: iOS
    settings:
      base:
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/$(APP_PRODUCT_NAME).app/$(APP_PRODUCT_NAME)
      groups:
        - baseSettingsGroup
    sources:
        path: projectNameTests
      - path: projectName/Sources/Model/Promotion.swift
      - path: projectName/Sources/Model/Game.swift
    type: bundle.unit-test
  projectNameUITests:
    dependencies:
      - target: projectName
    platform: iOS
    settings:
      base: null
      groups:
        - baseSettingsGroup
    sources:
      - path: projectNameUITests
    type: bundle.ui-testing
```

``` yml
###########################################################
#  project_watchos.yml 
###########################################################

targets:
  projectName watch:
    dependencies:
      - target: projectName watchkitapp Extension
    platform: watchOS
    scheme:
      configVariants:
        - Distribution
        - Production
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 4
        DEVELOPMENT_TEAM: XXXXXXXXXX
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Distribution:
          DEVELOPMENT_TEAM: YYYYYYYYYY
          PRODUCT_BUNDLE_IDENTIFIER: ${BASE_BUNDLE_IDENTIFIER}.watchkitapp
        Distribution Debug:
          CODE_SIGN_IDENTITY: 'Apple Development: Developer (ZZZZZZZZZ)'
          PROVISIONING_PROFILE_SPECIFIER: match Development ${PRODUCT_BUNDLE_IDENTIFIER}
        Distribution Release:
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: Apple Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc ${PRODUCT_BUNDLE_IDENTIFIER}
        Production:
          DEVELOPMENT_TEAM: YYYYYYYYYY
          PRODUCT_BUNDLE_IDENTIFIER: ${BASE_BUNDLE_IDENTIFIER}.watchkitapp
        Production Debug:
          CODE_SIGN_IDENTITY: 'Apple Development: Developer (ZZZZZZZZZ)'
          PROVISIONING_PROFILE_SPECIFIER: match Development ${PRODUCT_BUNDLE_IDENTIFIER}
        Production Release:
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: Apple Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore ${PRODUCT_BUNDLE_IDENTIFIER}
    sources:
      - path: projectNameWatch
      - group: projectNameWatchExtension
        path: projectNameWatchExtension/Resource
    type: application.watchapp2
  projectName watchkitapp Extension:
      dependencies:
      framework: Vendor/ibm-mobile-push/IBMMobilePush.framework
    platform: watchOS
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 4
      configs:
        Distribution:
          DEVELOPMENT_TEAM: YYYYYYYYYY
          PRODUCT_BUNDLE_IDENTIFIER: ${BASE_BUNDLE_IDENTIFIER}.watchkitapp.watchkitextension
        Distribution Debug:
          CODE_SIGN_IDENTITY: 'Apple Development: Developer (ZZZZZZZZZ)'
          PROVISIONING_PROFILE_SPECIFIER: match Development ${PRODUCT_BUNDLE_IDENTIFIER}
        Distribution Release:
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: Apple Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc ${PRODUCT_BUNDLE_IDENTIFIER}
        Production:
          DEVELOPMENT_TEAM: YYYYYYYYYY
          PRODUCT_BUNDLE_IDENTIFIER: ${BASE_BUNDLE_IDENTIFIER}.watchkitapp.watchkitextension
        Production Debug:
          CODE_SIGN_IDENTITY: 'Apple Development: Developer (ZZZZZZZZZ)'
          PROVISIONING_PROFILE_SPECIFIER: match Development ${PRODUCT_BUNDLE_IDENTIFIER}
        Production Release:
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: Apple Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore ${PRODUCT_BUNDLE_IDENTIFIER}
        groups:
         - baseSettingsGroup
    sources:
      - path: projectNameWatchExtension
      - group: projectNameWatchExtension
        path: projectName/Sources/Utilities/LocalizableSwiftGen.swift
      - group: projectNameWatchExtension
        path: projectName/Sources/ApplicationDelegates/ConfigurationApplicationDelegate.swift
    type: watchkit2-extension
    ```
