### ISSUE TITLE
How to add a path to Header Search Paths

### ISSUE THREAD

**Issue by AeonLucid** [yonaskolb/XcodeGen#1037]
Is it possible to have XcodeGen add a path to the `Header Search Paths` inside the generated xcodeproject? I need to have an external include directory added in such a way that I can use angle brackets for the includes.

As example:
![image](https://user-images.githubusercontent.com/4643257/112023838-e5cde100-8b33-11eb-8a86-a4d54b4f83ae.png)

This is my current project.yml:
```
name: Something
options:
  bundleIdPrefix: com.aeonlucid.something
targets:
  Tweak:
    type: bundle
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - path: src
```
