### ISSUE TITLE
File not added to target membership in 2.19.0

### ISSUE THREAD

**Issue by takoikatakotako** [yonaskolb/XcodeGen#1045]
Hello!
I have prepared a GoogleService-Info.plist file an Info.plist files for each target.
It worked fine up to 2.18.0, but after upgrading to 2.19.0, GoogleService-Info.plist and Info.plist are no longer added to my membership.
Need additional settings?
The folder structure and Xcodegen are as follows.
Xcodegen always help me. Thank you!🙏

```
...
Develop:
  type: application
  platform: iOS
  sources:
    - path: MyApp
    - Config/Develop
...
Staging:
  type: application
  platform: iOS
  sources:
    - path: MyApp
    - Config/Staging
...
Production:
  type: application
  platform: iOS
  sources:
    - path: MyApp
    - Config/Production
...
```

```
├── MyApp
│   ├── AppDelegate.swift
│   ├── ViewController.swift
│    ...
├── Config
│   ├── Develop
│   │   ├── GoogleService-Info.plist
│   │   └── Info.plist
│   ├── Staging
│   │   ├── GoogleService-Info.plist
│   │   └── Info.plist
│   └── Production
│       ├── GoogleService-Info.plist
│       └── Info.plist
├── project.yml
├── Mintfile
...
```

In 2.18.0
<img width="400" alt="2 18 0" src="https://user-images.githubusercontent.com/7970479/113410213-d3825b80-93ed-11eb-8397-656aac4cc03a.png">

In 2.19.0
<img width="400" alt="2 19 0" src="https://user-images.githubusercontent.com/7970479/113410217-d67d4c00-93ed-11eb-8d02-67e909b32b85.png">
