### ISSUE TITLE
Capabilities - App Group Issue

### ISSUE THREAD

**Issue by yevgenPaykey** [yonaskolb/XcodeGen#1046]
Hi.
Just referenced this issue https://github.com/yonaskolb/XcodeGen/issues/919 to add entitlements. 
```
entitlements:
      path: App/App.entitlements
      properties:
        com.apple.security.application-groups: group.App.Sample
```
But for me it doesn't work since this creates .entitlements file with a String value for the key "com.apple.security.application-groups" instead of Array. This leads to a bug: app group is not present in the list and not "checked". And this capability doesn't work 
<img width="787" alt="Screenshot 2021-04-07 at 20 50 00" src="https://user-images.githubusercontent.com/53140245/113911777-08722200-97e3-11eb-950a-091e38bbca39.png">

At the same time, If I Use pre-generated Entitlements file and remove corresponding code in yaml, the groups list is just empty

Is there something like
`com.apple.security.application-groups: 
  - group: "group.App.Sample`

?

**Comment by yonaskolb** [comment]
Hi @yevgenPaykey. Does this work?
```
entitlements:
      path: App/App.entitlements
      properties:
        com.apple.security.application-groups: [group.App.Sample]
```
