### ISSUE TITLE
How to add testTargets from local swift package to targets in Xcodegen?

### ISSUE THREAD

**Issue by BeerPoldet** [yonaskolb/XcodeGen#1050]
I have a swift package named `Lib` having a testTarget name `LibTests`. And I also have iOS target name `MyApp` which wants to use `LibTests` as one of its testTargets scheme. If I were using Xcode UI to manipulate `xcodeproj` directly. I can go to `MyApp`'s test scheme and add `LibTests` there. But I wonder how can I do the same with Xcodegen.

I have my `project.yml` defined like this. It doesn't work. `LibTests` doesn't get included in `MyApp` test targets.

```
packages:
  Lib:
    path: Lib

targets:
  MyApp:
    type: application
    platform: iOS
    scheme:
      testTargets:
      - package: Lib
        product: LibTests
```

Thanks in advance.

**Comment by freddi-kit** [comment]
Hi, @BeerPoldet.
The format that you write is not supported. Yours wrote format is for `Package dependency` but not for `testTargets`.
The correct format for `testTargets` is in described [here](https://github.com/yonaskolb/XcodeGen/blob/0ac7a5f8c6652650d03d89c92da09ec74c6e6060/Docs/ProjectSpec.md#test-target), please check it.

**Comment by BeerPoldet** [comment]
@freddi-kit Is there other way I can specify `testTargets` that's from SwiftPM?.  Doing as below doesn't work either as `LibTests` isn't target that defined in my `project.yml` but exported from SwiftPM.
```
packages:
  Lib:
    path: Lib

targets:
  MyApp:
    type: application
    platform: iOS
    scheme:
      testTargets:
      - LibTests
```
Do you have suggestion for other workarounds?

**Comment by freddi-kit** [comment]
I'm checking, please wait for a moment.

**Comment by freddi-kit** [comment]
can you provide me the detail of Lib's package.swift?

**Comment by BeerPoldet** [comment]
Here you go. I redacted some of the irrelevant bits.
```
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
  name: "Lib",
  platforms: [.iOS(.v14)],
  products: [...],
  targets: [
    ...,
    .testTarget(
      name: "LibTests",
      dependencies: []
    )
  ]
)
```

**Comment by freddi-kit** [comment]
Thank you

**Comment by freddi-kit** [comment]
Sorry, I cannot create an Xcode project which referring spm's inside test as test target even not using Xcodegen. 
Could you help to give me some information about your project?  Some project tree and scheme pictures are okay.

**Comment by BeerPoldet** [comment]
I created a sample project that demonstrates this issue. here https://github.com/BeerPoldet/MyAppXcodegen

As I referred to the point that I can add `MyLibTests` to `MyApp` scheme through Xcode UI. eg.
<img width="1512" alt="Screen Shot 2564-04-11 at 13 35 39" src="https://user-images.githubusercontent.com/7531231/114294746-d0acf800-9aca-11eb-8385-7612c31bc39f.png">
<img width="1512" alt="Screen Shot 2564-04-11 at 13 35 56" src="https://user-images.githubusercontent.com/7531231/114294757-d99dc980-9aca-11eb-9f35-2a7202b598d0.png">
<img width="1512" alt="Screen Shot 2564-04-11 at 13 36 02" src="https://user-images.githubusercontent.com/7531231/114294759-dc98ba00-9aca-11eb-8c5f-96950b108f05.png">

**Comment by freddi-kit** [comment]
Thank you! let me check detail

**Comment by freddi-kit** [comment]
Sorry for late. I'm currently working on it and it requires other library fixing. But please note that operation is ongoing

**Comment by BeerPoldet** [comment]
Great! I appreciate your effort in adding this. I have been invested a bit in learning `Xcodeproj` the ruby program that xcodegen uses underlying. But I also don't find a way to create `TestableReference` if I can remember that has `BuildableReference` to a target which does not define in xcodrproj code. 
Sorry for splitting a lot of nonsense stuff. Anyway, thank you. God bless.

**Comment by freddi-kit** [comment]
What you said makes sence! BuildableReference is one of in problem and we need to fix it.
FYI: https://github.com/tuist/XcodeProj/pull/605

**Comment by freddi-kit** [comment]
If you want to challenge to add it to xcodegen, your contribution is welcome 😄 
But we need to wait for tuist/XcodeProj#605 at least

**Comment by oscar-odon** [comment]
I have the same issue now. My xcodegen version is the 2.27.0 but I stills havig the issue.

**Comment by alexdmotoc** [comment]
I also have this problem, I have a local SPM package that is included in the main iOS project and I can't figure out how to link the SPM package's tests with the main app, or have them run independently.

**Comment by oscar-odon** [comment]
Hi! @freddi-kit I just try that structure but it stills trhowing me the same error.

My project.yml is now like this:

```
name: SampleApp #Replace this for the name of your test App

## options section ##

options:
  createIntermediateGroups: true
  bundleIdPrefix: com.pomelo
  groupSortPosition: top
  generateEmptyDirectories: true

## packages section ## 

packages:
  MyLibrary:
    path: ./MyLibrary

## targets section ##   

targets:
  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "12.4"
    sources: [SampleApp]
    scheme: 
      build:
        targets:
          SampleApp: all
      testTargets:
      - MyLibrary/MyLibraryTests
    postCompileScripts:
    - script: |
        # check if directory exists then add it to path
        if [ -d ~/.mint/bin ]; then
            echo "Adding ~/.mint/bin to PATH"
            export PATH=~/.mint/bin:$PATH
        else
          echo "~/.mint/bin folder is missing"
        fi

        # check if swiftlint tool can be found.
        if [ $(command -v swiftlint) ]; then
          swiftlint
        else
          echo "Swiftlint tool is missing, try running `sh initial-setup.sh` or run `mint bootstrap --link`"
          exit 1
        fi
      name: Swiftlint
    dependencies:
    - package: MyLibrary
```
