### ISSUE TITLE
Generated info.generate.plist file will be added to Copy Bundle Resources

### ISSUE THREAD

**Issue by mrtsamma** [yonaskolb/XcodeGen#1055]
If I generate info.plist file and use custom naming as `Info.generated.plist` instead of `Info.plist` then it will be added to Copy Bundle Resources.

Generated as:
```
info:
  path: MyApp/Resources/Info.generated.plist
  properties:
    CFBundleDisplayName: "MyApp"
```
Would like to ignore all generated files by adding to `*.generated.*` to gitignore.
Don't want to put straight Info.plist to git ignore cause some statically added frameworks are needing to have it in the repo.

**Comment by alephao** [comment]
Do you have an example project? I tried reproducing here with no success.

But I had a similar issue and I solved using this:

```
```

**Comment by yonaskolb** [comment]
@mrtsamma is this in XcodeGen 2.20.0?
cc @liamnichols

**Comment by liamnichols** [comment]
@mrtsamma, it would be good to identify if this is a new issue you are seeing in 0.20.0 as there is a relevant change that you should be aware of:

> - Fixed files with names ending in Info.plist (such as GoogleServices-Info.plist) from being omitted from the Copy Resources build phase. **Now, only the resolved info plist file for each specific target is omitted.** yonaskolb/XcodeGen#1027

That being said, it does not sound like your **Info.generated.plist** file should be copied as a resource because you _are_ defining it in the spec. If you think that there is a bug here, please could you share the complete **project.yml** spec or even a repo where we can reproduce the bug? 🙏 

Thanks!

**Comment by smaljaar** [comment]
Yes, this looks like a regression. I was running xcodegen 2.18.0 and after upgrade to 2.20.0 the Info.plist is included in the bundle resources. I was including sources in which also the Info.plist files resides. To make the build pass I had to move out the Info.plist file from the included sources and just put it in the root of my project. Since multiple targets have plists I then needed to specify for each target a unique .plist name. Here is the relevant .yml file that made it work after I had to move the Info.plist out of the /TargetFiles path. I'm thinking I will have to do the same things for the test targets.


```
targets:
  TargetName:
    scheme:
      configVariants:
        - production
      testTargets: 
        - TargetTests
    type: application
    platform: iOS
    sources: 
      - path: ../TargetFiles
      - path: ../Shared
      - path: ../Fonts
    settings:
      base:
        INFOPLIST_FILE: Info.plist    
    dependencies:
      - target: NotificationService
        embed: true
        codeSign: false
  NotificationService:
    type: app-extension
    platform: iOS
    sources: 
      - path: ../NotificationService
      - path: ../Shared
    settings:
      base:
        INFOPLIST_FILE: NotificationServiceInfo.plist
```
