### ISSUE TITLE
Skipped tests usage

### ISSUE THREAD

**Issue by yevgenPaykey** [yonaskolb/XcodeGen#1056]
Hello. 
According to documentation:
` skippedTests: [String] - List of tests in the test target to skip. Defaults to empty
`
For me it doesn't work

```
scheme:
      testTargets:
        - name: ClientTests
          randomExecutionOrder: true
          skippedTests: 
            - ApiManagerApiCallTests
```

also 
```
skippedTests: 
            - "ApiManagerApiCallTests"
```

and

`skippedTests: [ApiManagerApiCallTests]`

`randomExecutionOrder` does work for the scheme, but skippedTests don't. Am I missing something?

**Comment by freddi-kit** [comment]
Hello, for my environment it works well with Xcode 2.20.0.

**Comment by freddi-kit** [comment]
Can you try below?

- Check spell of specified test (i should be okay I think)
- Delete generate xcodeproj and re-generate (sometimes xcscheme setting is old remaining)

**Comment by yevgenPaykey** [comment]
> Can you try below? When I had same issue, second thing worked well for me
> 
> 
> 
> - Check spell of specified test (it should be okay I think)
> 
> - Delete generated xcodeproj and re-generate (sometimes old xcscheme setting is remaining)
> 
> 

In Xcode I can skip whole test class, not only separate test methods. So I specify class name. Is it supported?

**Comment by freddi-kit** [comment]
yes, my project is specifying class and works well

**Comment by yevgenPaykey** [comment]
> yes, my project is specifying class and works well

Could you please share your config?

**Comment by freddi-kit** [comment]
ok, but please wait a moment, my app is incompany one so let me make example app

**Comment by freddi-kit** [comment]
https://github.com/freddi-kit/SampleSkippedTest 

I made sample project. Please run xcodegen at root and confirm skipped test in Edit Scheme 

![image](https://user-images.githubusercontent.com/13707872/114743921-1a763680-9d88-11eb-8749-69ccf75aa827.png)

**Comment by yevgenPaykey** [comment]
Ok I think I got it. The issue happens only if test that you want to skip are in different path.

```
ClientTests:
    type: bundle.unit-test
    settings:
      TARGETED_DEVICE_FAMILY: 1
    platform: iOS
    sources:
      - path: ../../OtherClientTests
      - path: ../../folder/folder/ClientTests
    scheme:
      testTargets:
        - name: ClientTests
          randomExecutionOrder: true
          skippedTests: 
            - ClientTestsTests
```

Problem is that 'ClientTestsTests' located in 'OtherClientTests' folder and not "taken into account"
