### ISSUE TITLE
Unable to set SPM dependency as weak

### ISSUE THREAD

**Issue by 4brunu** [yonaskolb/XcodeGen#1061]
Hi,

I added a SPM dependency that is a XCFramework, but I can't set this dependency as weak, although I set it as weak, it's ignored.
I suspect that this is being treated like a static library.

What I want to do is to set the TwilioVideo dependency as optional.

<img width="678" alt="Screenshot 2021-04-23 at 15 59 27" src="https://user-images.githubusercontent.com/784666/115890528-f03e0c00-a44c-11eb-98ae-5f220ac4f75a.png">

```
packages:
  TwilioVideo:
    url: https://github.com/twilio/twilio-video-ios
    exactVersion: 4.4.0
```

```
    dependencies:
    - sdk: SwiftUI.framework
      weak: true
    - package: TwilioVideo
      weak: true
```

Am I doing something wrong, or is this a XcodeGen issue?

Thanks
