### ISSUE TITLE
buildPhase: headers not working

### ISSUE THREAD

**Issue by shakfu** [yonaskolb/XcodeGen#1063]
Hi:

For some strange reason, when I specify `buildPhase: headers`, the corresponding buildPhase is not created in the Xcode project. While this does not prevent successful compilation, it's just weird that everything works well except this. Here's my full spec:

```yaml
name: sndpipe~
options:
  bundleIdPrefix: org.me
targets:
  sndpipe~:
    type: bundle
    platform: macOS
    deploymentTarget: "10.13"
    sources:
      - path: src/sndpipe~.c
        buildPhase: sources
      - path: src/include
        includes: "*.h"
        buildPhase: headers
    dependencies:
      - sdk: CoreFoundation.framework
      - framework: src/lib/libsndfile.a
      - framework: src/lib/libsoundpipe.a
    configFiles:
      Debug: project.xcconfig
      Release: project.xcconfig
    settings:
      CODE_SIGN_IDENTITY: "-"
      DEVELOPMENT_TEAM: ""
      GCC_OPTIMIZATION_LEVEL: 0
      HEADER_SEARCH_PATHS:
        - $(C74SUPPORT)/max-includes
        - $(C74SUPPORT)/msp-includes
        - $(C74SUPPORT)/jit-includes
        - $(PROJECT_HEADERS)
      INFOPLIST_FILE: $(SRCROOT)/../../../Info.plist
      LIBRARY_SEARCH_PATHS: $(PROJECT_LIBS)
      MACOSX_DEPLOYMENT_TARGET: "10.13"
      OTHER_LDFLAGS:
        - $(C74_SYM_LINKER_FLAGS)
        - $(PROJECT_LDFLAGS)
      PRODUCT_BUNDLE_IDENTIFIER: org.me.sndpipe
      PRODUCT_NAME: $(TARGET_NAME)
```
