### ISSUE TITLE
Issues with SettingsGroups

### ISSUE THREAD

**Issue by Daedren** [yonaskolb/XcodeGen#1068]
Hello, not sure if it's me misunderstanding how they work, but I'm having issues with getting settingsGroups to work.

I place something akin to this
```yaml
name: TestProj
settingsGroups:
  watchOS:
    base:
      TARGETED_DEVICE_FAMILY: 4
      WATCHOS_DEPLOYMENT_TARGET: 4.0
  iOS:
    base:
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
options:
  createIntermediateGroups: true
  defaultConfig: Debug
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
targets:
  appLib:
    platform: [iOS, watchOS]
    platformSuffix: "${platform}"
    productName: "appLib${platform}"
    settings:
      groups:
        - "${project}"
      configs:
        ENABLE_BITCODE: YES
    sources:
    - path: appLib/Test.swift
    - path: appLib/Test2.swift
    type: framework
```

But on running xcodegen, I always get  `- Invalid settings group "${project}"`
