### ISSUE TITLE
Currently .xcconfig files on Xcode don't seem to follow the folder hierarchy.

### ISSUE THREAD

**Issue by Elland** [yonaskolb/XcodeGen#1069]
When using the top-level `configFiles:` label to point to individual `.xcconfig` files, it all works correctly, with the exception of how it's currently displayed in the xcode file drawer. The files I'm pointing to are two levels down the file hierarchy (we have a significant amount of them), but on Xcode they're displayed at the top level. Is this a bug, intended behaviour, or did I miss some aspect of the file spec?

Excerpt of `project.yaml` with names changed.

```yaml
configs:
  APP DEV: debug
  APP1: release
  APP2: release
  APP3: release

configFiles:
  APP DEV: SourceFolder/Supporting Files/APP DEV/RND DEV.xcconfig
  APP1: SourceFolder/Supporting Files/APP1/APP1.xcconfig
  APP2: SourceFolder/Supporting Files/APP2/APP2.xcconfig
  APP3: SourceFolder/Supporting Files/APP3/APP3.xcconfig

targets:
  MainTarget:
    type: application
    platform: iOS
    deploymentTarget: "14.4"
    sources: [SourceFolder]
    configVariants:
      - APP1
      - APP2
      - APP3
      - APP DEV
```

On Xcode they show app at the top level as such:

```
-  MainTarget
    - APP DEV
        - APP DEV.xcconfig
     - APP1
         - APP1.xcconfig
     - APP2
         - APP2.xcconfig
      - APP3
         - APP3.xcconfig
```

And the Supporting Files folder appears empty. When inspecting the file locations on Xcode, I can see that it points to the right file, deeper inside the folder structure. Any clues on what's happening is appreciated.

**Comment by freddi-kit** [comment]
`createIntermediateGroups` make keep hierarchy of the generated project and the actual folder one.

```yml
# Write it top of project.yml
options:
   createIntermediateGroups: true
```

Could you help confirming it?
