### ISSUE TITLE
MacOS deploymentTarget is added, when only iOS is specified

### ISSUE THREAD

**Issue by totidev** [yonaskolb/XcodeGen#1079]
I have the following options set:
```yml
options:
  deploymentTarget:
    iOS: 13.0
```
The target that is generated is a Framework, and I have added `platform: iOS` to it.
Yet, when I generate the project, it keeps adding MacOS 10.15 as a target - is there any way to prevent this from being added?
<img width="607" alt="Screenshot 2021-05-13 at 10 17 15" src="https://user-images.githubusercontent.com/3868645/118105574-76a69780-b3d4-11eb-8505-86dd742b5b2b.png">

**Comment by subdigital** [comment]
I have the same issue

**Comment by freddi-kit** [comment]
`` is only overriding the plaform version. Please use `platform` if you want to limit OS in `target`.

https://github.com/yonaskolb/XcodeGen/blob/8bfa2f33e4a7d99eb8b8068bf671c7060b8de63e/Docs/ProjectSpec.md#target

**Comment by subdigital** [comment]
Ah I misread the initial report. I have this:

```
targets:
  MyTarget:
    type: framework
    platform: iOS
    deploymentTarget: 11.0
```

This generates the same result as the picture above.

**Comment by totidev** [comment]
I don't think you did misread it. I stated that I have also set `platform: iOS` as you have in your example.

**Comment by totidev** [comment]
> `deploymentTarget ` is only for overriding the plaform version. Please use `platform` if you want to limit OS in `target`.
> 
> https://github.com/yonaskolb/XcodeGen/blob/8bfa2f33e4a7d99eb8b8068bf671c7060b8de63e/Docs/ProjectSpec.md#target

As I said in my post, I have set the platform to just iOS. I have the deploymentTarget set in the options as I want to specify the iOS version in one place.

**Comment by totidev** [comment]
This is how my target is configured:
```yml
targets:
  SomeFramework:
    type: framework
    platform: iOS
```

**Comment by freddi-kit** [comment]
Ops, I'm sorry. How about setting `TARGETED_DEVICE_FAMILY` as `1` in settings?

**Comment by freddi-kit** [comment]
```yml
targets:
  App:
    type: application
    platform: iOS
    ...
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1 # supports iPhone(1)
```

**Comment by totidev** [comment]
Thanks for the response. If I do that, it now looks like this:
<img width="608" alt="Screenshot 2021-06-04 at 11 57 38" src="https://user-images.githubusercontent.com/3868645/120791471-2aaac680-c52c-11eb-9b18-6c4ddac7f00a.png">

But if I change the TARGETED_DEVICE_FAMILY to `2`, or use `1,2` then MacOS is again automatically selected.

**Comment by totidev** [comment]
Thanks for your help. I realise now the project setup was correct, but that something else must be happening. I now found the answer to this: in your settings you need to add `SUPPORTS_MACCATALYST: NO`, so for example:
```yml
targets:
  App:
    type: application
    platform: iOS
    ...
    settings:
      base:
        SUPPORTS_MACCATALYST: NO
```
