### ISSUE TITLE
Modular app test target

### ISSUE THREAD

**Issue by iamszabo** [yonaskolb/XcodeGen#1088]
First, thanks for all the work put into this great tool!
I'm in a middle of migrating our app to use XcodeGen. It's a modular app containing multiple modules. There is a scheme that contains all the tests to make the testing easier by running all the test targets. When I try to reference a target that is not defined in my project file I get a `Spec validation error: Scheme "AllUnitTests" has invalid build target "OtherModuleTests"` error. Is there any workaround for this?

```
AllUnitTests:
    build:
      targets:
        MainAppTests: test # This works fine as it's defined in this project file
        OtherModuleTests: test # This target is defined outside of the project file
```
