### ISSUE TITLE
Multine post action script is single-line

### ISSUE THREAD

**Issue by jakubkiermasz-zd** [yonaskolb/XcodeGen#1093]
Hi,
I'm having trouble with the multiline script declared as the scheme's post-build action.
The `project.yml` contains:
```
schemes:
  Release:
    build:
      targets:
        TargetName: [archive]
      postActions: 
        - name: Action Name
          script: |
                  one
                  two
                  three
```

The generated script has spaces instead of new lines:
```
one two three
```

It's highly probable, that it's not the issue with my setup. I used the script parameter declared in exactly the same way to generate the target's build phases scripts, and it works like a charm.
