### ISSUE TITLE
Autogenerate source directory

### ISSUE THREAD

**Issue by own2pwn** [yonaskolb/XcodeGen#1099]
I believe it'd be nice to have an option / autogenerate source tree root when you're defining new target. Am I missing an existing option?

**Comment by VaslD** [comment]
Maybe use a template?

I have one globally available on my machine for Swift Packages:

```yaml
targetTemplates:
  SwiftPackage:
    type: framework
    platform:
      - iOS
      - macOS
      - tvOS
      - watchOS
    platformSuffix: " (${platform})"
    sources:
      - path: "../Sources/${target_name}"
        excludes:
          - ReadMe.md
```

The takeaway point is the use of `${target_name}` in templated sources.
