### ISSUE TITLE
XcodeGen crashes when generating schemes with `settingPresets: none`

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#110]
With this configuration:

```yaml
name: Project
configs:
  Debug: none
options:
  settingPresets: none
targets:
  Lyft:
    type: application
    platform: iOS
    sources:
      - Sources
    scheme: {}
```

XcodeGen crashes when [searching for configurations](https://github.com/yonaskolb/XcodeGen/blob/master/Sources/XcodeGenKit/ProjectGenerator.swift#L113-L114). It looks like this config is actually invalid, because it should be `Debug: debug`, but maybe we should at least validate that in the configuration.

Here's a sample project reproducing this issue: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1416705/XcodeGenTest.zip)
