### ISSUE TITLE
Having an empty templateAttributes causes all attributes to be removed.

### ISSUE THREAD

**Issue by CraigSiemens** [yonaskolb/XcodeGen#1101]
Given the following project.yml, `MyTarget` will be created with no template attributes. It seems like if anything contains an empty `templateAttributes`, it all cause all other attributes that may have some from another template to be ignored/removed.

```yml
targetTemplates:
  SomeTemplate:
    templateAttributes:
      someAttribute: "Some Value"
targets:
  MyTarget:
    templates:
    - SomeTemplate
    templateAttributes:
```

It's easy enough to work around by adding any attitude to the target.

```yml
    templateAttributes:
      _:
```

I'd assume xcodegen is trying to merge the dictionaries but the one from the target with no content is possibly being parsed into a string which cant be merged with the existing dictionary. So instead of throwing an error or using the current values in the dictionary, it's returning an empty one.

---

"By why have an empty `templateAttributes` in the first place?" you may be asking.
We have some tooling to automatically update the yml files for various reasons. Having the `templateAttributes` allows us to set where it should appear in the file. If we rely on the scripts to add it when needed, it'd probably be added to either the bottom of the file, or a random location since dictionaries are unordered.
