### ISSUE TITLE
Add a source folder as a group, but with any children folders as a folder

### ISSUE THREAD

**Issue by hiltonc** [yonaskolb/XcodeGen#1117]
I'm working on a Safari web extension which includes a bunch of files and folders in a Resources directory. I need to bundle all of these files and folders, but without a parent "Resources" folder in my app extension. In Xcode it should look like:

<img width="429" alt="Screen Shot 2021-08-17 at 4 59 19 PM" src="https://user-images.githubusercontent.com/470753/129815868-2c0727dc-9728-48c6-b125-e36f767f5339.png">

Unfortunately I can't find a straightforward way to do this with XcodeGen. If I hardcode each path I can do it, but the contents of this folder can change over time and I'd prefer to just pick up those changes from the file system.

I currently have them hardcoded like this:

```
    type: app-extension
    platform: iOS
    sources:
      - Sources
      - path: Resources/assets
        type: file
        buildPhase: resources
        group: Resources
      - path: Resources/background.js
        buildPhase: resources
        group: Resources
      - path: Resources/content.js
        buildPhase: resources
        group: Resources
      - path: Resources/manifest.json
        buildPhase: resources
        group: Resources
      - path: Resources/popup.html
        buildPhase: resources
        group: Resources
      - path: Resources/popup.js
        buildPhase: resources
        group: Resources
```

I'd prefer to be able to just specify the `Resources` path with some configuration to have it treated like this.

Is there already a way to do this, or is this something that can be easily accomodated?
