### ISSUE TITLE
Add ability to use multiple groups for local Swift Package

### ISSUE THREAD

**Issue by hainayanda** [yonaskolb/XcodeGen#1118]
By default, any Swift Package added via xcodegen will be populated into one group named "Packages". It's not always ideal since in my case, I have 2 groups of packages:
- **Local Packages** which contains Application local packages that will be used only by the corresponding apps. These are apps specific features modules. 
- **Shared Packages** which contains packages from git submodules that are shared via multiple apps that use the submodules. This includes common apps functionality modules, like base networking, remote config, utility, etc.

Using the current xcodegen will put all the packages in the same group and will create confusion for my team. I am using git modules because I need to have access to shared packages and the ability to fix and update them right away instead of updating via Swift Package Manager manually.

Can xcodegen have the ability to configure multiple groups for packages instead of using the default Packages group?

**Comment by havebeenfitz** [comment]
@yonaskolb is this a desired feature? I think I could help and make a PR if you don't mind

**Comment by yonaskolb** [comment]
I'm not sure what you mean. Do you mean the `Package Dependencies` section in the navigator? Xcode automatically builds that from your list of resolved Swift packages. Is there a way to do what you're doing without XcodeGen?

**Comment by havebeenfitz** [comment]
As I understand, it's about the `Packages` folder on the top controlled by `localPackagesGroup`. It can only be flat for now, but it would be nice to have the ability to have a hierarchy of folders if needed. Something like:

![Screenshot 2022-02-04 at 11 45 20](https://user-images.githubusercontent.com/31866271/152498754-44f200a7-85df-4c2d-ad50-fc24706e0a3d.png)

**Comment by hainayanda** [comment]
Exactly

**Comment by MartinP7r** [comment]
@hainayanda  have you tried setting the group via the optional parameter added in https://github.com/yonaskolb/XcodeGen/pull/1175?  

You could do something like

```yml
packages:
  AlamofireNetworkClient:
    path: Packages/AlamofireNetworkClient
    group: Packages/Group1
  AppEnvironment:
    path: Packages/Group2/AppEnvironment
    group: Packages/Group2
  ...
```

See [documentation](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#local-package).

**Comment by maxkraev-personal** [comment]
Sorry, but it's not working for me. When I set the package like 

```
packages:
  AppFeature:
    path: Packages/Features/AppFeature
    group: Features/AppFeature
```

and regenerating the project, the groups are not created, and the package is absent. @John-Connolly, could you please guide me on how to use the configuration? I have ` createIntermediateGroups` set to true on the root level, spec validation doesn't find any mistakes

I tried different options like setting the group to the exact path - no luck, unfortunately.
