### ISSUE TITLE
Define settings of mlmodel files

### ISSUE THREAD

**Issue by WesleyJacobsMP** [yonaskolb/XcodeGen#1132]
I've currently been unable to find how to keep my settings of mlmodel files when running xcodegen.
The change done in xcode (Change the model class to not be generated in "Target Membership") results in the following addition in the project file:

`BAF7A3E854C74A605097D91F /* digits.mlmodel in Sources */ = {isa = PBXBuildFile; fileRef = FA1AF80468D8D39346D72A20 /* digits.mlmodel */; settings = {ATTRIBUTES = (no_codegen, ); }; };`

I want to be able to keep that last part (the settings) when running xcodegen.

**Comment by Sherlouk** [comment]
I believe this is the code which powers this:

https://github.com/yonaskolb/XcodeGen/blob/master/Sources/XcodeGenKit/PBXProjGenerator.swift#L685-L698

I too require this change, but for an 'intentdefinition' file, which I want to have look a little something like:

```
25349A18EC6E9EF7D2887BA2 /* Intents.intentdefinition in Sources */ = {isa = PBXBuildFile; fileRef = 4EF78D0C887E7CB991044D30 /* Intents.intentdefinition */; settings = {ATTRIBUTES = (private_codegen, ); }; };
```

I tried setting it using the `attributes` array which is [available in the docs](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-source), but that doesn't seem to work:

```yaml
    sources:
      - path: Intents.intentdefinition
        attributes: 
          - private_codegen
```

**Comment by Sherlouk** [comment]
Found what was broken in my code after looking at https://github.com/yonaskolb/XcodeGen/pull/583 - this issue can probably be closed down as it is supported.

For the original author (@WesleyJacobsMP), add the following YAML to your configuration under the target in which the file is added.

```yaml
    sources:
      - path: PATH/TO/digits.mlmodel
        attributes: 
          - no_codegen
```

The mistake I was making above was that the full configuration had numerous sources, and they're evaluated in a top-down approach with the ones at the top taking higher priority. So I needed to move my Intents attributes property further up the sources array.

Here's my full sources YAML now.

```yaml
    sources:
      - Project.xcassets
      - path: Project/Ext/Widget/Intents.intentdefinition
        attributes: 
          - private_codegen
      - Project/Ext/Widget
```

Notably, the third item in this array, was at position two, which was overriding the attributes I was trying to specify.
