### ISSUE TITLE
Swift Package Products

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#1133]
How do I specify which Swift package products I want to add?

When adding Firebase package directly in Xcode 13, I am presented with this window

![Screen Shot 2021-09-28 at 4 48 59 PM](https://user-images.githubusercontent.com/1013676/135181132-f479d2b5-2ffb-46b9-9266-780ad3f0d638.png)

When adding Firebase with Xcodegen:

```
  Firebase:
    github: firebase/firebase-ios-sdk
    from: 8.8.0
```

I receive an error in Xcode 13 when trying to build: `Missing package product 'Firebase'`

**Comment by brandtdaniels** [comment]
Nevermind, I found the documentation here: https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md#swift-package

**Comment by Kylmakalle** [comment]
I've been also confused about docs in project spec, but solution is really pretty easy.

```yaml
packages:  
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 8.0.0
    
# ...

dependencies:
  - package: Firebase
    product: FirebaseCrashlytics
  - package: Firebase
    product: FirebasePerformance
  - package: Firebase
    product: FirebaseAnalytics
      
# ...

OTHER_LDFLAGS:
    - "-ObjC"
```
