### ISSUE TITLE
`Link binary with libraries`-build phase

### ISSUE THREAD

**Issue by knothed** [yonaskolb/XcodeGen#1138]
Using `xcodegen` with a project.yml which does not have any dependencies will create a project which is missing the "link binary with libraries" build phase.

When subsequently adding an SPM dependency manually in Xcode, building will fail (_Undefined symbol_) because the SPM dependency will not be added to a "link binary with libraries" phase since it is missing.

Is there a way to generate an empty "link binary with libraries" phase using `xcodegen`?

**Comment by armcknight** [comment]
Try adding `link: true` under the SPM package dependency for your target, like so:

```
target: myTarget
  dependencies: 
    - package: mySPM_Dependency
      link: true
```
