### ISSUE TITLE
Multiline script not work?

### ISSUE THREAD

**Issue by bimawa** [yonaskolb/XcodeGen#1148]
When I try to use the multiline script for preActions,postActions a block xcodegen make this script in single line.
![CleanShot 2021-11-14 at 12 20 21@2x](https://user-images.githubusercontent.com/1393809/141671479-a505e204-48e7-400b-af58-77e560b08a8e.png)
It's an issue? Or a feature?

**Comment by Chris-Corea** [comment]
Hi @bimawa - I just happened to come across your question and wondered if you were able to resolve it yourself. For what it's worth, I was able to get multiple lines in a postAction script with the following YAML:
```yaml
postActions:
    - settingsTarget: MyAppTarget
      script: |
          echo "first line"
          echo "new line"
```
Can you paste an example of how you've defined the postAction script in your project config?
