### ISSUE TITLE
Local swift packages don't link correctly if project spec and local packages are not at the project root

### ISSUE THREAD

**Issue by amarantedaniel** [yonaskolb/XcodeGen#1149]
I noticed that when the project spec is in a different folder other than the project root, the local packages paths are not linked correctly.

I have created a repository to demonstrate the issue: https://github.com/amarantedaniel/XcodeGenPackages

It has a config file at the project root and another one inside a folder
when generating the project with the root spec it links the packages correctly.
when generating the project specifying the spec that's inside the folder the packages that are inside folders are not linked correctly.

**Comment by eMdOS** [comment]
Have you tried? ....

```yml
name: XcodeGenPackages
packages:
  TestPackage:
    path: ../TestPackage
  TestPackageInFolder:
    path: ../PackagesFolder/TestPackageInFolder
```
