### ISSUE TITLE
Location Simulation For Test Targets

### ISSUE THREAD

**Issue by KrisRJack** [yonaskolb/XcodeGen#1150]
Hi All!

In a previous issue #722 & #756, Location Simulation was requested and added as a feature in XcodeGen. Is it possible to expand upon this and include location within test targets as well?

Currently, the way to simulate location is by adding the lines below, however, this is limited to normal runs in the simulator and does not work inside a UI test run:
```
run:
  simulateLocation:
     allow: true
     defaultLocation: Honolulu, HI, USA
```

I'm wondering if it's possible to create something like below. I added an image below to show how this would look in the build scheme:
```
test:
      gatherCoverageData: true
      targets:
        - App_iOS_UITests
        - name: App_iOS_Tests
          parallelizable: true
          randomExecutionOrder: true
          location: Honolulu, HI, USA  ### FEATURE REQUEST
```

<img width="846" alt="Screen Shot 2021-11-22 at 1 02 38 PM" src="https://user-images.githubusercontent.com/35638500/143057759-55cf212c-76d0-4689-af56-a1e1e31598b8.png">

![Screen Shot 2021-11-23 at 10 41 37 AM](https://user-images.githubusercontent.com/35638500/143057737-d4c2eead-6dfb-4215-a133-e1772d389712.png)
