### ISSUE TITLE
Having multiple targets share the same Source folder but excluding some files.

### ISSUE THREAD

**Issue by YColdefy** [yonaskolb/XcodeGen#1152]
As an example let's says that I have two targets A and B that share the same source files, with some minor exceptions.

I want to be able to exclude some files that would be only for A in my target B, and vice-versa.

Here is an example of my folder structure:
```
Root Folder
 |
 |-- Source
    |
    | - Screen1
       |
       | - View
           | - ViewState.swift // common file
           | - View_MMA.swift // file specific to A
           | - View_MMB.swift // file specific to B
```

In the XcodeGen settings file I define two targets, setting Source as the source folder and exclude settings for View_MMA.swift and View_MMB.swift:

```
targets:
  MMAPresentation:
    sources: 
      - Source
      - path: Source
        excludes:
          - "**/*_MM[!A].*"

  MMBPresentation:
    sources: 
      - Source
      - path: Source
        excludes:
          - "**/*_MM[!B].*"
```

I then run xcodegen and open the project.

All the files in the project explorer (expected) but when I check the target membership, View_MMA.swift and View_MMB.swift are members of both A and B while I would expect View_MMA.swift to be a member of A only and View_MMB.swift to be a member of B only.

- I did check that my glob expression does match using globster.xyz 
- I did try to exclude one file with it's direct path in the exclude setting, but it was still a member of the targets

Would anyone know what am I doing wrong here?
Maybe the way I'm trying to use sources/excludes itself isn't right? In that case would there be any way to do what I'm trying to do with XcodeGen?

Thank you for your help

**Comment by PaulTaykalo** [comment]
How about simple as 
```
targets:
  MMAPresentation:
    sources: 
      - Source
      - path: Source
        excludes:
          - **/*_MMB.*

  MMBPresentation:
    sources: 
      - Source
      - path: Source
        excludes:
          - "**/*_MMA.*"
```

**Comment by YColdefy** [comment]
Thanks for your answer

I tried but the files target membership is still set to both targets when I check in Xcode.

**Comment by mateuszfidos** [comment]
@YColdefy It's the same if you add `EXCLUDED_SOURCE_FILE_NAMES` in your `xcconfig` file. In `Build Settings` all exclusions are setup correctly but if you select any file you still see double target membership. But even with this double membership somehow Xcode seems to be respecting your exclusion settings. I created two identical files with identical protocols and classes that conform to them and did some testing. Didn't get any `redeclaration` errors and was able to build one target when the other class had some syntax errors. Xcode did omit this broken implementation for one target but did threw an error when I changed targets.

I'm not sure what effect it will have in the long run cause my framework is a work in progress but building targets seems to be working fine and proper files are taken into account. 

But I would definitely like to have this sorted out cause it seems like it's working by accident.

**Comment by YColdefy** [comment]
@mateuszfidos thank you for you comment. In my case I do get the redeclaration errors and am unable to build so that's not working for me :/

**Comment by mateuszfidos** [comment]
@YColdefy try defining `EXCLUDED_SOURCE_FILE_NAMES` in `xcconfig` files. You have to do it per platform but you have `${platform}` to help you. Here's an example:

```
    configFiles:
      Debug: path/to/config/${platform}/Debug.xcconfig
      Release: path/to/config/${platform}/Release.xcconfig
```

and per `xcconfig` something like this:

```
MACOS_FILES = */*/macOS/* */macOS/* */macOS/*/*
EXCLUDED_SOURCE_FILE_NAMES = $(MACOS_FILES)
```

^ is for `iOS` and for`macOS` it's the other way around, you know the drill

**Comment by YColdefy** [comment]
Thanks

In my case I get redeclaration build errors so It would seem that something is different from your setup.

**Comment by adrianramming** [comment]
@YColdefy I faces the same problem. Found out that we need to remove the `- Source` from `Sources:`. So it should look like this: 
```
targets:
  MMAPresentation:
    sources: 
      - path: Source
        excludes:
          - "**/*_MM[!A].*"

  MMBPresentation:
    sources: 
      - path: Source
        excludes:
          - "**/*_MM[!B].*"
```

I know this is an old thread, but maybe it helps someone.
