### ISSUE TITLE
Target type `tool` does not list bundle dependency in Dependencies Build Phase

### ISSUE THREAD

**Issue by armcknight** [yonaskolb/XcodeGen#1155]
It does appear in the Copy Bundle Resources Build Phase, but not in the Dependencies Build Phase. This results in the bundle not appearing at runtime. If I add the bundle target to the tool target's Dependencies Build Phase, then it works.

relevant spec portion:
```
targets:
  createYear:
    type: tool
    sources: [createYear]
    platform: macOS
    deploymentTarget: 10.15
    dependencies:
      - bundle: copyYearResources
  createYearResources:
    type: bundle
    sources: [createYearResources]
    platform: macOS
    deploymentTarget: 10.15
```

result:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/3241469/144744576-1cabaf22-52fc-42db-9b66-6c49eeead43d.png">

expected, which works for my tool at runtime:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/3241469/144744584-75c5f9a7-ac74-4c11-a2c2-25531bdd5585.png">
