### ISSUE TITLE
Feature request: `xpcServices` for copyFiles destination (Sparkle)

### ISSUE THREAD

**Issue by imWildCat** [yonaskolb/XcodeGen#1156]
Background: I'm building a project which is using a xpc bundle for automatic updating (Sparkle).

I'm actually expecting something like:

```yaml
dependencies:
   - bundle: vendors/xpc/my.app.identifier.xpc.InstallerLauncher.xpc
        embed: true
        codeSign: false
        buildPhase:
          copyFiles:
            destination: xpcServices # FIXME: does not work
```

Is it supported now? If not, do you accept a PR to add this support?
