### ISSUE TITLE
Question: Embed a Bundle containing macOS code into a Catalyst framework target

### ISSUE THREAD

**Issue by imWildCat** [yonaskolb/XcodeGen#1157]
Previously, before using `XcodeGen`, I have two targets has this kind of relationship:

<img width="997" alt="image" src="https://user-images.githubusercontent.com/2396817/145059809-a307c2a4-3904-4471-9987-e3934d781f66.png">

during migration, I defined it as

```yaml
  AppKitCatalyst:
    type: framework
    platform: iOS
    sources:
      - AppKitCatalyst
    configFiles:
      Debug: xcconfigs/AppKitCatalyst-Debug.xcconfig
      Release: xcconfigs/AppKitCatalyst-Release.xcconfig
    dependencies:
      - target: LoggerKit
      - target: AppKitBridge
        platformFilter: macOS
        embed: true
        codeSign: true
        copyFiles:
          - destination: plugins
```

However, it generates:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/2396817/145061527-014024d3-a5a3-4022-932d-d80fd35b7a69.png">

Anything I can do to fix it?
