### ISSUE TITLE
*.atlasc folders as resources

### ISSUE THREAD

**Issue by sbaropeak** [yonaskolb/XcodeGen#1166]
Hi, I have a project with dozens of folders *.atlasc, by default xcodegen adds them as groups, by I need them to be added as folders like a bundle folder, or the code is not able to find them.
Since there is a lot of them I don't want to add them one by one. I wonder if there's a way to do it without having to specify each one of them. I have tried many ways playing with the sources properties, but without success. 

For example: Adding a wildcard to the path field
```
targets:
  MyTarget:
    sources:
      - path: MyTarget
        excludes:
          - "**/*.atlasc"
      - path: MyTarget/**/*.atlasc
        type: folder
```

Using wildcards in the path triggers this error: "Spec validation error: Target "MyTarget" has a missing source directory"
I found this [closed issue](https://github.com/yonaskolb/XcodeGen/issues/407), but it seems that it doesn't work the way I want/think. However, I'm not sure if this would give me the desired result, I think it would create more than one group.

xcodegen version: 2.25.0

I have made a change in the code [here](https://github.com/sbaropeak/XcodeGen/blob/atlasc-folders/Sources/ProjectSpec/FileType.swift#L75) to treat atlasc folders as they would be resources and works exactly they way I want. It creates just one group in the xcode project and *.atlasc/ are added as folders instead of groups.

Maybe I'm missing something but is there a way to tell xcodegen something like I want the files/folders of this type to be treated as folder/file/group?

Thanks in advance.

**Comment by yonaskolb** [comment]
Hi @sbaropeak.
Yes, there is a way to configure this in the spec, and that's through fileTypes. Try this:
```yml
options:
  fileTypes:
    atlasc:
      buildPhase: resources
```
See here for docs under `fileTypes` https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#options
