### ISSUE TITLE
How to add Custom Flag - Active Compilation Conditions 

### ISSUE THREAD

**Issue by liauli** [yonaskolb/XcodeGen#1174]
Hello!
I added some custom flags for debug build only, however I couldn't find how to add the flags through XcodeGen. 
How do we add the flags in Target > Build Settings > Custom Flag > Active Compilation Conditions? 
Thanks in advance!

**Comment by VaslD** [comment]
**Almost all Xcode target settings can be migrated this way, including options and check-boxes not in the Build Settings panel. You just to need to find what changed when you, for example, checked a box.**

Then:

1. Highlight the specific setting in Build Settings panel.
2. Press Command + C (or custom keyboard shortcut for system-wide Copy command).
3. Paste in a plain-text editor.
 
You will see something like:

```plaintext
//:configuration = Debug
SWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG

//:configuration = Release

//:completeSettings = some
SWIFT_ACTIVE_COMPILATION_CONDITIONS
```

This gives you the raw key-value to set when editing the Xcode Project property list, which XcodeGen generates/modifies. So in your example, you need to put `SWIFT_ACTIVE_COMPILATION_CONDITIONS` key in a target's `settings` dictionary, and set value to `DEBUG` for debug configuration.

The project spec for XcodeGen would look like:

```yaml
targets:
  MyApp:
    sources:
      - "MyApp"
    settings:
      base:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    templates:
      - "Swift"
```
