### ISSUE TITLE
ResourcesTag do not work

### ISSUE THREAD

**Issue by pengzishang** [yonaskolb/XcodeGen#1183]
There is a font file named "Songti.otf" under the path "GuruClub/Resources/Songti.otf"
I need to add a ResourcesTag to it
I tried like those :
    sources:
      - path: GuruClub/Resources/
        excludes:
            - "Songti.otf"
      - path: GuruClub/Resources/Songti.otf
        resourceTags: ["example", "movie"]

or

    sources:
      - path: GuruClub/Resources/Songti.otf
        buildPhase: resources
        resourceTags:
          - example
          - movie

or 
    sources:
      - path: GuruClub/Resources/Songti.otf
        resourceTags: [movie]

none of them working, it there any mistake or typo in my code?

**Comment by Summys** [comment]
I suppose GuruClub is the name of your project and not a directory inside. What worked for me is 

```
     sources:
      - path: Resources/file.type
        buildPhase: resources
        resourceTags:
          - example
          - movie

**Comment by pengzishang** [comment]
> 

sadly, I tried a code like yours

`targets:
  GuruClub:
    type: application
    platform: iOS
    sources:
      - GuruClub
      - GuruClubFoundationBundle/Localizable
      - path: GuruClub/Resources/Songti.otf
        buildPhase: resources
        resourceTags:
          - example
          - movie`

however, it did not work

**Comment by pengzishang** [comment]
sadly, I tried a code like yours

```
targets:
  GuruClub:
    type: application
    platform: iOS
    sources:
      - GuruClub
      - GuruClubFoundationBundle/Localizable
      - path: GuruClub/Resources/Songti.otf
        buildPhase: resources
        resourceTags:
          - example
          - movie
```

however, it did not work

> I suppose GuruClub is the name of your project and not a directory inside. What worked for me is
> 
> ```
>      sources:
>       - path: Resources/file.type
>         buildPhase: resources
>         resourceTags:
>           - example
>           - movie
> ```

**Comment by yonaskolb** [comment]
Try setting the resourceTags in the first source. Source paths are processed in order and then reused. Does that work?
```
      - path: GuruClub/Resources/Songti.otf
        buildPhase: resources
        resourceTags:
          - example
          - movie
      - GuruClub
```
