### ISSUE TITLE
Swift Package Manager trouble

### ISSUE THREAD

**Issue by rzil** [yonaskolb/XcodeGen#1193]
I want to use xcodegen to add a Swift Package Manager dependency that is a static library. The package in question is The Composable Architecture (https://github.com/pointfreeco/swift-composable-architecture). Following the instructions in the docs, I added these lines to my project.yml file

```
packages:
  swift-composable-architecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.34.0
```

Then later inside my target,

```
      - framework: swift-composable-architecture
        product: ComposableArchitecture
        embed: false
```

Unfortunately, the library is not linked into the target in Xcode, unless I manually add it myself as in the below screenshot.
<img width="389" alt="Screen Shot 2022-03-21 at 3 53 38 pm" src="https://user-images.githubusercontent.com/1035211/159207237-c5ccbdec-7188-4c29-9c89-8d99a2d5c799.png">
Rather, xcodegen is adding a reference to something that doesn't exist as you see below.
<img width="386" alt="Screen Shot 2022-03-21 at 4 01 12 pm" src="https://user-images.githubusercontent.com/1035211/159207702-b14c1069-f230-485c-aa13-167493d457fb.png">
How do I accomplish this correctly?
