### ISSUE TITLE
Follow Xcode to allow copying without requiring embed=true

### ISSUE THREAD

**Issue by shakfu** [yonaskolb/XcodeGen#1206]
Can you please drop the requirement that `embed` should be set to true to allow for copying. This is not a requirement of Xcode. Indeed in my case, it will not work if I embed a Framework, but only if I copy it (without embedding it) so I was hoping for the following to work in xcodegen so as to be consistent with how my current xcode project works (please see screenshot below):

```yaml
name: demo
options:
  bundleIdPrefix: org.me
settings:
  CODE_SIGN_IDENTITY: "-"
  DEVELOPMENT_TEAM: ""
  GCC_OPTIMIZATION_LEVEL: 0
  GCC_NO_COMMON_BLOCKS: No
  HEADER_SEARCH_PATHS:
    - $(PROJECT_HEADERS)
  INFOPLIST_FILE: $(SRCROOT)/../../../Info.plist
  LIBRARY_SEARCH_PATHS: $(PROJECT_LIBS)
  OTHER_LDFLAGS:
    - $(PROJECT_LDFLAGS)
  PRODUCT_NAME: $(TARGET_NAME)
configFiles:
  Debug: project.xcconfig
  Release: project.xcconfig

targets:
  py:
    type: bundle
    platform: macOS
    sources:
      - ../../py.c
    dependencies:
      - sdk: CoreFoundation.framework
      - framework: ../build/lib/Python.framework
        embed: false
        copy: 
          destination: resources
    settings:
      MACOSX_DEPLOYMENT_TARGET: "10.13"
```

<img width="733" alt="screenshot" src="https://user-images.githubusercontent.com/3701918/162250448-394345d1-a74d-419d-90e2-1524e65b6270.png">
