### ISSUE TITLE
Info.plist - duplicated files in build phase 

### ISSUE THREAD

**Issue by KamilGucik** [yonaskolb/XcodeGen#1217]
After generating project ( and running bundle exec pod install ) with two targets: application and test and assingning predefined Info.plist files to them by: 
    settings:
        INFOPLIST_FILE
they are being set in build phases/copy bundle resources, what leads to build fail.a 

```
targets:
  ios:
    type: application 
    platform: iOS
    settings:
      INFOPLIST_FILE: $(SRCROOT)/Sources/ios/Configuration/Files/Info.plist
      PRODUCT_DISPLAY_NAME: ###PROJECT_NAME###
      CODE_SIGN_STYLE: Manual
    sources: 
      - path: ../../Sources/ios
        excludes: 
          - "**/.gitkeep"
    preBuildScripts:
      - name: SwiftLint
        script: |
                ${PODS_ROOT}/SwiftLint/swiftlint --config '.configs/.swiftlint.yml'

  ios-tests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: $(SRCROOT)/Sources/ios-tests/Info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/ios.app/ios
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: ios
    sources:
      - path: ../../Sources/ios-tests
        excludes:
          - "**/.gitkeep"
```
