### ISSUE TITLE
Cannot add testable target from project reference

### ISSUE THREAD

**Issue by piotrsmajek** [yonaskolb/XcodeGen#1253]
I'm trying to add testable target from project reference according to the instructions https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#testable-target-reference 

```
projectReferences:
  Keychain:
    path: Modules/Keychain/Keychain.xcodeproj

targets:
  xyz:
     scheme:
        testTargets:
          - project: Keychain/KeychainTests
```

And unfortunetly it's not working 👎 

Additionaly, there is a typo in instruction:

```
project: {project-reference-name}/{target-name}: Name of local swift package and its target.
```

But this is for project not for swift package 😄
