### ISSUE TITLE
`executable` in Run Action not setting properly

### ISSUE THREAD

**Issue by piotrsmajek** [yonaskolb/XcodeGen#1258]
I have configuration with other app added to project by`projectReferences`

```
projectReferences:
  xyz:
    path: ../Modules/xyz/xyz.xcodeproj
```

and I set 

```
schemes:
  xyz:
    build:
      targets:
        xyz/xyz: all
    run:
      executable: "xyz/xyz"
```

According to the documentation:
![image](https://user-images.githubusercontent.com/52935707/187906820-8cb2a289-da19-4c17-8bd0-9479e28e2c12.png)

And in project I have settings like this after `xcodegen generate`
![image](https://user-images.githubusercontent.com/52935707/187910982-dfbf63db-84bd-4a1b-8f41-57ce641b3577.png)
![image](https://user-images.githubusercontent.com/52935707/187911025-1d81e539-a7d9-4193-ab9d-c1034b703ada.png)

Executable is missing :/ How can I add this properly?
