### ISSUE TITLE
createIntermediateGroups results in broken file refs in projects

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#129]
With this project config:

```yaml
name: Project
options:
  createIntermediateGroups: True
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Sources/Foo/bar.swift
```

The resulting project has broken file refs to `bar.swift`:

![with](https://user-images.githubusercontent.com/283886/32394861-ed1f03b4-c09b-11e7-91ad-691fb4f35832.png)

Example project: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1442410/XcodeGenTest.zip)
