### ISSUE TITLE
CoverageTargets does not work with local package as Testable Target Reference

### ISSUE THREAD

**Issue by thangngoquocOura** [yonaskolb/XcodeGen#1295]
I defined the package:
```
packages:
  MyPackage:
    path: ../MyPackage
```

And used it in:

```
    test:
      config: Release_Debug
      language: en
      region: US
      gatherCoverageData: true
      coverageTargets:
        - MyApp
        - MyPackage/MyPackage
```

Xcodegen complained that `Scheme "Release (Debug)" has invalid project reference "MyPackage"`, also I don't know how to define the target as local package vs project reference, from [here](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#testable-target-reference) the local package and project reference are using the same syntax

**Comment by yonaskolb** [comment]
try:
```
    test:
      config: Release_Debug
      language: en
      region: US
      gatherCoverageData: true
      coverageTargets:
        - MyApp
        - package: MyPackage
```
