### ISSUE TITLE
Using fileGroups with sources results in missing file refs

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#130]
With this config:

```yaml
name: Project
fileGroups:
  - Sources
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Sources/Foo/bar.swift
```

You end up with broken file refs:

![with](https://user-images.githubusercontent.com/283886/32395002-7c5c5946-c09c-11e7-8869-93f686d0d0c0.png)

This is similar to https://github.com/yonaskolb/XcodeGen/issues/129

Example project: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1442422/XcodeGenTest.zip)
