### ISSUE TITLE
How can I set Host Application to main app target on test target for framework?

### ISSUE THREAD

**Issue by takehilo** [yonaskolb/XcodeGen#1302]
I have the following targets:

- MyApp
- MyAppTests
- APIClient (embeded framework)
- APIClientTests

I want to run APIClientTests on device not on Simulator.

APIClientTests target setting is like following:

```yaml
targets:
  APIClientTests:
    dependencies:
      - target: APIClient
        codeSign: false
    platform: iOS
    type: bundle.unit-test
```

Using this setting, Host Application will be `None`.

![image](https://user-images.githubusercontent.com/23430968/209045190-7ee3a77e-c735-4660-97db-5ec68eebc4ca.png)

How can I set Host Application to `MyApp`?
I tried setting `TEST_HOST` to `$(BUILT_PRODUCTS_DIR)/MyApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MyApp` but it didn't work. 

![image](https://user-images.githubusercontent.com/23430968/209045810-bb32594e-26f5-448b-af34-acfe18b22bee.png)
