### ISSUE TITLE
Code generation for intent definition file cannot be disabled

### ISSUE THREAD

**Issue by mathieualvado** [yonaskolb/XcodeGen#1312]
When generating a project with an intent definition file (used for customizing widgets) included in multiple targets, there is no option to disable code generation. This create a duplicated symbol issue when compiling the project.

From https://developer.apple.com/documentation/widgetkit/making-a-configurable-widget:

```
Xcode generates code from the intent definition file. To use this code in a target:
- Include the intent definition file as a member of the target.
- Indicate the specific intents to include in the target by adding the intents’ class names to the Supported Intents section of the target’s properties.

If you include the intent definition file in a framework, you must also include it in the containing app’s target. In that case, to avoid duplicating types in the app and the framework, select No Generated Classes for the app target in the Target Membership section of the File inspector.
```

I tried using the `attributes` field for `sources` but it didn't work. Output should be `settings = {ATTRIBUTES = (no_codegen, )` in the Xcode Project file for files with `No Generated Classes` selected.

Version: 2.26.0

**Comment by mathieualvado** [comment]
@yonaskolb Can I submit a PR to implement support for this feature?

**Comment by yonaskolb** [comment]
Hi @mathieualvado. You should be able to set this with attributes, either for an individual target source path or globally across all file types, though I haven't tested this.

target source:
```
targets:
  MyTarget:
    sources:
        - path: somePath
          attributes: [no_codegen]
```

filetype:
```
options:
  fileTypes:
    intentdefinition: # or whatever the file extension is
      attributes: [no_codegen]
```

Let me know if that works, I just typed them by hand
