### ISSUE TITLE
Add folder/files without target but keeping tree structure

### ISSUE THREAD

**Issue by marcosmko** [yonaskolb/XcodeGen#1314]
Hello all!

Just wondering if I can add files and folders to project without adding to target (like fileGroup) but keeping the tree structure.
Maybe something like this?

```
targets:
  MyApp:
    sources:
      - path: MyApp
        excludes:
          - "Resources/Environments"
    fileGroups:
      - Resources/Environments
```

It would generate the project structure as if I'm not excluding folders AND not adding to the MyApp target.

Thank you very much!

**Comment by yonaskolb** [comment]
I'm writing this off the top of my head, but does this work?
```yml
targets:
  MyApp:
    sources:
      - path: MyApp/Resources/Environments
        buildPhase: none
      - path: MyApp
```

**Comment by marcosmko** [comment]
hey @yonaskolb ! unfortunately it doesn't 😕
it is adding to the root, to target and to build phase

**Comment by Mauricevb** [comment]
I have the same question. I would like to keep MarkDown files visible within Xcode, but they shouldn't be included as a resource in my app.

**Comment by KacperCzapp** [comment]
I found a solution:
```yml
    sources:
     - path: myTarget
       excludes:
         - "**/*.plist"
     - path: myTarget
       includes:
         - "**/*.plist"
       buildPhase: none
```
This adds the files to the project, but not to the target. 

Use the same lists of paths in `includes` and `excludes`, and add `buildPhase: none` in the `includes`.
