### ISSUE TITLE
Catch dependency cycles during validation

### ISSUE THREAD

**Issue by bkase** [yonaskolb/XcodeGen#132]
Right now XcodeGen will just recurse until stack-overflow

**Comment by yonaskolb** [comment]
What sort of dependency cycle? Do you have an example?

**Comment by bkase** [comment]
```
targets:
  A:
    dependencies:
      - B
  B:
    dependencies:
      - A
```

I can come up with a small repro test case if it would be helpful
