### ISSUE TITLE
Product name doesn't reflect the "WRAPPER_EXTENSION" setting

### ISSUE THREAD

**Issue by krishsatya** [yonaskolb/XcodeGen#1321]
I'm building an audio driver that I've set up as a target with type `bundle`. My `.yml` looks something like this:

```
targets:
  MyAudioPlugin:
    type: bundle
    settings:
      base:
        INSTALL_PATH: $(LOCAL_LIBRARY_DIR)/Audio/Plug-Ins/HAL
        PRODUCT_NAME: MyAudioPlugin
        SKIP_INSTALL: true
        WRAPPER_EXTENSION: driver
```

I'd like the final product output to be called `MyAudioPlugin.driver`, however, in Xcode it's displaying as `MyAudioPlugin.bundle`. Strangely though, the actual file output has the correct extension. I'm not sure if I'm using the correct setting or if there's a flag I have to set to override the default naming.
