### ISSUE TITLE
Package declaration doesn't expand settings

### ISSUE THREAD

**Issue by davidberry-nice** [yonaskolb/XcodeGen#1323]
Given the config file (fragment):

```
settings:
  MY_LIBRARY_BRANCH: "feature"

packages:
  MyLibrary:
    url: https://github.com/MyLibrary
    branch: "${MY_LIBRARY_BRANCH}"
```

I would expect the generated files to look for the "feature" branch of my library, but instead Xcode resolve packages gives me an error and reports that it can't find the branch "${MY_LIBRARY_BRANCH}"

Also tried it with `MY_LIBRARY_BRANCH` at file scope and within a "base" tag and none of the above worked.
