### ISSUE TITLE
Autogenerating Schemes With Individual XCConfig Files

### ISSUE THREAD

**Issue by davefoxy** [yonaskolb/XcodeGen#1325]
I'm trying to have xcodegen auto-create individual schemes for different development environments. I have separate .xcconfig files for each of the schemes and build settings I want to create.

The `scheme` object's `configVariants` seemed promising from the docs and so here is what I have:

```yaml
name: MyApp

configs:
  Staging Debug: debug
  Staging Release: release
  QA Debug: debug
  QA Release: release

targets:
  MyApp:
    type: application
    platform: iOS
    scheme:
      configVariants:
        - Staging
        - QA
      testTargets:
        - MyAppTests
    sources:
      - path: MyApp
```

This _does_ create the `MyApp Staging` and `MyApp QA` schemes but it doesn't bring in settings from my xcconfig files. I was a little confused about how this "automagically" might work but I think it might be looking for files with both, in my example, `Staging` and `Release` in the filename as there doesn't seem to be an obvious place to directly refer to the xcconfig file's filename explicitly.

Anyways, it builds ok but none of the xcconfig files' properties are appearing in the generated project's settings. In my case, I have `MyApp-Staging-Debug.xcconfig` and `MyApp-Staging-Release.xcconfig`files in the same directory as my `project.yml`.

Any advice on how to get this particular aspect up and running would be great. Additionally, I'm going to want to move these config files to a separate directory (so not in the same dir as my `project.yml`) so if there's a way I'm missing to do that, it'd be great to find out how 🙏 🙇
