### ISSUE TITLE
Generation Failing With `zsh: trace trap  xcodegen`

### ISSUE THREAD

**Issue by davefoxy** [yonaskolb/XcodeGen#1326]
I'm trying to have my project build multiple schemes which all use different configurations whose values are stored in `.xcconfig` files. I have some luck with using `configVariants` within my target but it appears to require creating both release and debug variations for each build configuration file. Essentially I'm trying to replicate an existing project and it only has separate schemes with their own configuration files.

I looked into the top-level `schemes` object and have the following below however when I run `xcodegen` in the terminal, I'm receiving `zsh: trace trap  xcodegen`. I don't get any validation errors on the project.yml file itself, just this error. Can anyone possibly let me know if this is a bug or where I'm going wrong with my setup?

Thanks

```yaml
name: MyApp

configs:
  Staging: debug

configFiles:
  Staging: MyApp-Staging.xcconfig

schemes:
  MyAppStaging:
    build:
      targets:
        MyApp: all
    run:
      configFile: Staging

targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - path: App
```
