### ISSUE TITLE
Generated project doesn't show live issues and compile errors in code [tvOS]

### ISSUE THREAD

**Issue by vkondrashkov** [yonaskolb/XcodeGen#1332]
I'm using xcodegen both for iOS and tvOS applications. When generating iOS application everything works fine and project shows all necessary errors. 
As for tvOS application generated xcode project doesn't show any auto-complete options, live issues and compiler errors.

Project.yml fragment for tvOS:
```
options:
  minimumXcodeGenVersion: 2.4.0
  deploymentTarget:
    tvOS: 13.0
settings:
  DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  TVOS_DEPLOYMENT_TARGET: 13.0
  SWIFT_VERSION: 5.5
  TARGETED_DEVICE_FAMILY: "3"
  VERSIONING_SYSTEM: apple-generic
  EXCLUDED_ARCHS[sdk=appletvsimulator*]: arm64
targets:
  UnreelAppleTV:
    type: application
    platform: tvOS
```

Maybe i'm missing something? Thanks for any help.
