### ISSUE TITLE
Can't add custom flags with multiple templates

### ISSUE THREAD

**Issue by dungi** [yonaskolb/XcodeGen#1347]
Hey,

I have different schemes, that contains different custom flags, like:

"PUSHNOTIFICATIONS ADS AR"
"PUSHNOTIFICATIONS AR"
""

this is used for:

```
#if AR
do something that only AR tenants can do
#endif
```

in the project.yml I have something like this

```
targets:
  WEATHERAPP_BRASIL_WITH_AR:
    templates:
      - WeatherAppBase
      - ARFeatures
      - ADs
```

how can I dynamically add "AR" or "ADS" or "PUSHNOTIFICATIONS" to `SWIFT_ACTIVE_COMPILATION_CONDITIONS` - if I set `SWIFT_ACTIVE_COMPILATION_CONDITIONS` in the ARFeatures-Template, it will be overridden by the ADs-Template
