### ISSUE TITLE
BUILT_PRODUCTS_DIR doesn't work in sources section

### ISSUE THREAD

**Issue by kmlmsg** [yonaskolb/XcodeGen#1355]
I'm trying to add copyFiles build phase but it returns spec validation error: 
`
Spec validation error: Target "*target*" has a missing source directory "/Users/*user*/Documents/Projects/*folder*/*folder*/*folder*/*folder*/BUILT_PRODUCTS_DIR/AutoStart"
`

```
    sources:
      - path: $(BUILT_PRODUCTS_DIR)/AutoStart
        buildPhase:
          copyFiles:
            destination: wrapper
            subpath: Contents/Library/LoginItems

```

Am I doing something wrong?
