### ISSUE TITLE
Excluding .m files from a target path isn't working

### ISSUE THREAD

**Issue by OmranK** [yonaskolb/XcodeGen#1358]
Trying to exclude some .m files in a directory from being targeted, as I need to specifically declare them one by one and add the right compiler flags to them. When I include them in the excludes list, they do not get excluded. .c files do however get excluded..

Isn't excluded:
```
 sources:
   - path: "MPOS"
      excludes:
          - "/../../aFile.m"
```

Is Excluded:
```
 sources:
   - path: "MPOS"
      excludes:
                - "/../../anotherFile.c"
```                

When built, `anotherFile.c` has the correct compiler flags but `aFile.m` doesn't:
```
- path: "/../../aFile.m"
   compilerFlags: "-fno-objc-arc -w"
- path: "/../../anotherFile.c"
   compilerFlags: "-fno-objc-arc -w"
```
