### ISSUE TITLE
How to specify platform settings for multiplatform target?

### ISSUE THREAD

**Issue by jsorge** [yonaskolb/XcodeGen#1364]
If I have an application project with targets specified below:
```
targets:
  MyApp:
    sources: MyApp
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: 17.0
      macOS: 14.0
    type: application
    settings:
      base:
        SWIFT_VERSION : 5.0
```
How can I add a platform-specific build setting? For example, on the Mac's debug configuration I want to use manual code signing (so that I can build my app in a VM and use provisioning profiles to enable the build and run) but use automatic signing for iOS's debug configuration?
