### ISSUE TITLE
XCodegen wrong generated .xcodeproj

### ISSUE THREAD

**Issue by pedroramos1449** [yonaskolb/XcodeGen#1365]
I am converting my project to use XCodegen, firstly I've made my .yml file, on all my modules.
Here's the project when It doesn't had xcodegen, that's the perfect way it should be:

[![enter image description here][1]][1]

Here's my yml file, that I have made for this CustoJusto, if you look closely the UIComponents shouldn't be on the main targets, but somehow it is.... 
Here's my CustoJusto .yml:

```
name: CustoJusto
include:
  - ../cj-uicomponents/iOS/UIComponents/project.yml
options:
  minimumXcodeGenVersion: 2.25
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "12.3"
targets:
  CustoJusto:
    type: framework
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "pt.custojusto.custojusto"
    scheme:
      gatherCoverageData: true
    sources:
      - path: CustoJusto
        createIntermediateGroups: true
    dependencies:
      - target: UIComponents
      - target: knockerservice
      - target: CoreCustoJusto
      - target: knockercontent
      - sdk: AppTrackingTransparency.framework
      - sdk: CoreTelephony.framework
      - framework: ../cj-pro/shared/build/ios/CustoJustoProShared.xcframework

  CoreCustoJusto:
    type: framework
    platform: iOS
    sources:
      - path: CoreCustoJusto
        createIntermediateGroups: true
    dependencies:
      - sdk: Knocker.framework
      - sdk: HighlanderFoundationKit.framework
      - framework: ../cj-pro/shared/build/ios/CustoJustoProShared.xcframework
     
  CoreCustoJustoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/CoreCustoJustoTests
        createIntermediateGroups: true

  CustoJustoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/CustoJustoUITests
        createIntermediateGroups: true

  knockerservice:
    type: app-extension
    platform: iOS
    sources:
      - path: knockerservice
        createIntermediateGroups: true
    dependencies:
      - target: CoreCustoJusto

  knockercontent:
    type: app-extension
    platform: iOS
    sources:
      - path: knockercontent
        createIntermediateGroups: true

```

Here's the UIComponents .yml:

```



name: UIComponents
options:
  minimumXcodeGenVersion: 2.25
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "15.0"
targets:
  UIComponents:
    type: framework
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "pt.custojusto.UIComponents"
    scheme:
      gatherCoverageData: true
    sources:
      - path: UIComponents
        createIntermediateGroups: true

  UIComponentsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: UIComponentsTests
        createIntermediateGroups: true

```

But instead, with the .yml provided above, it goes like this, when generated...

[![enter image description here][2]][2]

Does anyone knows How to fix this, or can give me some hints? I'm new in this XCodegen thing, and can't find much relative to this, besides the doc.

  [1]: https://i.stack.imgur.com/SOb0J.png
  [2]: https://i.stack.imgur.com/7X413.png

**Comment by pedroramos1449** [comment]
But based on my .yml I don't have it, on my targets:


```
name: CustoJusto
include:
  - ../cj-uicomponents/iOS/UIComponents/project.yml
options:
  minimumXcodeGenVersion: 2.25
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "12.3"
targets:
  CustoJusto:
    type: framework
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "pt.custojusto.custojusto"
    scheme:
      gatherCoverageData: true
    sources:
      - path: CustoJusto
        createIntermediateGroups: true
    dependencies:
      - target: UIComponents
      - target: knockerservice
      - target: CoreCustoJusto
      - target: knockercontent
      - sdk: AppTrackingTransparency.framework
      - sdk: CoreTelephony.framework
      - framework: ../cj-pro/shared/build/ios/CustoJustoProShared.xcframework

  CoreCustoJusto:
    type: framework
    platform: iOS
    sources:
      - path: CoreCustoJusto
        createIntermediateGroups: true
    dependencies:
      - sdk: Knocker.framework
      - sdk: HighlanderFoundationKit.framework
      - framework: ../cj-pro/shared/build/ios/CustoJustoProShared.xcframework
     
  CoreCustoJustoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/CoreCustoJustoTests
        createIntermediateGroups: true

  CustoJustoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/CustoJustoUITests
        createIntermediateGroups: true

  knockerservice:
    type: app-extension
    platform: iOS
    sources:
      - path: knockerservice
        createIntermediateGroups: true
    dependencies:
      - target: CoreCustoJusto

  knockercontent:
    type: app-extension
    platform: iOS
    sources:
      - path: knockercontent
        createIntermediateGroups: true
```
