### ISSUE TITLE
How to have a build settings defined in "base", while customising it further in "config/Release"? 

### ISSUE THREAD

**Issue by acecilia** [yonaskolb/XcodeGen#1371]
Hi 👋 

I have the following spec:
```yaml
...
settings:
  base:
    OTHER_SWIFT_FLAGS:
      - -Xfrontend
      - -warn-long-expression-type-checking=500
      - -Xfrontend
      - -warn-long-function-bodies=1000

  configs:
    Release:
      OTHER_SWIFT_FLAGS:
        - -Xfrontend 
        - -internalize-at-link
...
```

The expectation is that:
* For all configurations, `OTHER_SWIFT_FLAGS` has a value of `-Xfrontend -warn-long-expression-type-checking=500 -Xfrontend -warn-long-function-bodies=1000`
* For release configuration, `OTHER_SWIFT_FLAGS` has a value of `-Xfrontend -warn-long-expression-type-checking=500 -Xfrontend -warn-long-function-bodies=1000 -Xfrontend -internalize-at-link`

The reality is that:
* For all configurations, `OTHER_SWIFT_FLAGS` has a value of `-Xfrontend -warn-long-expression-type-checking=500 -Xfrontend -warn-long-function-bodies=1000`
* For release configuration, `OTHER_SWIFT_FLAGS` has a value of `-Xfrontend -internalize-at-link`

Is there any way to achieve the expected behaviour?

Thanks! 🙏
