### ISSUE TITLE
Is it possible to add URL Types into the project.yml for deeplinking?

### ISSUE THREAD

**Issue by shen-square** [yonaskolb/XcodeGen#1373]
<img width="861" alt="image" src="https://github.com/yonaskolb/XcodeGen/assets/75467072/447a4a7c-4107-4308-8cef-b877d4066ad9">

**Comment by yonaskolb** [comment]
These url types are part of the info plist. If you have an actual `Info.plist` file in the target, using the editor in xcode will make the necessary diff to that file. Looks like the key is called `CFBundleURLTypes`
- If you're using an auto generated info plist through Xcode, you can add the relevant build settings prefixed with `INFOPLIST_KEY_` like `INFOPLIST_KEY_CFBundleURLTypes`
- If you're using XcodeGen to generate the `Info.plist`, you can add the relevant key to the `info.properties` on the target `https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#plist` 

I hope that's enough information to go off

**Comment by theCodingDJ** [comment]
@yonaskolb the `INFOPLIST_KEY_` idea is not working for me, Xcode 15.2, XcodeGen 2.38.0, the values are added to the build settings instead.

Here is an example of my implementation:

```yaml
    application:
      type: application
      platform: iOS
      deploymentTarget: '15.0'
      settings:
        base:
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          OTHER_LDFLAGS: $(inherited) -ObjC
          INFOPLIST_FILE: $(PRODUCT_NAME)-Info.plist
          INFOPLIST_KEY_CFBundleURLTypes:
            - INFOPLIST_KEY_CFBundleTypeRole: Viewer
              INFOPLIST_KEY_CFBundleURLName: "Custom scheme"
              INFOPLIST_KEY_CFBundleURLSchemes:
                - "com.custom-scheme.demo"
```
Unless I am doing something wrong way....?
