### ISSUE TITLE
buildToolPlugins doesn't work for aggregateTargets

### ISSUE THREAD

**Issue by clausjoergensen** [yonaskolb/XcodeGen#1389]
For example:

```
packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    from: 0.52.4
    
aggregateTargets:
  SwiftLint:
    buildToolPlugins:
      - plugin: SwiftLintPlugin
        package: SwiftLint
```

will just generate a empty aggregate target, with no "Run Build Tool Plug-Ins" item.

It works fine doing it manually in Xcode
