### ISSUE TITLE
Disabling Scheme from Target

### ISSUE THREAD

**Issue by vicajilau** [yonaskolb/XcodeGen#1394]
I have a target with several schemes. I would like to delete the schema that is automatically created with the name of the target. Is there any way to disable this functionality of autogenerating the schema from the target?

**Comment by robinmacharg** [comment]
If you're using a target's convenience scheme (i.e. [`TargetScheme`](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme)) you can add a `management` section to either the target directly or, to apply to all targets, to a `TargetTemplate`:

```yaml
# Directly in a target:
targets:
  myTarget:
 # ...
  scheme:
    management:
      isShown: false

# In a target template:
targetTemplates:
  myTemplate:
    # ...
    scheme:
      management:
        isShown: false

targets:
  myTarget:
    templates: [myTemplate]
    # ...
```

The scheme still exists (have a look in Xcode's Manage Schemes dialogue) but is not shown in the drop-down.  You can then add custom schemes that address your targets.

One thing I've not found a way to do is to prevent generation of the default schemes completely.  This seems to interfere with naming your custom scheme the same as a target: the autogenerated scheme supersedes any custom scheme:

```yaml
targets:
  myTarget:
    # ...
    # autogenerated scheme still applies

schemes:
  myTarget: # <-- ignored?
    # ...
```
