### ISSUE TITLE
mlpackage bundles not recognized

### ISSUE THREAD

**Issue by aaron-foreflight** [yonaskolb/XcodeGen#1397]
mlpackage bundles are not recognized as a bundle by xcodegen. These bundles should be treated like a file and added to the compiled sources build phase. It would be nice if xcodegen could support these out of the box.

Here is the configuration I had to use to properly set this up in our project:

```yaml
- path: Sources/FancyMLFeature/models/mypackage.mlpackage
  group: Sources/FancyMLFeature/models
  buildPhase: sources
  type: file

- path: Sources
  excludes:
     - FancyMLFeature/models/mypackage.mlpackage/**
```

More on mlpackage bundles from Apple here:
https://developer.apple.com/documentation/coreml/updating_a_model_file_to_a_model_package
