### ISSUE TITLE
Integration with R.Swift

### ISSUE THREAD

**Issue by razor313** [yonaskolb/XcodeGen#1399]
I'm trying to use R.swift in my project and add it in the `packages` as well as in the `buildToolPlugins` as the following code, but it wasn't in the `Run Build Tool Plug-ins` section after generating *.xcproject file.
Did I define it wrong?

_**Xcodegen: 2.32.0
Xcode: 14.3**_

```
packages:
  RswiftGenerator:
    url: https://github.com/mac-cain13/R.swift
    from: 7.3.2
targets:
  MyApp:
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: RswiftGenerator
```

**Comment by vicajilau** [comment]
I suggest you take a look at the [scripts](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#build-script) that xcodegen allows you to generate within each target. Something like this:

<img width="426" alt="image" src="https://github.com/yonaskolb/XcodeGen/assets/34163765/cb1c2575-db0a-4686-ac60-2f7c8f8dea2c">

I hope this helps you 😃

**Comment by roman-aliyev** [comment]
Try the example bellow with xcodegen 2.37.0:
```yml
targets:
  MyApp:
    ...
    dependencies:
      - package: Rswift
        product: RswiftLibrary
    buildToolPlugins:
      - package: Rswift
        plugin: RswiftGenerateInternalResources
packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift
    from: 7.3.2
```

Also you might consider the plugin within a local package. See the conceptual example here -> mac-cain13/R.swift#838 . Corresponding manifest:
```yml
targets:
  MyApp:
    ...
    dependencies:
      - package: RswiftPlugin
        product: RswiftPluginDependencies
    buildToolPlugins:
      - package: RswiftPlugin
        plugin: RswiftPlugin
packages:
  RswiftPlugin:
    path: Packages/RswiftPlugin
```
