### ISSUE TITLE
[help wanted]Does it support conditional dependencies?

### ISSUE THREAD

**Issue by cdoky** [yonaskolb/XcodeGen#1403]
```yaml
targets:
  iOSApp:
    type: application
    platform: iOS
    deploymentTarget: 11.0
    dependencies:
      - framework: ./Debug.xcframework
        condition: debug
      - framework: ./Release.xcframework
        condition: release
```
Does it support similar conditional dependencies?
