### ISSUE TITLE
Cannot add xcode breakpoints from xcodegen

### ISSUE THREAD

**Issue by alfian0** [yonaskolb/XcodeGen#1408]
Can anyone give me sample how to add breakpoints on the project, because I follow the doc but breakpoint not created on the project

```
breakpoints:
      - type: Symbolic
        symbol: -[UIViewController dealloc]
        enabled: true
        ignoreCount: 0
        continueAfterRunningActions: true
        actions:
          - type: Sound
            sound: Pop
```
