### ISSUE TITLE
Schemes: target/build type map doesn't seem to support non-array strings

### ISSUE THREAD

**Issue by chucker** [yonaskolb/XcodeGen#1411]
I had a scheme like so:

```yaml
schemes:
  MyApp:
    build:
      targets:
        MyApp: all
        MyAppTests: test
```

However, the generated Xcode project showed it (in Xcode) with _all_ build types enabled for _both_ targets.

[The docs seem to say this syntax should work:](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#build) `targets: [String:String] or [String:[String]]`. (I'm assuming the above code is the first of those syntaxes.)

However, I had to change the YAML to be an array for Xcode to do the right thing:

```yaml
schemes:
  MyApp:
    build:
      targets:
        MyApp: all
        MyAppTests: [test]
```
