### ISSUE TITLE
Local packages with custom group not showing in generated project

### ISSUE THREAD

**Issue by JaapManenschijn** [yonaskolb/XcodeGen#1416]
#1175 added the ability to specify a custom group but to me it's not behaving like I would expect it to.

I would expect it to create the group structure i specify, for example:

```
packages:
  AlamofireNetworkClient:
    path: Packages/AlamofireNetworkClient
  AppEnvironment:
    path: Packages/Group2/AppEnvironment
    group: Packages/Group2
  ...
```
This should result in the following structure in Xcode
```
Project
- Packages
    - AlamofireNetworkClient
    - Group2
        - AppEnvironment
```

Instead, the `Group2` and it's content is simply not showing up in the generated project at all.
It will only work if the whole group chain already exists through other means.

The same issue was previously described in #1118.
#1392 also seems to ask about the possibility of doing this.
