### ISSUE TITLE
How to configure Notification Service Extention target?

### ISSUE THREAD

**Issue by sborovikov-belkacar** [yonaskolb/XcodeGen#1420]
Perhaps someone has already solved this problem. Tell me if you know. How can I add a Notification Service Extention target using XcdoeGen?
I just don't see this type of target in XcodeGen.

**Comment by Simimi-dot** [comment]
@sborovikov-belkacar have you solve this problem ? I have a similar situation, I create an app-extension target, but the folder for this target is not created, and because of this, info.plist and entitlements are not created

**Comment by yonaskolb** [comment]
This is the target definition you can use
```
NotificationService:
    type: com.apple.product-type.app-extension
    platform: iOS
    sources:
        - path: NotificationService
```
You'll need an appropriate Info.plist in that directory that XcodeGen doesn't generate for you. You can get one by just creating the target within Xcode.

Let me know if that helps. Closing this for now
