### ISSUE TITLE
Custom `**Info.plist`s target membership is checked

### ISSUE THREAD

**Issue by amirRTA** [yonaskolb/XcodeGen#1423]
Hello,
I have used XcodeGen the Great 🥇 in our application and it works flawlessly unless one little issue with **GoogleService-Info.plist** files. 
I have three **GoogleService-Info.plist** files, each one is related to a separate application environment (develop, stage, and production) and I have to use them in a single xcode target. Following is MyApp structure.
```yaml
targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - path: MyApp
      - path: MyApp/Resources/GoogleService-Infos/DEV/GoogleService-Info.plist
        buildPhase: none
      - path: MyApp/Resources/GoogleService-Infos/INT/GoogleService-Info.plist
        buildPhase: none
      - path: MyApp/Resources/GoogleService-Infos/PROD/GoogleService-Info.plist
        buildPhase: none
```
<img width="276" alt="Screen Shot 2023-12-06 at 09 37 01" src="https://github.com/yonaskolb/XcodeGen/assets/126375828/9f5dc244-888a-43b5-84b7-3a38130b1bed">

<img width="1639" alt="Screen Shot 2023-12-06 at 13 11 21" src="https://github.com/yonaskolb/XcodeGen/assets/126375828/c5535eda-1a5b-4123-a666-4ea533cd78e8">

I added a script in the build phases to select the proper Info.plist file and then copy it inside my app's bundle directory. In this case, I have to set an unselected target membership on them and don't need to have them on copy bundle sources inside build phases.

I tried to set build phases to none for them but it didn't work. This note inside the [project spec > buildPhase](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-source) already mentioned it I guess `Note that Info.plist files will never be added to any build phases, no matter what this setting is.`.
```
      - path: Source/Resources/GoogleService-Infos/INT/GoogleService-Info.plist
        buildPhase: non
```

I'm using the 2.38.0 veriosn of XcodeGen. 
I'm encountering the opposite case of #1045 pls help me THX. 🙏
