### ISSUE TITLE
Local Packages Not Displayed in Project Package Dependencies List

### ISSUE THREAD

**Issue by Faridka0** [yonaskolb/XcodeGen#1436]
Hi,
We have local and remote packages that we add as dependencies to our targets:

```
packages:
  SomeRemote:
    url: https://github.com/yonaskolb/XcodeGen
    version: 2.38.0
  SomeLocal:
    path: Packages/SomeLocal
    
 ...
    
 targets:
  MyApp:
    dependencies:
      - package: SomeRemote
      - package: SomeLocal
```

When you open Project -> Package Dependencies, only external dependencies appear in the list. How can we make local packages show up there as well, or is it possibly a bug in XcodeGen?
In the Xcode interface, there is an option to include local packages in this list.

<img width="1028" alt="Снимок экрана 2024-01-17 в 14 58 52" src="https://github.com/yonaskolb/XcodeGen/assets/34135316/59de1cf9-e259-4508-9d7f-844e420f7101">

Xcode 15.2
XcodeGen 2.37.0
