### ISSUE TITLE
supportedDestinations doesn't work, all platforms are displayed in Xcode

### ISSUE THREAD

**Issue by kekearif** [yonaskolb/XcodeGen#1437]
I am trying to set my target to only support `iPhone` (iOS). Here is my simple setup:

```
name: xcodegen-demo

options:
  bundleIdPrefix: keke
  deploymentTarget:
    iOS: 16.2

targets:
  xcodegen-demo:
    type: application
    platform: iOS
    # iPad, Mac, and Apple Vision still showing in Xcode
    supportedDestinations: [iOS]
    sources:
      - path: xcodegen-demo
```

using `supportedDestinations: [iOS]` doesn't appear to work, after generating the project and opening it in Xcode I can see that all the possible destinations are still available.

![Screenshot 2024-01-21 at 22 33 56](https://github.com/yonaskolb/XcodeGen/assets/10420186/13ffcadb-c8f9-41aa-be02-89fe1363e217)

Is this a bug or am I doing something wrong?
