### ISSUE TITLE
[BUG] Optional source path doesn't work if executing xcodegen from outer directory

### ISSUE THREAD

**Issue by Skoti** [yonaskolb/XcodeGen#1453]
Given a project config:
```yml
name: OptionalSourcePath

targets:
  OptionalSourcePath:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: "First"
      - path: "Second"
        optional: true
```
and a directory structure of:
```
❯ tree dir
dir
├── First
├── Second
└── project.yml

3 directories, 1 file
```

calling xcodegen from within `dir`: 
```bash
cd dir
xcodegen -s project.yml
```
generates a correct Xcode project.

However, calling xcodegen from outside of `dir`:
```bash
❯ basename $PWD
Downloads
❯ ls dir
First  project.yml  Second
❯ xcodegen -s dir/project.yml
```

Generates an Xcode project where the "Second" dir is missing from file tree:
![missing](https://github.com/yonaskolb/XcodeGen/assets/1700160/30f9a3be-50aa-423e-9776-91af4f96e396)
