### ISSUE TITLE
Strange behavior of SwiftUI App

### ISSUE THREAD

**Issue by rsarv3006** [yonaskolb/XcodeGen#1458]
I created an empty SwiftUI project and updated the Content View so that it appears like so:
<img width="439" alt="image" src="https://github.com/yonaskolb/XcodeGen/assets/77516949/becb3062-79d1-4cda-b106-5ee783ae27c9">

I then added my excodegen project file:

`name: TestThing
options:
  bundleIdPrefix: rjs.app.dev.TestThing
targets:
  TestThing:
    type: application
    platform: iOS
    deploymentTarget: "17.2"
    sources: [TestThing]
    info:
      path: TestThing/Info.plist`

And now the view appears as:

<img width="415" alt="image" src="https://github.com/yonaskolb/XcodeGen/assets/77516949/a195456b-4193-4871-9e86-7e0175797b8b">

No other code has changed. I went through the docs and tried to see if there was anything specific to SwiftUI but I did not find anything.

I created a project reproducing the issue and an MR with the diff.

https://github.com/rsarv3006/TestThing/pull/1/files

I'm guessing I'm just missing something obvious but would appreciate any and all input. Thank you!

**Comment by yonaskolb** [comment]
This may be launch screen related. Try either of the following 2 info plist settings
```
UILaunchScreen_Generation: YES
UILaunchStoryboardName: LaunchScreen
```
Let me know how you go

**Comment by kovs705** [comment]
I got the same thing, I fixed it that way, but I think @yonaskolb recommendation is better
```yml
...
    path: App/Info.plist
    info:
      path: YourProjectName/Info.plist
      properties:
        UILaunchScreen:
          UIColor: UIColor.black  #you can change to image as well
```
based on @yonaskolb answer:
```yml
...
    path: App/Info.plist
    info:
      path: YourProjectName/Info.plist
      properties:
        UILaunchScreen_Generation: YES
        UILaunchStoryboardName: LaunchScreen
```
