### ISSUE TITLE
Exclude PrivacyInfo.xcprivacy from Copy Bundle Resources

### ISSUE THREAD

**Issue by arisupriatna14** [yonaskolb/XcodeGen#1459]
How to exclude `PrivacyInfo.xcprivacy` from `Copy Bundle Resource`? Cause, when generate the project.yml is automatically the added into `Copy Bundle Resource` and error occurred when build.

Error Detail
```
Multiple commands produce '/Users/xxxx/Library/Developer/Xcode/DerivedData/xxx-ajimjnjhhtgfrughlwdbsrgcefjx/Build/Products/Debug-iphonesimulator/MyApp.app/PrivacyInfo.xcprivacy'
```

I'm trying to exclude the file like this:
```yml
sources:
  - path: Application/Supporting Files
     excludes:
       - "**/*.xcprivacy"
```
but is that exclude from project not for `Copy Bundle Resource`.

Is there a way to exclude the PrivacyInfo file from the Copy Bundle Resource?

Thanks in advance.

**Comment by arisupriatna14** [comment]
UP!

**Comment by yonaskolb** [comment]
It's possible to add this to a preceding path with an `includes` that sets a custom build phase, but the easiest way is to set a project wide file default
```yml
options:
  fileTypes:
    xcprivacy:
      buildPhase: none
```
I'll open this issue back up though as a marker for someone to open a one line PR to add this as an XcodeGen default here https://github.com/yonaskolb/XcodeGen/blob/9df3e62734fd8a2f5af8f04337ba4d93a4a5370c/Sources/ProjectSpec/FileType.swift#L122
