### ISSUE TITLE
Using 'supportedDestinations' with watchOS app doesn't generate an 'Embed Watch Content' build phase

### ISSUE THREAD

**Issue by FelixLisczyk** [yonaskolb/XcodeGen#1463]
I'm currently in the process of migrating my project specs from `platform` to `supportedDestinations`. According to the project spec, this should work for all target types:

> Note that the definition of supported destinations can be applied to every type of bundle making everything more easy to manage (app targets, unit tests, UI tests etc).

I've noticed when I configure my watch app target with `supportedDestinations`, XcodeGen no longer generates an 'Embed Watch Content' build phase for the iOS app. Here is an example:

```
name: MyApp
options:
  bundleIdPrefix: com.example
targets:
  UniversalApp:
    dependencies:
      - target: WatchApp
    supportedDestinations: [iOS, macOS]
    type: application
    sources:
      - Universal
  WatchApp:
    supportedDestinations: [watchOS]
    type: application
    sources:
      - Watch

```
Is this a bug or intended behavior? Should I continue to use `platform` for my watchOS targets? Thank you!
