### ISSUE TITLE
Specify multiple package products broken

### ISSUE THREAD

**Issue by lionel-alves** [yonaskolb/XcodeGen#1473]
Hi,

Adding multiple product from a swift package doesn't work for me.

relevant part of my `project.yaml`:
```
    dependencies:
      - package: Core
        products:
          - Core
          - CoreUI
```

Core is added correctly but not CoreUI. After the project generation I can add CoreUI manually.
I tried the example [in the Tests](https://github.com/yonaskolb/XcodeGen/blob/master/Tests/Fixtures/SPM/project.yml), that worked for me. Any idea?
