### ISSUE TITLE
fileGroups makes duplicate top level groups

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#150]
With this project config:

```yaml
name: Project
fileGroups:
  - Sources
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Sources
```

And this directory structure:

```
% tree
.
├── Sources
│   ├── Foo
│   │   ├── Foo
│   │   │   └── bar.swift
│   │   └── baz.swift
│   └── foo.swift
└── project.yml

3 directories, 4 files
```

You end up with duplicate top level groups named `Foo`:

![image](https://user-images.githubusercontent.com/283886/32766975-3ab04f2a-c8c6-11e7-8653-685376317ec4.png)

Where the structure should actually match the files on disk.

Example project: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1469821/XcodeGenTest.zip)
