### ISSUE TITLE
Problem with including macros to project locally

### ISSUE THREAD

**Issue by timoninas** [yonaskolb/XcodeGen#1501]
Here I try to include my macros locally into the project. But eventually have this issue in logs:
`Error: external macro implementation type 'MyLocalMacros.MockekeMacro' could not be found for macro 'Mockeke()'`

I'm using 2.42.0 XcodeGen

My yml config:
```yml
name: TemplateProject
options:
  deploymentTarget:
    iOS: "15.0"

settings:
  base:
    MARKETING_VERSION: 1.0

targetTemplates:
  Framework:
    type: framework
    platform: iOS
    settings:
      BUILD_LIBRARY_FOR_DISTRIBUTION: true
    info:
      path: Info.plist

packages:
  MyLocalMacros:
    path: ./../MyLocalMacros   // Here I try to include it

targets:
  TemplateProjectDemo:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    info:
      path: TemplateProjectDemo/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    sources:
      - TemplateProjectDemo
    dependencies:
      - framework: Products/xc/TemplateProject.xcframework
      - package: MyLocalMacros
        linkType: static
        destinationFilters: [iOS, macOS]
      - framework: Products/xc/OtherFramework1.xcframework
      - framework: Products/xc/OtherFramework1.xcframework
      - framework: Products/xc/OtherFramework1.xcframework
```

Could you please provide examples: how to include macros into the project (as local package, or as target, etc)
Because I have faced it today and it's stumbling block for my project :(
