### ISSUE TITLE
How to keep files visible in Xcode but excluded from specific targets

### ISSUE THREAD

**Issue by andywpt** [yonaskolb/XcodeGen#1502]
## Description
In the GUI interface, we can exclude a file from a target by unchecking the checkbox in the target membership section, the excluded file is still visible in Xcode. 

However, when using the **excludes** keyword in XcodeGen, the excluded file is not visible in Xcode.
Is there a way to achieve this? Thanks

```
targets:
  Demo:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    deploymentTarget: 15
    sources:
      - path: Demo
        excludes:
          - "**/*.json" // Cannot edit these files in the generated Xcode project
```
