### ISSUE TITLE
2.42.0 bug: The element XCLocalSwiftPackageReference is not supported when generating mocks with Mockingbird

### ISSUE THREAD

**Issue by KonDouvris** [yonaskolb/XcodeGen#1508]
I have the following problem.

I am using Mockingbird (https://github.com/typealiased/mockingbird) for mocking.
When i am building my test target, i get an error in my `generate mockingbird mocks` custom shell script.

The script is the following:
```
set -eu

# Prevent Xcode 13 from running this script while indexing.
[[ "${ACTION}" == "indexbuild" ]] && exit 0

# Infer the derived data location from the build environment.
[[ -z "${DERIVED_DATA+x}" ]] && DERIVED_DATA="$(echo "${BUILD_ROOT}" | sed -n 's|\(.*\)/Build/.*|\1|p')"

"${DERIVED_DATA}/SourcePackages/checkouts/mockingbird/mockingbird" generate --targets "develop" "developTests"
```

In my project.yml i have the following target:

```
  developTests:
    type: bundle.unit-test
    platform: iOS
    settings:
    dependencies:
      - target: develop
      - package: Mockingbird
    sources:
      - path: appTests
      - path: MockingbirdMocks
        optional: true
    preBuildScripts:
      - path: ./bin/mockingbird.sh
        name: Generate Mockingbird Mocks
        outputFiles:
          - $(SRCROOT)/MockingbirdMocks/developMocks.generated.swift
          - $(SRCROOT)/MockingbirdMocks/developTestsMocks.generated.swift
        basedOnDependencyAnalysis: false

```

The problem started when update xcodegen to `2.42.0`.
I am using MacOS Sequoia 15, and XCode 16.0.0

Any help would be highly appreciated.
Thanks in advance!
