### ISSUE TITLE
Generating entitlements per build configuration

### ISSUE THREAD

**Issue by totidev** [yonaskolb/XcodeGen#1536]
I have added the entitlements option to my app, and it correctly generates an entitlement file. However, is it possible to do this based on configuration? I would like to have different values for debug and release. With the example provided below, I can pass in `development` for aps-enviroment, but how could I do this so that the release configuration uses `production`?

```yaml
entitlements:
  path: App/App.entitlements
    properties:
      aps-environment: development
```
