### ISSUE TITLE
Missing package product when adding local package

### ISSUE THREAD

**Issue by gsabran** [yonaskolb/XcodeGen#1549]
This was mentioned in a resolved thread. I'm not sure if the described fixed is legit: https://github.com/yonaskolb/XcodeGen/issues/721#issuecomment-2196428321

Here's my `project.yml`

```yml
name: FocussedProject.generated
options:
  buildIndependentTargetsInParallel: true
  createIntermediateGroups: true
  deploymentTarget:
    macOS: '15.2'
  developmentLanguage: en
  generateEmptyDirectories: true
  groupSortPosition: top
  minimizedProjectReferenceProxies: true
  minimumXcodeGenVersion: 2.38.0
  transitivelyLinkDependencies: true
  useBaseInternationalization: true
  xcodeVersion: '16.3'
packages:
  AppFoundation:
    path: ./modules/foundations/AppFoundation
  ConcurrencyFoundation:
    path: ./modules/foundations/ConcurrencyFoundation
  DLS:
    path: ./modules/coreui/DLS
  DependencyFoundation:
    path: ./modules/foundations/DependencyFoundation
  FoundationInterfaces:
    path: ./modules/foundations/FoundationInterfaces
  JSONFoundation:
    path: ./modules/foundations/JSONFoundation
  LoggingServiceInterface:
    path: ./modules/serviceInterfaces/LoggingServiceInterface
  ServerServiceInterface:
    path: ./modules/serviceInterfaces/ServerServiceInterface
  SettingsFeature:
    path: ./modules/features/Settings
  SettingsServiceInterface:
    path: ./modules/serviceInterfaces/SettingsServiceInterface
  ThreadSafe:
    path: ./modules/macros/ThreadSafe
settings:
  base:
    SWIFT_VERSION: '6.0'
targets:
  FocusProject:
    dependencies:
    - package: DLS
      products: DLS
    - package: ServerServiceInterface
      products: ServerServiceInterface
    - package: JSONFoundation
      products: JSONFoundation
    - package: SettingsServiceInterface
      products: SettingsServiceInterface
    - package: SettingsFeature
      products: SettingsFeature
    - package: AppFoundation
      products: AppFoundation
    - package: LoggingServiceInterface
      products: LoggingServiceInterface
    - package: DependencyFoundation
      products: DependencyFoundation
    - package: ThreadSafe
      products: ThreadSafe
    - package: FoundationInterfaces
      products: FoundationInterfaces
    - package: ConcurrencyFoundation
      products: ConcurrencyFoundation
    deploymentTarget: '15.2'
    platform: macOS
    requiresObjCLinking: true
    settings:
      GENERATE_INFOPLIST_FILE: 'YES'
    sources:
    - path: FocusProject/Sources
    type: application
```

From what I can tell, Xcode shows an alright configuration:

<img width="885" alt="Image" src="https://github.com/user-attachments/assets/8a92bf2a-bc1a-46b6-b503-98f890e1e9f7" />
<img width="880" alt="Image" src="https://github.com/user-attachments/assets/ac019fa1-02ff-4f5c-bcb9-213625a4fda4" />
<img width="824" alt="Image" src="https://github.com/user-attachments/assets/c5acc737-250c-4ffa-b7a9-a2f3b314fb59" />
