### ISSUE TITLE
Scheme-Parameter parallelizable does not disable parallel testing

### ISSUE THREAD

**Issue by alexdm-e2n** [yonaskolb/XcodeGen#1551]
The parameter `parallelizable` is now threefold, the default evaluating to "Swift Testing Only". (See Screenshot)

![Image](https://github.com/user-attachments/assets/bcdb6c3d-53f3-4372-8fe3-70dc48959b19)

When using the following example, setting parallelizable to false leads to the default, i.e. currently it is not possbile to generate projects with completely serial tests.

```
TestScheme:
    test:
      targets:
        - name: testTargetName
          parallelizable: false
```

Expected: Parallelization Disabled
