### ISSUE TITLE
Sources: Add multiple sources of a target as subgroup of that target

### ISSUE THREAD

**Issue by peymankh** [yonaskolb/XcodeGen#162]
This would be ideal when using multiple targets where each may have one or more than one source path.

An example would be:

``` yaml
targets: 
    TargetA:
        sources: 
            - "Source1"
            - "Source2"
    TargetB:
        sources:
            - "Source3"
```

Currently it results in the following:

```
Source1
Source2
Source3
```

The ideal result would be:

```
TargetA
    Source1
        Contents...
    Source2
        Contents...

TargetB
    Source3 Contents...
```

This would also result in better structure of what the source hierarchy is even if more than one target is sharing the same source path(s).

This presumably cannot be the case if `createIntermediateGroups` is used.
