### ISSUE TITLE
createIntermediateGroups ends up with broken file refs

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#183]
With this project configuration:

```yaml
name: Project
options:
  createIntermediateGroups: True
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Modules/Sources
      - Foo/Sources
```

And this folder structure:

```
.
├── Foo
│   └── Sources
│       └── baz.swift
├── Modules
│   └── Sources
│       └── bar.swift
└── project.yml
```

Running XcodeGen results in a broken project file:

![screen shot 2017-12-05 at 16 32 41](https://user-images.githubusercontent.com/283886/33638237-f12cc034-d9d9-11e7-90e0-6310c3007316.png)

Example setup: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1533449/XcodeGenTest.zip)
