### ISSUE TITLE
Framework dependencies aren't found

### ISSUE THREAD

**Issue by xgalaxy** [yonaskolb/XcodeGen#192]
Here is what my dependency section looks like:
```
    dependencies:
      - framework: Vendor/Realm/Realm_iOS.framework
      - framework: Vendor/Realm/RealmSwift_iOS.framework
```

In XCode under the Frameworks folder they show up with the relative path as the name. And when I try and compile I get this error:
```
ld: framework not found Realm_iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I manually remove and readd the frameworks in XCode it compiles fine.

**Comment by xgalaxy** [comment]
As an aside it would be kind of nice if these didn't show up with the relative path but just the name instead. But I digress.

**Comment by yonaskolb** [comment]
Interesting, I’ll need to debug this. They should indeed be showing up with just the name, and linking correctly.
Are you also adding the vendor directory as a target source? If so, that might be messing things up.

**Comment by yonaskolb** [comment]
Are you able to share more of your spec @xgalaxy? Do you have the `createIntermediateGroups` options on, any `fileGroups`, included `Vendor` or it's sub directories as sources?

**Comment by xgalaxy** [comment]
Yes. Sorry for the delay. Maybe I'm doing something wrong? Thanks for the help.

```
name: Roman
targets:
  Roman_iOS:
    type: application
    platform: iOS
    sources:
      - path: App/iOS
        name: iOS
    dependencies:
      - framework: Vendor/Realm/Realm_iOS.framework
      - framework: Vendor/Realm/RealmSwift_iOS.framework
  Roman_watchOS:
    type: application.watchapp2
    platform: watchOS
    sources:
      - path: App/watchOS
        name: watchOS
    dependencies:
      - framework: Vendor/Realm/Realm_watchOS.framework
      - framework: Vendor/Realm/RealmSwift_watchOS.framework
```
