### ISSUE TITLE
Can't test target as `spec.schemes` doesn't generate testables

### ISSUE THREAD

**Issue by vhbit** [yonaskolb/XcodeGen#193]
Sample code:

```
schemes:
  STCore:
    build:
      targets:
        - target: STCore
          buildTypes: all
        - target: STCoreTests
          buildTypes: testing
    test:
      config: Staging-Debug
    run:
      config: Staging-Debug
    analyze:
      config: Staging-Debug
```

Resulting `STCore` Xcode scheme doesn't have any `Testable` set so it's impossible to test scheme `STCore`

I've checked on 1.4.0 but after a quick look into the code I think it is still presented on master.

**Comment by yonaskolb** [comment]
Yeah that's something that's missing from the expanded scheme spec. It's still a work in progress,  which is why it isn't actually documented. 
In your simple case though you should be able to add the scheme in the target spec.
```
targets:
  STCore:
    scheme:
      testTargets: [STCoreTests]
      configVariants: [Staging,..other variants if you like]    
```
