### ISSUE TITLE
Optional file paths with existing files get duplicated

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#210]
With this project configuration:

```yaml
name: Project
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Sources
      - path: Sources/Foo.swift
        optional: True
```

And this folder structure:

```
.
├── Sources
│   └── Foo.swift
└── project.yml

1 directory, 2 files
```

`Foo.swift` is included twice if it already exists at the time the project file is generated.

Here's an example project demonstrating the issue: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1588462/XcodeGenTest.zip)
