### ISSUE TITLE
Project.yml for the "average" Library

### ISSUE THREAD

**Issue by codeOfRobin** [yonaskolb/XcodeGen#222]
Hey!

I'm trying to build a directory structure fairly similar to how most cross platform libraries are structured.

I'd like to have: 
- 1 `Sources` directory which has most of my core logic
- A directory for each platform that has platform specific logic, of the form `ProjectName-{OS_NAME}`. So, if my library is called `RxDwifft`, the folders are `RxDwifft-iOS`, `RxDwifft-macOS` etc. Each of those targets owns both `Sources` + the OS specific directory
- A common `Tests` Directory, which tests most of my core logic
- Tests specific to each OS with the same layout as above, so the folders are `RxDwifftTests_iOS`, `RxDwifftTests_macOS` etc
- An example app(maybe)

Going with this layout, here's an example `project.yml` I'm considering:

```
name: RxDwifft
targets:
  RxDwifft:
    type: framework
    platform: [iOS, macOS]
    sources: Sources
    scheme:
      gatherCoverageData: true
      testTargets:
        - RxDwifftTest
    dependencies:
      - carthage: RxSwift
      - carthage: Dwifft
  RxDwifftTest:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources: Tests
    dependencies:
      - carthage: RxSwift
      - carthage: Dwifft
      - carthage: SwiftCheck
      - target: RxDwifft
  Example:
    type: application
    platform: [iOS]
    sources: Example
    dependencies:
      - target: RxDwifft
```

Unfortunately, this fails:
```
5 Spec validations errors:
	- Target "Example_iOS" has invalid dependency: "RxDwifft"
	- Target "RxDwifftTest_iOS" has invalid dependency: "RxDwifft"
	- Target "RxDwifftTest_macOS" has invalid dependency: "RxDwifft"
	- Target "RxDwifft_iOS" scheme has invalid test "RxDwifftTest"
	- Target "RxDwifft_macOS" scheme has invalid test "RxDwifftTest"
```

**Comment by yonaskolb** [comment]
Hi @codeOfRobin 
Yes, what you're aiming for is totally possible. See here for details about multi platform targets https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#platform

Basically if a target has multiple platforms, multiple targets will be created. By default these targets will have a `_platform` suffix. Then anywhere within that target specification you can reference the platform dynamically using `$platform` (to for example link to another multi platform target, or include a special source directory).

Your validation errors happen because the target names have changed to gain this prefix, and you aren't referencing them correctly. The error message should be improved to check for cases like this.

This is how you would define the targets. I've included the platform specific source folder in your `RXDwifft` target

```yaml
name: RxDwifft
targets:
  RxDwifft:
    type: framework
    platform: [iOS, macOS]
    sources: 
      - Sources
      - RxDwifft-$platform
    scheme:
      gatherCoverageData: true
      testTargets:
        - RxDwifftTest_$platform
    dependencies:
      - carthage: RxSwift
      - carthage: Dwifft
  RxDwifftTest:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources: Tests
    dependencies:
      - carthage: RxSwift
      - carthage: Dwifft
      - carthage: SwiftCheck
      - target: RxDwifft_$platform
  Example:
    type: application
    platform: iOS
    sources: Example
    dependencies:
      - target: RxDwifft_iOS
```
