### ISSUE TITLE
Add another xcodeproj as a dependency

### ISSUE THREAD

**Issue by codeOfRobin** [yonaskolb/XcodeGen#224]
Hey Yonas!

Lots of times when I'm working on a dependency and an app together (like my swift API client and my app at work), I like to include the API client's xcodeproj (by simply dragging and dropping) so I can make changes and have them appear directly in my app. Is there any good way to support that kind of workflow with xcodegen?

**Comment by yonaskolb** [comment]
Hi @codeOfRobin 
You could reference your API client as an implicit framework dependency, and then add both projects into a workspace.

api client spec
```
targets:
  API:
    type: framework
    ...
```

app spec
```
targets:
  app:
    ...
    dependencies:
      - framework: API.framework
         implicit: true
```

If your API client is simply an existing xcodeproj that will work too.

In the future we could even generate the workspace, as described here #168
