### ISSUE TITLE
Generates non-parsable xcodeproj when a file name contains '@'

### ISSUE THREAD

**Issue by ImLaufderZeit** [yonaskolb/XcodeGen#24]
Using XcodeGen 0.3.0 and Xcode 8.3.3.

If one of files name contains "@", xcodegen generates non-parsable project by Xcode, somehow.
So it cannot deal with retina filenames such as `foobar@2x.jpg`, `foobar@3x.jpg`.
Adding those kind of assets to *.xcassets wouldn't really solve this problem as I intend not to use it, since using xcassets forces UIImage to be cached.

_example:_
```
name: FooBar
targets:
  - name: FooBar
    type: application
    platform: iOS
    sources: 
      - Assets
```

If "Assets" directory or its subdirectory contains a file that has "@" in its name, Xcode cannot parse generated project.
The other tool, `struct`, can correctly generates a project in the same situation, just fwiw.
