### ISSUE TITLE
Platform settings not applied

### ISSUE THREAD

**Issue by thecb4** [yonaskolb/XcodeGen#247]
New to XcodeGen and trying to create a universal framework as a test. However, the below project.yml does not apply the correct base SDK or deployment targets by platform. Not sure what I'm missing.

```yaml
name: GenKit
options:
  usesTabs: false
  indentWidth: 2
  createIntermediateGroups: true
  bundleIdPrefix: io.thecb4
  settingPresets: all
  # deploymentTarget:
  #   iOS: 11.2
  #   tvOS: 11.2
  #   watchOS": 4.1
  #   macOS: 10.13
configs:
  Debug: debug
  Release: release
fileGroups:
  - Framework
targets:
  GenKit:
    type: framework
    platform: [macOS, iOS, tvOS, watchOS]
    sources:
      - Framework/Sources/Core
      - Framework/Sources/$platform
    scheme:
      testTargets:
        - GenKitUnitTests_$platform
        # - GenKitUITests_$platform
      build:
        targets:
          - target: GenKit
            buildTypes: all
          - target: GenKitUnitTests_$platform
            buildTypes: testing
      test:
        config: Debug
      run:
        config: Debug
      analyze:
        config: Debug
      gatherCoverageData: true
      commandLineArguments:
        # "-MyEnabledArg": true
        # "-MyDisabledArg": false
    # settings:
    #   PRODUCT_MODULE_NAME: $(PROJECT_NAME)
    #   PRODUCT_NAME: $(PROJECT_NAME)
  GenKitUnitTests:
    type: bundle.unit-test
    platform: [macOS, iOS, tvOS, watchOS]
    sources:
      - Framework/Tests/Unit/Core
      - Framework/Tests/Unit/$platform
    dependencies:
      # - carthage: RxSwift
      # - carthage: Dwifft
      # - carthage: SwiftCheck
      - target: GenKit_$platform
  # GenKitUITests:
  #   type: bundle.ui-testing
  #   platform: [macOS, iOS, tvOS, watchOS]
  #   sources:
  #     - Framework/Tests/UI/Core
  #     - Framework/Tests/UI/Core/$platform
  #   dependencies:
  #     # - carthage: RxSwift
  #     # - carthage: Dwifft
  #     # - carthage: SwiftCheck
  #     - target: GenKit_$platform
```
