### ISSUE TITLE
Spec decoder's type inference issue

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#253]
Currently this `environmentVariables ` part fails to parse quietly and XcodeGen is not writing it to xcscheme. I debugged a bit, and the value `YES` is mistakenly treated as bool.
```yml
  BitriseClientTests:
    platform: iOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/BitriseClientTests-Debug.xcconfig
    sources:
      - Tests/BitriseClientTests
    dependencies:
      - target: BitriseClient
    scheme:
      testTargets:
        - BitriseClientTests
      gatherCoverageData: true
      environmentVariables:
        - variable: TEST
          value: YES
          isEnabled: true
```

The document demands `environmentVariables` to be `[String: String]`, so the decoder should accept `YES` or `1` as string, too.
