### ISSUE TITLE
Can't target macOS 10.10, becomes 10.1

### ISSUE THREAD

**Issue by LinusU** [yonaskolb/XcodeGen#268]
I have the following deployment targets in my `project.yml`, notice that I _have_ quoted the version in order for yaml to interpret it as a string instead of float.

```yml
name: JSBridge
options:
  bundleIdPrefix: org.linusu
  deploymentTarget:
    macOS: '10.10'
    iOS: '9.0'
targets:
  JSBridge:
    type: framework
    platform: [iOS, macOS]
    sources: Sources
    scheme: {}
    dependencies:
      - carthage: PromiseKit
```

Still, the generated Xcode Project has `MACOSX_DEPLOYMENT_TARGET = 10.1;` 🤔
