### ISSUE TITLE
Add Frameworks as Embedded Binaries

### ISSUE THREAD

**Issue by ImLaufderZeit** [yonaskolb/XcodeGen#27]
I often use Swift dynamic framework and specify them in `xcodegen.yml` like below:

```
name: Foo
targets:
  - name: Bar
    type: application
    platform: iOS
    sources: 
      - Sources
    dependencies:
      - framework: Frameworks/Foo.framework
      - framework: Frameworks/Bar.framework

```

XcodeGen correctly handle this and add those frameworks to `Linked Frameworks and Libraries`, but it seems we do not have an option to have them as `Embedded Binaries`?
