### ISSUE TITLE
Dependencies: dynamic library linkage 

### ISSUE THREAD

**Issue by libe** [yonaskolb/XcodeGen#271]
Hello,

I am having troubles trying to link a dynamic library with the following spec

```yaml
MyFramework:
  type: framework
  platform: iOS
  deploymentTarget: "11.0"
  dependencies: 
    - framework: deps/Curl/libcurl.a
      embed: true
```

When I inspect the Xcode project generated I can see that the library appears in the Link Frameworks section but the at link time I get the error -lcurl not found.

Is linking dynamic libraries supported? From the docs it is not explicitly mentioned it seems.

Thanks again for this great tool!

Libe
