### ISSUE TITLE
Dependency to legacy target

### ISSUE THREAD

**Issue by abeintopalo** [yonaskolb/XcodeGen#286]
Just playing around with dependencies and noticed when a target has a dependency to a `legacy` target then XcodeGen adds the legacy target into the _Copy Bundle Resources_ build phase resulting in build error.

Consider the following snippet:
```
targets:
  MyTarget:
    dependencies:
      - target: Legacy
        embed: false
  Legacy:
    type: ""
```

without explicit `embed: false` as seen above _Legacy_ target is added into the _Copy Bundle Resources_ build phase of _MyTarget_

Maybe embed value as true as default for legacy dependencies would be a better option?
