### ISSUE TITLE
Specify the structure not only alphabetically but also using priorities for folders / files

### ISSUE THREAD

**Issue by radimhalfar** [yonaskolb/XcodeGen#292]
If the project is named starting letter `P` the project is always generated as below. The Product reference folder is placed on top of the file structure. Is there any option to mark the folders with priority of order ? Also If I do have README.md file in the project it is sometimes placed to the top sometimes not. Is it possible to place it always on the top?  
```
Test.xcodeproj
Product
Test
---- Sources
-------- Extension
-------- Scenes
------------ Feature.swift
---- Resources
---- SupportingFiles
```

`project.yml`
```
name: TemplateTest
options:
  bundleIdPrefix: com.test
targets:
  TemplateTest:
    type: application
    platform: iOS
    sources: [TemplateTest]
```

It is probably for another issue but if I specify `excludes` this way:
```
name: TemplateTest
options:
  bundleIdPrefix: com.test
targets:
  TemplateTest:
    type: application
    platform: iOS
    sources: [TemplateTest]
    excludes: 
       - "README.md" 
```
it basically never gets excluded.

**Comment by Alex293** [comment]
+1 (yeah not really original)

**Comment by yonaskolb** [comment]
Yeah at the moment all groups and files are sorted alphabetically.
There could be some special rules for automatically created groups like `Product` and `Frameworks`.
In terms of the other groups they come from various target and project settings, so it's hard to set an orderId somewhere, but it would be possible to have some sort of `sortOrder` option where you could list some paths, and if they are found it would sort those and put everything else afterwards.

As for the `excludes`, that must be set on a source itself not the target, which requires the more verbose form of defining sources:

```yml
name: TemplateTest
options:
  bundleIdPrefix: com.test
targets:
  TemplateTest:
    type: application
    platform: iOS
    sources: 
      - path: TemplateTest
        excludes: 
          - README.md
```
