### ISSUE TITLE
when framework folder isEmpty compile file will lead to  framework not found MyFramework

### ISSUE THREAD

**Issue by a5978445** [yonaskolb/XcodeGen#313]
first show  my `project.yml`:

```yml

name: MyProject
options:
  bundleIdPrefix: com.myapp
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "9.0"
    sources: [MyApp]
    settings:
      CUSTOM_BUILD_SETTING: my_value
    dependencies:
      - target: MyFramework
    removeHeaders: False 
  MyFramework:
    type: framework
    platform: iOS
    sources: [MyFramework]
    deploymentTarget: "9.0"

```

then show my folder ：
<img width="440" alt="2018-05-28 5 22 10" src="https://user-images.githubusercontent.com/11722240/40607657-b5a893b2-629b-11e8-97c9-41bb6a6d0bfa.png">
<img width="522" alt="2018-05-28 5 22 16" src="https://user-images.githubusercontent.com/11722240/40607658-b7828774-629b-11e8-90c8-1528b2fabdd3.png">

and  i will run `xcodegen --quiet`

open `MyProject `, select `MyApp` then run, it will report a link error
 `ld: framework not found MyFramework
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
Carefully check the target configure, i found the` MyFramework`  configure has error:
<img width="886" alt="2018-05-28 5 26 53" src="https://user-images.githubusercontent.com/11722240/40607883-5a0d1766-629c-11e8-8872-d6050b3924ab.png">
there has no `Compile Source` Tab Control，after Manually add `Compile Source` Tab Control, it's build sucess.

* *note：* It is worth noting that if my folder contains can compile files, the issue don't appear
* *version*: 1.9.0

## Example Issue File:
[ExampleShowIssue.zip](https://github.com/yonaskolb/XcodeGen/files/2044530/ExampleShowIssue.zip)
