### ISSUE TITLE
Add sources outside project file's parent folder?

### ISSUE THREAD

**Issue by Piasy** [yonaskolb/XcodeGen#318]
My project structure:

```
- ios_project
    - project.xcodeproj
    - example
- src
- generated_src
    - cpp
    - objc
```

I want include `example`, `../src`, `../generated_src/cpp`, `../generated_src/objc` into my project's sources, below is my `project.yml`:

``` yml
  AudioMixer:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources:
      - example
      - ../src
      - ../generated_src/cpp
      - ../generated_src/objc
```

The problem is, those three groups `src`, `cpp`, and `objc` has wrong path value:

<img width="258" alt="screen shot 2018-06-12 at 00 00 23" src="https://user-images.githubusercontent.com/3098704/41243031-c142e680-6dd3-11e8-829d-4c250ab7f746.png">

It's "Relative To Group", but has an absolute path value, which cause header search failure.

How could I fix it?
