### ISSUE TITLE
Ability to set run options/diagnostics in schemes

### ISSUE THREAD

**Issue by eskerber** [yonaskolb/XcodeGen#325]
If this is something currently supported, let me know and I can make it more clear in the docs.

The "run" options in a scheme have several options that are unable to be set via XcodeGen. Namely those in the "Options" and "Diagnostics" tabs:

![2018-06-28 at 2 07 pm](https://user-images.githubusercontent.com/75236/42055381-97bd8f8e-7adc-11e8-99cd-0d35580b2ae4.jpg)

![2018-06-28 at 2 07 pm](https://user-images.githubusercontent.com/75236/42055412-ae274788-7adc-11e8-9d0a-2b0f2b365880.jpg)

Setting one of these options results in fairly irregular output in the resulting `xcscheme` file:

![2018-06-28 at 2 04 pm](https://user-images.githubusercontent.com/75236/42055268-41217988-7adc-11e8-859d-bb3ea63e3288.jpg)

It would be great to have first-class support for these fields in YAML. i.e.:

```yaml
run:
  enableThreadSanitizer: true
  commandLineArguments:
    "-set-store": false
   ... etc
```
