### ISSUE TITLE
Exclude files syntax (or possible bug?)

### ISSUE THREAD

**Issue by rpassis** [yonaskolb/XcodeGen#363]
Hi there,

Apologies in advance if this is not the right place for asking these questions (feel free to tell me off :) ) but I haven't been able to exclude source files from a generated project

I created a very simple example that reproduces the issue and attached here.

[TestProject.zip](https://github.com/yonaskolb/XcodeGen/files/2239306/TestProject.zip)

Here's my `project.yml` inlined in case you spot any obvious mistakes:

```
name: TestProjectGenerated
targets:
  TestProject:
    type: application
    platform: iOS
    sources:
      - path: TestProject
        excludes:
          - "TestProject/Excluded/**"
```

I also tried a few different variations of the excludes string, even a simple wildcard, but they all seem to be ignored.

Thanks!
Rog
