### ISSUE TITLE
Framework dependency always embedded

### ISSUE THREAD

**Issue by danicoello** [yonaskolb/XcodeGen#372]
I'm having this dependency settings on my target section of project.yml file:

```
dependencies:
      - framework: myFramwork.framework
        embed: false
```

This produces that the "Embedded Binaries Section" contains "My framework" added when this should not happens. If I set "embed" to "true" the same framework is added twice on the same section. In both scenarios the "Linked Frameworks and Libraries" contains the link to framework just one time.

I only want that the framework is linked but not embedded

It appears that framework is always being added in addtion to my settings. What could be happening?

**Comment by brentleyjones** [comment]
Can you post a more complete project.yml (made up names are fine). I’ll take a look at this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danicoello** [comment]
This is the project.yml that I am using.

```
name: MyApp
options:
  xcodeVersion: "9.4.1"
  bundleIdPrefix: "com.myapp"
  deploymentTarget: 
    iOS: "9.3"
configs:
  QA Debug: debug
  QA Release: release
  PROD Debug: debug
  PROD Release: release
settings:
  configs:
    QA Debug:
      DISPLAY_NAME_CUSTOM: "My App QA"
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.MyApp-qa"
      ENVIROMENT: "QA"
    QA Release:
      DISPLAY_NAME_CUSTOM: "My App QA"
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.MyApp-qa"
      ENVIROMENT: "QA"
    PROD Debug:
      DISPLAY_NAME_CUSTOM: "My App"
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.MyApp"
      ENVIROMENT: "PROD"
    PROD Release:
      DISPLAY_NAME_CUSTOM: "My App"
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.MyApp"
      ENVIROMENT: "PROD"
targets:
  MyApp:
    type: application
    platform: iOS
    sources: MyApp
    settings:
      INFOPLIST_FILE: MyApp/Resources/MyApp.plist
      SWIFT_VERSION: "3.3"
      SWIFT_OBJC_BRIDGING_HEADER: MyApp/Resources/MyApp-Bridging-Header.h
      FRAMEWORK_SEARCH_PATHS: [$(inherited), $(PROJECT_DIR), MyApp/AmazonAws]
      CODE_SIGN_ENTITLEMENTS: MyApp/Resources/MyApp.entitlements
      CODE_SIGN_IDENTITY: "iPhone Developer: Developer (XXXXXXXXXX)"
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: "XXXXXXXXXX"
      PROVISIONING_PROFILE: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      PROVISIONING_PROFILE_SPECIFIER: "MyApp Development Provisioning"
    dependencies:
      - framework: MyApp/AmazonAws/AWSMobileHubHelper.framework
        embed: false
    scheme:
      testTargets: 
        - MyAppTests
        - MyAppUITests
      configVariants:
        - QA
        - PROD
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: MyAppTests
    dependencies:
      - target: MyApp
    settings:
      SWIFT_VERSION: "3.3"
      DEVELOPMENT_TEAM: "XXXXXXXXXX"
      INFOPLIST_FILE: MyAppTests/Info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/MyApp.app/MyApp
  MyAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: MyAppUITests
    dependencies:
      - target: MyApp
    settings:
      SWIFT_VERSION: "3.3"
      DEVELOPMENT_TEAM: "XXXXXXXXXX"
      INFOPLIST_FILE: MyAppUITests/Info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/MyApp.app/MyApp
  MyAppPushNotificationExtension:
    type: app-extension
    platform: iOS
    sources: MyAppPushNotificationExtension
    settings:
      SWIFT_VERSION: "3.3"
```

**Comment by yonaskolb** [comment]
Hi @danicoello. As a side comment, it's always cool to see people's `project.yml`. Here are some things you could possibly simplify:

- `settings.configs` can reference partial config names, to remove `debug` vs `release` duplication
- you can provide a `base` settings for common settings, and then remove them from all the targets
- `TEST_HOST` _shouldn't_ be required
- `INFOPLIST_FILE` should be automatically found, unless you have multiple of them in an apps sources

example of settings:
```yml
settings:
  base:
    SWIFT_VERSION: "3.3"
    DEVELOPMENT_TEAM: "XXXXXXXXXX"
  configs:
    QA:
      DISPLAY_NAME_CUSTOM: "My App QA"
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.MyApp-qa"
      ENVIROMENT: "QA"
    PROD:
      DISPLAY_NAME_CUSTOM: "My App"
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.MyApp"
      ENVIROMENT: "PROD"
```

@brentleyjones we should also automatically add any custom framework directories to `FRAMEWORK_SEARCH_PATHS`, if that is required

**Comment by brentleyjones** [comment]
@danicoello: The issue is that you have `AmazonAws` under `MyApp`, which means it gets picked up automatically and is thus being embedded. This wouldn't be an issue if the framework was dynamic and was allowed to be embedded.

A couple ways to fix this:

1. Exclude the `AmazonAws` directory
```yaml
targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - path: MyApp
        excludes:
          - AmazonAws
```

2. Move the `AmazonAws` directory to be outside of `MyApp`

---

@yonaskolb:

`TEST_HOST` is not set anywhere in the code, so it is needed.

`INFOPLIST_FILE` was indeed found correctly.

I'll look into the `FRAMEWORK_SEARCH_PATHS` change. I've noticed needing the same thing on our project.
