### ISSUE TITLE
AggregateTarget dependencies aren't set as dependencies in Xcode

### ISSUE THREAD

**Issue by brentleyjones** [yonaskolb/XcodeGen#376]
```yaml
aggregateTargets:
  Agg:
    buildScripts:
      - name: Carthage Verify
        script: cd $SRCROOT && $SRCROOT/Carthage/carthage-verify.sh
targets:
  App:
    dependencies:
      - target: Agg1
```

I get the error `Target "App" has invalid dependency: "Agg"`

Related, there is no way to make an AggregateTarget depend on another AggregateTarget.
