### ISSUE TITLE
Nested project.yml includes not using relative paths (modular project.yml files)

### ISSUE THREAD

**Issue by keehun** [yonaskolb/XcodeGen#385]
I am importing (copy-pasting) other projects each that have their own `project.yml` files for Xcodegen. Here is the directory structure:

```
- ProjectFolder/
    - project.yml
    - App/
    - AppTests/
    - DependencyA/
        - project.yml
        - DependencyAApp/
        - DependencyATests/
```

In my `ProjectFolder/project.yml`, I define `include: [DependencyA/project.yml]`. In my `DependencyA/project.yml`, I define:

```
name: DependencyAApp
targets:
    DependencyAApp:
        sources:
            - path: DependencyAApp
        scheme:
            testTargets:
                - DependencyATests
    DependencyATests
        sources:
            - path: DependencyATests
        dependencies:
            - target: DependencyAApp
```

When I `cd ProjectFolder` and run `xcodegen`, I get an error saying that `- Target "DependencyATests" has a missing source directory "ProjectFolder/DependencyATests"` whereas I would expect `sources` defined in a `yml` file to be relative to that `yml` file and not the root one including it.

Is there an option flag that I am missing? In this project, I can't use Pods or Carthage. I'm also aware that:
1. I can define `sources` in `DependencyA/project.yml` to include that folder so it looks like `- path: DependencyA/DependencyATests` which then works
2. I can also combine all the `project.yml` files into one file and include `DependencyA/` in the `sources` path

But I don't like either of the solutions as I want to maintain the modularity of the `project.yml` files.

Is this possible?
