### ISSUE TITLE
Problem running tests under macOS

### ISSUE THREAD

**Issue by frankdilo** [yonaskolb/XcodeGen#386]
Hi there, think I have found an issue running `xcodegen` (version `1.11.1`) to generate a project for a `macOS` framework and it's associated test target.

With the configuration below, when I try to run tests I get the following error and tests fail:

```
Test target StatefulTests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
```

```yml
name: Stateful
options:
  bundleIdPrefix: xyz.frankdilo
targets:
  Stateful:
    type: framework
    platform: macOS
    deploymentTarget: "10.13"
    sources: 
      - Sources
      - Supporting Files
  StatefulTests:
    platform: macOS
    type: bundle.unit-test
    sources:
      - Tests
    dependencies:
      - target: Stateful
```

I tracked down the problem to a build setting on the test target. Adding this setting to the settings of the test target fixes running tests for me:

```yml
    settings:
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks"
```

I think this should be the default for tests targets of frameworks under macOS.
