### ISSUE TITLE
Wildcards in source paths (directory component) isn’t working

### ISSUE THREAD

**Issue by rastersize** [yonaskolb/XcodeGen#407]
Hey there :)

I’m trying to copy all resources of a group of features into the app bundle. I have the following directory structure:

```
|- features
|  |- yo
|  |  |- resources
|  |  |  |- cool.json
|  |- foo
|  |  |- resources
|  |  |  |- panda.png
| project.yaml
```

The main `project.yml` file for the App looks something like:
```yaml
name: App

targets:
  App:
    platform: iOS
    type: application
    sources:
      - sources
      - path: "features/*/resources"
        buildPhase:
          - destination: resources

    dependencies:
      # Looks something like, each feature has its own project.yml file as well.
      - framework: Yo.framework
        implicit: true
      - framework: Foo.framework
        implicit: true
```

However when I run `xcodegen` I get a spec validation error. It seems like XcodeGen, or PathKit, isn’t globbing on the directory.
```
📋  Loaded project:
  Name: App
  Targets:
    📱  App: application
⚙️  Generating project...
Spec validation error: Target "App" has a missing source directory "/[…]/xcodegen-resources/features/*/resources"
```

Here’s a [zip file with the setup](http://c.rastersize.com/72557e6574d6/download/xcodegen-resources.zip).

---

I would have expected XcodeGen to find all resource files from yo and foo. That is `cool.json` and `panda.png`.
