### ISSUE TITLE
Add xcodegen to existing project (2 questions)

### ISSUE THREAD

**Issue by menesh2** [yonaskolb/XcodeGen#420]
Hi,
I'm trying to combine Xcodegen on my existing project, 
1. is there a way to generate project.yml file from the existing xcodeproj file or do i need to define all existing setting manually?
 
2. I cant manage to set the Base SDK to iOS
this is my project.yml: 

```YML
name: Gefen 
options: 
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  indentWidth: 2
  tabWidth: 2 
  settings:
    SDKROOT: iphoneos
  bundleIdPrefix: "GEF.Gefen.qa"
  deploymentTarget:
    iOS: 10.3
  configs:
    Debug: debug
    Release: release
  configFiles: 
    Debug: base.xcconfig
    Release: base.xcconfig
  defaultConfig: Release
  developmentLanguage: en
targets: 
  GefenQA:
    configFiles:
      Debug: Pods/Target Support Files/Pods-GefenQA/Pods-GefenQA.debug.xcconfig
      Release: Pods/Target Support Files/Pods-GefenQA/Pods-GefenQA.release.xcconfig
    type: application
    version: 1.37
    build: 297
    platform: iOS
    deploymentTarget: "10.3"
    sources:
      #Sources
      - path: Gefen
```
Am i doing it wrong?
