### ISSUE TITLE
Crash when legacy target is used as dependency 

### ISSUE THREAD

**Issue by abeintopalo** [yonaskolb/XcodeGen#425]
The latest version of XcodeGen crashes with `'xcodegen  -spec project.yml' terminated by signal SIGILL (Illegal instruction)` message when legacy target is used as dependency.

The test `project.yml` file:

```
name: CrashTest
options:
  bundleIdPrefix: com.company.crashtest
  deploymentTarget:
    iOS: 10.0
targets:
  Legacy:
    type: ""
    platform: iOS
    legacy:
      toolPath: /usr/local/bin/sometool
      passSettings: true
  CrashTest:
    name: CrashTest
    type: application
    platform: iOS
    sources:
      - path: CrashTest
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.company.crashtest
    dependencies:
      - target: Legacy
        embed: false
```

If I comment out the `dependencies` section it doesn't crash.
XcodeGen version: 1.11.2
Xcode version: 10
