### ISSUE TITLE
Build / Run Scripts don't end up in generated project

### ISSUE THREAD

**Issue by samedson** [yonaskolb/XcodeGen#438]
Attempting to generate a project with run scripts, and finding that they aren't ending up in the generated project. 

Version: 2.0.0 and 1.11.2

example.yml

```
name: iOSApp
options:
  bundleIdPrefix: ios.app.test.1234512345
targets:
  - name: The-App-iOS
    type: application
    platform: iOS
    deploymentTarget: 10.0
    preBuildScripts:
      - name: ExampleA
        script: ls
    postCompileScripts:
      - name: ExampleB
        script: ls
    postBuildScripts:
      - name: ExampleC
        script: ls
      - name: ExampleB
        path: ls

```

Running `xcodegen --spec example.yml`

I've tried many things, such as adding / removing sources / trying a different script. It just doesn't seem to work. Any idea what is going on?

Thanks!
