### ISSUE TITLE
.intentdefinition file defaults to resource not sources buildPhase attribute

### ISSUE THREAD

**Issue by DanEdgarTarget** [yonaskolb/XcodeGen#439]
While adding an `.intentdefinition` file, I noticed that Xcodegen includes the `.intentdefinition` file as a resource not as a source file.

This causes the normal Xcode compile time code generation which triggers from the `.intentdefinition` to not actually do the codegen for the `.intentdefinition` file so none of the required SiriKit Intent based classes defined in the `.intentdefinition` file appear in the target.

The workaround is just to explicitly set the `buildPhase` to `sources` for the `.intentdefinition` file:
```
sources:
      - path: App/Sources/Application/Routing/Intents.intentdefinition
        buildPhase: sources
 ...
```

It would be good if the default for Xcodegen `.intentdefinition` file type inclusion set the `buildPhase` to `sources` automatically so the manual file include wouldn't be necessary.
