### ISSUE TITLE
build settings - few questions

### ISSUE THREAD

**Issue by menesh2** [yonaskolb/XcodeGen#445]
Hi,
I have some "user defined" build settings that i want to translate in to the `project.yml` file,
but i could not understand how to do it.
for example, on the project file (level):

![screen shot 2018-11-25 at 17 57 44](https://user-images.githubusercontent.com/23659690/48981269-e2e59180-f0db-11e8-9caa-a9426c520f05.png)

or on s specific target: 
![screen shot 2018-11-25 at 17 58 21](https://user-images.githubusercontent.com/23659690/48984971-37543580-f10b-11e8-9480-03fd3715b8f9.png)

how do i define user defined settings?

Another setting is this one:

![screen shot 2018-11-25 at 18 03 30](https://user-images.githubusercontent.com/23659690/48981319-774ff400-f0dc-11e8-9f36-a7659438dcd5.png)

it seems like a 2 levels setting and i could not find any example for it, how do i represent it in the `project.yml`?

thanks a lot for your help

**Comment by yonaskolb** [comment]
Hi @menesh2 
Project and target settings are defined in the same way with a `settings` dictionary, with project settings being on the root of the project spec, and target settings living in each target.
Config specific settings can also be specified with a `configs` map:

An example
```yaml
settings:
  configs:
    Debug:
      MTL_ENABLE_DEBUG_INFO: YES
    Release:
      MTL_ENABLE_DEBUG_INFO: NO
targets:
  MyTarget:
    settings:
      configs:
        Debug:
          PROVISIONING_PROFILE: ""
        Release:
          PROVISIONING_PROFILE: my_provisioning_profile
```

See the documentation here for more info
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md#configuring-build-settings
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#settings
