### ISSUE TITLE
Static framework resources

### ISSUE THREAD

**Issue by esam091** [yonaskolb/XcodeGen#446]
We have a big app that would like to be split into modules, each with their own app target to use for faster iteration. The project structure is more or less like this:
```yml
name: MyProduct
targets:
  App:
    type: application
    sources: App
    dependencies:
      - target: Core
      - target: Cart
      - target: LiveChat
      - target: Home
      - target: SharedUI
      - #other modules
  Core:
    type: framework
    sources: Core
  SharedUI:
    type: framework
    sources: SharedUI
  Cart:
    type: framework
    sources: Cart
    dependencies:
      - target: Core
      - target: SharedUI
  CartExample:
    type: application
    sources: CartExample
    dependencies:
      - target: Cart
  Home:
    type: framework
    sources: Home
    dependencies:
      - target: Core
      - target: SharedUI
  HomeExample:
    type: application
    sources: HomeExample
    dependencies:
      - target: Home
  LiveChat:
    type: framework
    sources: LiveChat
    dependencies:
      - target: Core
      - target: SharedUI
  LiveChatExample:
    type: application
    sources: CartExample
    dependencies:
      - target: LiveChat
  # other modules
```

Each framework has their own resources(xibs, images, etc) and would need to be imported from the App target. We also need the frameworks to be statically loaded. The problem we're encountering is with static frameworks, there is no way to reference the resource from the framework.

For the current workaround, we have to manually put references in the main app.

```yml
targets:
  App:
    sources:
      - App
      - Cart:
        excludes: '*.swift'
      - Home:
        excludes: '*.swift'
      - LiveChat:
        excludes: '*.swift'
  HomeExample:
    sources:
      - HomeExample
      - Home:
        excludes: '*.swift'
  CartExample:
    sources:
      - Cart
      - CartExample:
        excludes: '*.swift'
# etc     
```

It works, but it feels very tedious to do this every time. Do you already have a solution for this that I didn't know of? If not, I think it would be useful to make a new target, `framework.static` for example that automatically copies framework resources to app targets.
