### ISSUE TITLE
Ability to set a couple of project/target settings?

### ISSUE THREAD

**Issue by smackie** [yonaskolb/XcodeGen#449]
As I work through converting our (huge) project files to xcodegen, I've found a couple of things that I can't resolved. I've looked at the Swift so I'm guess these aren't supported (yet) but figured I'd ask

- Project flag to turn off automatically generating schemes for every target. Ideally just for a list of targets and/or a class of target. For example, I have a *lot* of libraries. Don't need schemes for them. But schemes for the gtest applications and final apps would be fine.

- Target flag to disable copying headers. I don't really need them to be copied and I'd probably prefer just to suppress the "copy headers" step. Being able to flip the "Only copy on install" option would be a good workaround.

Any thoughts? The first seems relatively straightforward as part of the project definition. The second looks tricker from the code but flipping the "Only copy on install" option might be easier depending on what xcodeproj supports (I guess).

Cheers!

Scott...

**Comment by smackie** [comment]
Dug down a bit into the second issue a bit. It does look like there's logic in the code to suppress copying when the target is a static library but this doesn't appear to be working. For reference, the target looks like this

```
  foo-log:
    type: library.static
    platform: macOS
    sources:
      - path: foo/foo-log
        excludes:
          - "unit-test"
          - "Makefile*"
          - "src/Makefile*"
          - "*.mk"
```
I have loads of targets like this (the xcode build is overlaid on top of native linux build). The actual directory layout is

```
foo -+- src
     +- unit-test
     +- include
```

There are headers in the src directory too. If I get a chance, I'll try to run the config through with xcodegen in the debugger to see what's happening in in the target generation code.
