### ISSUE TITLE
Inconsistent CompilerFlags under Source

### ISSUE THREAD

**Issue by keehun** [yonaskolb/XcodeGen#453]
I believe this is a 2.0 regression, as it worked fine before updating `xcodegen` to 2.0 this afternoon:

```yaml
targets:
  App:
    sources:
      - path: "Classes/SBJSONParser+ObjectWithData.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Frameworks/JSON/NSObject+SBJSON.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Frameworks/JSON/NSString+SBJSON.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Frameworks/JSON/SBJSON.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Frameworks/JSON/SBJsonBase.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Frameworks/JSON/SBJsonParser.m"
        compilerFlags: "-fno-objc-arc -w"
      - path: "Frameworks/JSON/SBJsonWriter.m"
        compilerFlags: "-fno-objc-arc"
```
results in the following compiler flags set under `Build Phases > Compile Sources`:
![Xcode Build Phases Screenshot](https://i.imgur.com/pwe5Gic.png)

This is what the file directory looks like in Finder:
![File Directory Screenshot](https://i.imgur.com/8KZdHUu.png)

Again, this was working fine before the 2.0 update.

It seems to improve when I randomly change the capitalization of the `path`s such as `SBJSONWRITER.m` instead of `SBJsonWriter.m` but nothing consistent. `SBJSONWriter.m` also makes the flag appear. Everything I've tried for `SBJSON.m` doesn't help its case, it seems.

Here's my system specs/versions:
- 2017 15" MBP
- macOS 10.14
- 2.9GHz i7
- 16GB Memory
- 1TB APFS volume
- `xcodegen --version` prints `2.0.0`

**Comment by keehun** [comment]
To give a little more details: I can't find any pattern to it, but it is deterministic (deleting and regenerating the file doesn't cause a different set of files to get their compiler flags to be correctly set). It's not limited to a single folder. Some files work under one folder and not others. File permissions are consistent across files that get their compiler flags set as well as the ones that don't get set. My APFS volume is case-insensitive.

**Comment by yonaskolb** [comment]
Hmm, very strange. This sounds similar to the things @LinusU found in https://github.com/yonaskolb/XcodeGen/issues/405

**Comment by keehun** [comment]
Indeed! For now, I'm working around it by only manually triggering `xcodegen` after significant changes like new files and manually entering in my compiler flags (thatkfully, I have less than 15), but hope it will be resolved, soon!

**Comment by keehun** [comment]
@yonaskolb, are you able to reproduce this?

**Comment by LinusU** [comment]
@yonaskolb did you try this test case? https://github.com/yonaskolb/XcodeGen/compare/master...LinusU:warning-test-case

Let me know if there is anything I can do to assist further, would love to get this resolved :relaxed:

**Comment by yonaskolb** [comment]
@LinusU if you could create a PR with a failing unit test that would help a lot. Same with your issue @keehun

**Comment by keehun** [comment]
@yonaskolb , I will contribute something to that extent when I am able, but I don't foresee being able to do that any time soon.

**Comment by keehun** [comment]
@yonaskolb, I've been debugging the application a bit over the holidays, and so far, I've determined that all the compiler flags get parsed correctly from both YAML and JSON specs, and all of them are there at `SourceGenerator.swift:generateSourceFile`. Some of them are missing by the time it gets to `PBXProjGenerator.swift:getBuildFilesForSourceFiles`, and those that are missing are consistent with those missing in the resulting `xcodeproj` file.

**Comment by keehun** [comment]
@yonaskolb, I've tracked it down: it happens in `PBXProjGenerator.swift:getBuildFilesForSourceFiles`. More specifically, it happens in `sourceFiles.reduce` because there exist duplicates. This is my `project.yml`:

```yml
sources:
      - path: "Platform
        excludes:
          - "*/ClassA.m"
          - "*/ClassB.m"
          - "*/ClassC.m"
      - path: "Platform/SomeFolderStructure/ClassA.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Platform/SomeFolderstructure/DeeperStructure/ClassB.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Platform/Folders/ClassC.m"
        compilerFlags: "-fno-objc-arc -w"
```

Now, when I remove the last three files in that `sources` array, `ClassA.m`, `ClassB.m`, and `ClassC.m` are properly excluded from the Project and Targets. When I add the last three file items into `sources`, then I get duplicates in `sourceFiles` of `PBXProjGenerator.swift:getBuildFilesForSourceFiles`. This is the code I used to detect duplicates:

```swift
let crossReference = Dictionary(grouping: sourceFiles, by: { $0.path.description })
let duplicates = crossReference.filter { $1.count > 1 }     
print(duplicates.keys)```

And in `duplicates`, I do get `ClassA.m`, `ClassB.m`, and `ClassC.m` keys.

Is there perhaps a regression for `excludes` when the a file matching that rule exists elsewhere in `sources`?

**Comment by keehun** [comment]
Upon further inspection, I am realizing that this entire issue was caused by my incorrect `exclude` rules. This would have been avoided by clearer documentation on the part of `Xcodegen`. It looks like excludes rules are just standard glob rules, and the `exclude` rules that I had written were incorrect. (The fact that `excludes` are just standard `glob` rules was gleaned from [`SourceGenerator.swift:getSourceExcludes()`](https://github.com/yonaskolb/XcodeGen/blob/7e2c8707629e2f96c2451a9628b27cfee53e0e79/Sources/XcodeGenKit/SourceGenerator.swift#L296).)

Perhaps `xcodegen` can output a warning when duplicate files are found when generating the file? If I had `xcodegen` tell me that I had duplicate entries for files, I would have been able to deduce early-on that my `exclude` rules were incorrectly written—not doing what I wanted it to do.

What I had done wrong in my `exclude` rules was that I did not know that the glob rule was relative to the `path` of that source item. For example, doing:
```yml
sources:
      - path: "Platform/SomeFolderStructure/ClassA.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Platform/SomeFolderstructure/DeeperStructure/ClassB.m"
        compilerFlags: "-fno-objc-arc"
      - path: "Platform/Folders/ClassC.m"
        compilerFlags: "-fno-objc-arc -w"
      - path: "Platform"
        excludes:
          - "*/ClassA.m"
          - "*/ClassB.m"
          - "*/ClassC.m"
```
Only `ProjectParentDirectory/Platform/*/ClassA.m` was excluded, not `ProjectParentDirectory/*/ClassA.m`.

In the mean time, I will add a PR which updates the documentation to make the `exclude` rules clear. Now that my exclude rules are correct, all `compilerFlags` are being added correctly!
