### ISSUE TITLE
Project Configurations through YML file

### ISSUE THREAD

**Issue by joris1995** [yonaskolb/XcodeGen#455]
How can I achieve custom Project Configurations like in the screenshot with a YML file.
<img width="1399" alt="schermafbeelding 2018-12-06 om 23 19 18" src="https://user-images.githubusercontent.com/44894683/49615991-950c3b80-f9af-11e8-865b-251d9a943e85.png">

I expected to be able to do it like this, like the [docs](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#configs) say:
```
name: Test1
settings:
  configs:
    Alpha: alpha-com.company.Test1
    Beta: beta-com.company.Test1
    Debug: debug-com.company.Test1
    Release: com.company.Test1
options:
  bundleIdPrefix: com.company
targets:
  Test1:
    type: application
    platform: iOS
    sources: Test1
  Test1Tests:
    type: bundle.unit-test
    platform: iOS
    schemetestTargets: Test1Tests
    sources: Test1Tests
```

But this doesn't work. I have tried several options, like removing the settings Level above it, placing it in the target setting with & without config level. Any help would be much appreciated

**Comment by yonaskolb** [comment]
Hi @joris1995 

If you have configs other than `Debug` and `Release` they have to be defined first, with each one saying whether it contains the default `debug` or `release` settings. https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#configs

Then the format for config specific settings is slightly different from what you have above
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#settings

```yml
configs:
  Alpha: release
  Beta: release
  Debug: debug
  Release: release
targets:
  Test1:
    settings:
      configs:
        Alpha:
          PRODUCT_BUNDLE_IDENTIFIER: alpha-com.company.Test1
        Beta:
          PRODUCT_BUNDLE_IDENTIFIER: beta-com.company.Test1
        ...
```

I hope that answers your question. Let me know how you get on
