### ISSUE TITLE
Unit tests generating

### ISSUE THREAD

**Issue by raptorxcz** [yonaskolb/XcodeGen#460]
Hi, 

I am trying to generate my project by XcodeGen. Main target is working, but unit tests are not.

Here is my _project.yml_ file. In Tests target is missing framework as _Target dependency_.

<img width="860" alt="screenshot 2018-12-20 at 15 01 24" src="https://user-images.githubusercontent.com/3967087/50289119-2972a580-0468-11e9-87ca-06beaa35c160.png">

```yml
name: Models
options:
  carthageBuildPath: "../../Carthage/Build"
  groupSortPosition: top
targets:

  
  
  
  
  
  
  
  
  
  
  
  Models:
    type: "framework"
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      
      - Models
      
      - Models-iOS
      
    settings:
      base:
        
        APPLICATION_EXTENSION_API_ONLY: 'YES'
        
        INFOPLIST_FILE: 'Generated Supporting Files/FrameworkInfo.plist'
        PRODUCT_BUNDLE_IDENTIFIER: Models
        PRODUCT_NAME: Models
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Automatic
    dependencies:
      
      - sdk: CoreLocation.framework
      
      
      
      
      - carthage: CleanCore
      
      - carthage: CleanPlatform_iOS
      
      - carthage: Swinject
      
      - carthage: SwinjectAutoregistration
      
      - carthage: SWXMLHash
      
      
      
    
    scheme:
      testTargets:
        - ModelsTests
      gatherCoverageData: false
  ModelsTests:
    sources:
      - ModelsTests
    settings:
      base:
        INFOPLIST_FILE: 'Generated Supporting Files/FrameworkTestsInfo.plist'
        PRODUCT_BUNDLE_IDENTIFIER: ModelsTests
        PRODUCT_NAME: ModelsTests

        FRAMEWORK_SEARCH_PATHS: '$(inherited) $(PROJECT_DIR)/../../Carthage/Build/iOS'
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    type: bundle.unit-test
    platform: iOS
    depencencies:
      - target: Models
      
      - sdk: CoreLocation.framework
      
      
      
      - carthage: CleanCore
      
      - carthage: CleanPlatform_iOS
      
      - carthage: Swinject
      
      - carthage: SwinjectAutoregistration
      
      - carthage: SWXMLHash
      
    postBuildScripts:
      - path: ../../Scripts/copy-carthage-frameworks.sh
        name: Carthage
        inputFiles:
          - "$(SRCROOT)/../../Carthage/Build/iOS/Swinject.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/CleanPlatform_iOS.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/CleanCore.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/SWXMLHash.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/KeychainAccess.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/Reachability.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/Charts.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/TTTAttributedLabel.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/SwinjectAutoregistration.framework"
          - "$(SRCROOT)/../../Carthage/Build/iOS/MatomoTracker.framework"

```
