### ISSUE TITLE
Frameworks unit tests in app

### ISSUE THREAD

**Issue by raptorxcz** [yonaskolb/XcodeGen#461]
Hi,

I have Application with frameworks. Each framework has its own scheme and own unit tests.
Application do not have its own unit tests, instead it runs all frameworks unit tests.

How do I achieve this behaviour in XcodeGen?

I tried set it in scheme, but it is not working.

```
scheme:
      testTargets:
        - frameworkATests
        - frameworkBTests
        - frameworkCTests
        ...
```

For this settings I get error:
`- Target "Application" scheme has invalid test "frameworkATests"`

I would expect something like `implicit` keyword or path to the original project.

![49642090-59568d80-fa12-11e8-97bb-76e5f6c19c0c](https://user-images.githubusercontent.com/3967087/50332108-663eab00-0501-11e9-89fd-cfb0e895b60a.png)
![49642091-59568d80-fa12-11e8-9627-09ecebf84f0c](https://user-images.githubusercontent.com/3967087/50332109-663eab00-0501-11e9-805a-696d9b7b17e1.png)
![49642092-59568d80-fa12-11e8-970d-bb6d7b44cee3](https://user-images.githubusercontent.com/3967087/50332110-663eab00-0501-11e9-899e-7693144c0aec.png)

**Comment by raptorxcz** [comment]
Resolved in PR https://github.com/yonaskolb/XcodeGen/pull/466

**Comment by yonaskolb** [comment]
So I guess the issue was that the targets were in another project? Do you have multiple specs?

**Comment by raptorxcz** [comment]
Oh, I forgot to mention, each framework have its own project. So the application project contains only application files. I wanted to run frameworks tests from different project.

**Comment by raptorxcz** [comment]
Hi @yonaskolb, yes they are in same workspace. If you resolve this issue with another solution, I can close my MR. When I look at attached images, I think workspace is not required for this functionality.

**Comment by Utsira** [comment]
I've been able to add multiple test targets to the main app scheme using the new `projectReference` feature added in v 2.10. I think the [ProjectSpec.md](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#test-action) documentation doesn't make this clear. It says you can use a project reference for the `coverageTargets` field, but doesn't mention that you can also use project references in the `targets` field, but this works:

```
projectReferences:
  MyGreatFramework:
    path: Modules/Features/MyGreatFramework/MyGreatFramework.xcodeproj

schemes:
  AwesomeApp-PROD:
    build:
      targets:
        AwesomeApp: all
    test:
      targets:
        - AwesomeAppTests
        - MyGreatFramework/MyGreatFrameworkTests
      gatherCoverageData: true
```
