### ISSUE TITLE
Question: Can I generate Carthage script in framework

### ISSUE THREAD

**Issue by baevra** [yonaskolb/XcodeGen#463]
Can't run playgrounds without Carthage script in my framework, how can i enable this option?

**Comment by yonaskolb** [comment]
The carthage script will only be added to app and test targets by default. To add the script to other targets like frameworks you can add `embed: true` to the dependency

```yml
targets:
  Target:
    dependencies:
      - carthage: Alamofire
         embed: true
```

Not sure if this will help you with your playgrounds. Let me know how you go

Note you can also add a custom script to a target, documented here https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#build-script
