### ISSUE TITLE
Leveraging variables with XcodeGen project.yml 

### ISSUE THREAD

**Issue by johndpope** [yonaskolb/XcodeGen#473]
this might not be feasible due to limitations around yml

But here's my use case - 
I have a need to throw a variable to command line - and have the project spat out accordingly.

https://gist.github.com/johndpope/7ad704adf84f4ff6dbf48da6abde31f7

Eg. 
I want to pass in // or automatically infer from file detection.

XcodeGen generate useVariables

**variables.yml**
toolChain:tensorflow-DEVELOPMENT-2018-12-04-a

```yml

$toolchain = {{swift-latest}} // default value
name: SwiftTensorflow
options:
  bundleIdPrefix: com.swiftTensorflow

targets:
  SwiftTensorflow:
    type: tool
    platform: macOS
    deploymentTarget: "10.13"
    sources: 
        - Sources
    dependencies:
      - framework: /Library/Developer/Toolchains/$toolchain/usr/lib/swift/macosx/libtensorflow_framework.so
      - framework: /Library/Developer/Toolchains/$toolchain/usr/lib/swift/macosx/libtensorflow.so
      - framework: libpython2.7.tbd
    SWIFT_OPTIMIZATION_LEVEL: -O
    LD_RUNPATH_SEARCH_PATHS: "/Library/Developer/Toolchains/$toolchain/usr/lib/swift/macosx"
    OTHER_LDFLAGS:  -lpython
```

**Comment by johndpope** [comment]
this seems to solve things a bit 
%{foobar}
https://stackoverflow.com/questions/4150782/use-yaml-with-variables

maybe if we can just read all the extra parameters on xcodegen and send into yml.
Xcodegen foobar 1234

**Comment by johndpope** [comment]
digging deeper into this ansible use the flag --vars-file
https://docs.ansible.com/ansible-container/container_yml/template.html

it also has environment variables
_Passing environment variables
Variable definitions can also be provided as environment variables. Create AC_* variables in the Ansible Container environment that correspond to Jinja expressions in container.yml. For example, to provide a value for the Jina expression {{ web_image }}, define AC_WEB_IMAGE in the environment:

$ export AC_WEB_IMAGE=centos:7_

**Comment by johndpope** [comment]
```yml
defaults:
  toolchain_path: /Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/

name: SwiftTensorflow
options:
  bundleIdPrefix: com.swiftTensorflow

targets:
  SwiftTensorflow:
    type: tool
    platform: macOS
    deploymentTarget: "10.13"
    sources: 
        - Sources
    dependencies:
      - framework: {{ toolchain_path }}/libtensorflow_framework.so
      - framework: {{ toolchain_path }}/libtensorflow.so
      - framework: libpython2.7.tbd
    SWIFT_OPTIMIZATION_LEVEL: -O
    LD_RUNPATH_SEARCH_PATHS: {{ toolchain_path }}
    OTHER_LDFLAGS:  -lpython
    
```

**Comment by johndpope** [comment]
local variables working -  
```yml
toolchain_path: "/Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/"

name: SwiftTensorflow
options:
  bundleIdPrefix: com.swiftTensorflow

targets:
  SwiftTensorflow:
    type: tool
    platform: macOS
    deploymentTarget: "10.13"
    sources: 
        - Sources
    dependencies:
      - framework: ${ toolchain_path }/libtensorflow_framework.so
      - framework: ${ toolchain_path }/libtensorflow.so
      - framework: libpython2.7.tbd
    SWIFT_OPTIMIZATION_LEVEL: -O
    LD_RUNPATH_SEARCH_PATHS: ${ toolchain_path }
    OTHER_LDFLAGS:  -lpython
    
```

for some reason (on my other computer) my project isn't picking up OTHER_LDFLAGS /LD_RUNPATH_SEARCH_PATHS /SWIFT_OPTIMIZATION_LEVEL - need to investigate why.
