### ISSUE TITLE
Exclude files for a specific Platform

### ISSUE THREAD

**Issue by corysullivan** [yonaskolb/XcodeGen#474]
I'm building framework for macOS and iOS, I'm wondering if it is possible to exclude files for a specific platform?

```
fileGroups:
  - MyFramework
targets:
  MyFramework:
    type: framework
    platform: [macOS, iOS]
    settings:
      INFOPLIST_FILE: $(SRCROOT)/MyFramework/Resources/Info.plist
    sources:
      - path: MyFramework/Sources
      - path: MyFramework/Support
    excludes:
      // only want to exclude files for iOS
```
