### ISSUE TITLE
tiny bug - Xcodegen generate != Xcodegen 

### ISSUE THREAD

**Issue by johndpope** [yonaskolb/XcodeGen#475]
if there's a reason to delineate the two - that's fine - but it should throw some warnings to user. 

running **Xcodegen** against this project yml - spits out an xcode project - but missing compiler flags
https://gist.github.com/johndpope/3571bcab1d9466200e00a6b99987919d

maybe behaviour of **xcodegen** must match **xcodegen  generate** - and if you to ignore flags (which is confusing to me as to why) then have dedicated flag to do so if need be. 

Specifically these flags 
SWIFT_OPTIMIZATION_LEVEL: -O
    LD_RUNPATH_SEARCH_PATHS: "/Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx"
    OTHER_LDFLAGS:  -lpython

aren't picked up.

**Comment by yonaskolb** [comment]
Hi @johndpope. There should be no difference between `xcodegen` and `xcodegen generate`. (The former kept around for backwards compatibility)
From looking at your spec the compiler flags you mention won’t be read at all in either case. They have to sit under `settings’
```
targets:
  SwiftTorch:
    type: tool
    platform: macOS
    deploymentTarget: "10.13"
    sources: 
        - Sources
    dependencies:
      - framework: /Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/libtensorflow_framework.so
      - framework: /Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/libtensorflow.so
      - framework: libpython2.7.tbd
    settings:
      SWIFT_OPTIMIZATION_LEVEL: -O
      LD_RUNPATH_SEARCH_PATHS: "/Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx"
      OTHER_LDFLAGS:  -lpython
```
This is outlined in the documentation

Let me know if you have any more questions, otherwise feel free to close this
