### ISSUE TITLE
Add a custom group for a target source

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#478]
This would add another property to `TargetSource` to be able to specify a custom group that this source should be put into.
By default sources get added to the root of the project, or go up the tree if `options.createIntermediateGroups` is on. This will allow for more flexibility

eg:
```yml
targets:
  App:
    sources:
      - path: Sources/Files
        group: App/CustomName
```
