### ISSUE TITLE
Add postGen hook

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#479]
This would add a hook for a script to be run after generation. Critically this won't run if caching is on and the project isn't generated. 
This solves the issue of running `pod install` only if the project has changed as discussed here https://github.com/yonaskolb/XcodeGen/pull/412.

Example:
```yml
options:
  postGenScript: pod install
targets:
  ...
```
