### ISSUE TITLE
Allow custom name for a target source

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#484]
This would add another property to TargetSource to be able to specify a custom name that this source should have which would override the default path component.
eg:

```yml
targets:
  App:
    sources:
      - path: Sources
        name: App
```
