### ISSUE TITLE
Helper for carthage related frameworks

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#488]
This would add an option to a carthage dependency that would copy all of its related frameworks as well.
This is for some carthage dependencies that actually have multiple frameworks you need to embed.

For example https://github.com/DaveWoodCom/XCGLogger requires that you embed both `XCGLogger` and `ObjcExceptionBridging`.
XcodeGen could read the file in `Carthage/Build/.XCGLogger.version` to extract all the required build artifacts:

```json
{
  "commitish" : "6.1.0",
  "iOS" : [
    {
      "name" : "ObjcExceptionBridging",
      "hash" : "582b2059fd03bce0a3d265aa19d12915182be37e77e5d8502973766c9867cd9e"
    },
    {
      "name" : "XCGLogger",
      "hash" : "0736e85cd58080ece86985b85acb4c53bade7b849543e6d3b178d65f894f97b6"
    }
  ]
}
```

This functionality could live behind a flag. Something like the following:

old:
```
targets:
  Target:
    dependencies:
      - carthage: XCGLogger
      - carthage: ObjcExceptionBridging
```

new:
```
targets:
  Target:
    dependencies:
      - carthage: XCGLogger
        includeRelated: true
```
This behaviour could even be made the default but it would be a breaking change as sometimes you don't want to embed all of a dependencies frameworks
