### ISSUE TITLE
Changing CARTHAGE_BUILD_PATH

### ISSUE THREAD

**Issue by corysullivan** [yonaskolb/XcodeGen#498]
I'm a little confused on how to change the CARTHAGE_BUILD_PATH, I want to use 

`$(PROJECT_DIR)/../Carthage/Build`

I tried the following, but it's still using the default path

```
dependencies:
      - carthage: PubNub
        CARTHAGE_BUILD_PATH: $(PROJECT_DIR)/../Carthage/Build
```

**Comment by yonaskolb** [comment]
Hi @corysullivan. For documentation on that see either https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#options or https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md#carthage.

It has to be set in the **options**:
```
options:
  carthageBuildPath: ../Carthage/Build
targets:
  App:
    dependencies:
      - carthage: PubNub
```
