### ISSUE TITLE
Legacy targets crash Xcode

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#512]
Related to https://github.com/yonaskolb/XcodeGen/issues/425 it looks like legacy targets crash Xcode again.

Using this project spec:

```yaml
name: Foo
targets:
  Legacy:
    platform: iOS
    type: ""
    legacy:
      toolPath: /usr/bin/true
```

With XcodeGen master 65cc5f45d8d14e29a2d658e405df734f3bddadf2 Xcode crashes on launch

**Comment by keith** [comment]
Actually sorry I was wrong here, I got my projects mixed up. It does crash if use this spec however:

```yaml
name: Foo
targets:
  Legacy:
    platform: iOS
    type: ""
```

In this case XcodeGen should probably validate the `legacy` dictionary exists
