### ISSUE TITLE
Sources with folder reference type end up having incorrect path in Xcode project

### ISSUE THREAD

**Issue by nzhuk** [yonaskolb/XcodeGen#522]
xcodegen 2.2.0

My folder structure:

```
.
├── MyFramework
│   └── Resources
│       └── folder-to-copy
│           └── resource.txt
└── spec
    └── project.yml
```

spec/project.yml:

```
name: MyProject
targets:
  MyFramework:
    platform: iOS
    type: framework
    sources:
      - path: ../MyFramework/Resources
        type: folder
```

Command: `xcodegen -s spec/project.yml --project .` generates broken `MyProject.xcodeproj`:

![screenshot 2019-02-20 11 06 30](https://user-images.githubusercontent.com/294154/53079665-97d2f300-34ff-11e9-880f-343c9029ce16.png)

Notice that while the path `../MyFramework/Resources` is correct relative to the parent folder of the YML file, it's not correct relative to the Xcode project. In Xcode project, it should be `MyFramework/Resources`

[xcodegen-test.zip](https://github.com/yonaskolb/XcodeGen/files/2883800/xcodegen-test.zip)
