### ISSUE TITLE
Cannot use Target.platform as array

### ISSUE THREAD

**Issue by RomanPodymov** [yonaskolb/XcodeGen#523]
Hello.
Thank you for the tool, it's great. 
Today I found an issue with `Target.platform`. When I try to generate Xcode project using XcodeGen 2.2.0 with the `project.yml` created for XcodeGen 2.0.0 I get this error:
**Parsing project spec failed: Decoding failed at "platform": Incorrect type, expected String found ["iOS"]**
As far as I can see [here](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md) `Target.platform` can be an array of strings or a string. Is it still correct? Can I use `platform: [iOS]` in XcodeGen 2.2.0?

**Comment by yonaskolb** [comment]
Hi @RomanPodymov.
I can't reproduce this issue. You should be able to use `platform: [iOS]`. You can see an example of this in the tests https://github.com/yonaskolb/XcodeGen/blob/master/Tests/Fixtures/TestProject/project.yml#L173

Could you post your target definition?

**Comment by RomanPodymov** [comment]
Hello @yonaskolb 
Sorry for a long delay. Here is an example of **project.yml** that you can use to reproduce the issue:
```yml
targetTemplates:
  ios-app:
    type: application
    platform: [iOS]

name: MyProject
options:
  bundleIdPrefix: com.myapp
targets:
  MyApp:
    templates: [ios-app]
    deploymentTarget: "10.0"
    sources: [MyApp]
```
