### ISSUE TITLE
Subgroups are flattened when Sources paths contain ".." in YAML file

### ISSUE THREAD

**Issue by nzhuk** [yonaskolb/XcodeGen#525]
xcodegen 2.2.0

Test setup:

```
.
├── Sources
│   ├── Subfolder
│   │   └── file2.swift
│   └── file1.swift
└── spec
    └── project.yml
```

`spec/project.yml`:
```
name: MyProject
targets:
  MyFramework:
    type: framework
    platform: iOS
    sources:
      - path: ../Sources
```

Command: `xcodegen --spec spec/project.yml`

`MyProject.xcodeproj` looks like this:

![screenshot 2019-02-22 10 43 46](https://user-images.githubusercontent.com/294154/53230169-c16e5480-368e-11e9-9c58-25de94d9986c.png)

Current: `Subfolder` is not a subgroup of `Sources` group
Expected: `Subfolder` is a subgroup of `Sources` group

Note: This seems to be triggered when path of Sources in YAML file contains at least one `../`
