### ISSUE TITLE
Having trouble using excludes to exclude yml file from target.

### ISSUE THREAD

**Issue by kgellci** [yonaskolb/XcodeGen#526]
I have a `project.yml` with the following:

```
name: Area51
include:
  - Area51/Area51.yml
```

The Area51 directory holds Sources, Resources, and some additional files. One of the additional files being `Area51.yml`:

```
targets:
  Area51:
    sources:
      - path: .
         excludes: "*.yml"
```

I am trying to exclude Area51.yml from being added to the target but after generating the project, it continues to show up. Any help appreciated!
