### ISSUE TITLE
Change targets from list to map

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#53]
At the moment `targets` is list. That was done to preserve the order of generated targets in the xcode project.
There would be some upsides to making it a map of names to targets however:
- the `include` feature could edit and merge targets by name
- more natural yaml styl
- enforce the target name
- better visual seperation

The points are very minor other than the first one which is a real consideration.
Is having the order of targets in the project worth it? Thoughts anyone?

Here is a visual difference

**list - Array**
```yaml
targets:
  - name: MyTarget
    platform: iOS
    type: application
  - name: MyFramework
    platform: iOS
    type: framework
```
**map - Dictionary**
```yaml
targets:
  MyTarget:
    platform: iOS
    type: application
  MyFramework:
    platform: iOS
    type: framework 
```

In either case `targets` in the `ProjectSpec` struct would still be an array, this just affects yaml
