### ISSUE TITLE
Capabilities - Push Notifications

### ISSUE THREAD

**Issue by VictorUrielP** [yonaskolb/XcodeGen#540]
Hello!

I would like to know how to add push notification ON configuration in xcodegen

![image](https://user-images.githubusercontent.com/29692881/54774133-a0871980-4bd0-11e9-9a31-13c6c60eb84f.png)

And where to find more information about how to configure this part.

Thank you beforehand for your support!

**Comment by yonaskolb** [comment]
Hi @VictorUrielP

To answer questions like this, make the changes in a project that is tracked in git and then look at the diff. In this case there are actually quite a couple of changes.

**Entitlement file**
There is an entry added to your entitlement file. You can check the box in Xcode to edit your linked one or created a new one.
It will add the following content to your entitlements file.
```xml
<key>aps-environment</key>
<string>development</string>
```
To link an existing entitlements file you need to set the `CODE_SIGN_ENTITLEMENTS` build setting:
```yml
targets:
  App:
    settings:
      CODE_SIGN_ENTITLEMENTS: path/to/Entitlements.entitlements
```

If you are instead generating an entitlements file you can define this in your target
```yml
targets:
  App:
    entitlements:
      path: path/MyEntitlements.entitlements
      properties:
        aps-environment: development
```

**Target attributes**
It also seems Xcode adds the following attributes to a target. 
```
SystemCapabilities = {
  com.apple.Push = {
    enabled = 1;
  };
};
```
I'm not sure if this is required or not. If so you can set these like this:
```yml
targets:
  App:
    attributes:
      SystemCapabilities:
        com.apple.Push:
          enabled: 1
```

I hope that helps you. Let me know if you have any more questions.
