### ISSUE TITLE
Optional path not working

### ISSUE THREAD

**Issue by KyoheiG3** [yonaskolb/XcodeGen#546]
Hi.
Following project spec should make optional file reference, but it's not made.

```yml
name: MyProject
targets:
  MyFramework:
    platform: iOS
    type: framework
    sources:
      - path: Sources
      - path: Sources/File.swift
        optional: true
```

#527 might be related.

xcodegen 2.3.0

Thanks.
