### ISSUE TITLE
"optional: true" causes an existing source to be excluded

### ISSUE THREAD

**Issue by nzhuk** [yonaskolb/XcodeGen#559]
Environment:

- xcodegen 2.4.0
- macOS 10.4.4
- Xcode 10.2

Folder structure:
```
.
├── Sources
│   └── test.swift
└── spec
    └── project.yml
```

project.yml:
```
name: MyApp
targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - path: ../Sources
        optional: true
```

CLI command: `xcodegen -s spec/project.yml -p .`

Resulting Xcode project:

![Screenshot 2019-04-05 12 45 50](https://user-images.githubusercontent.com/294154/55619111-c0a60380-57a0-11e9-8ec6-690fb319f28e.png)

Note: **Sources** is missing.

If I remove `optional: true`, "Sources" appears:

![Screenshot 2019-04-05 12 46 40](https://user-images.githubusercontent.com/294154/55619202-e8956700-57a0-11e9-9efb-007fa1387657.png)

Also note: in this case, the "Sources" group has invalid file path in Xcode project (that's why `test.swift` is rendered in gray):
- Expected: `Sources`
- Actual: `../Sources`
