### ISSUE TITLE
Add HEADER_SEARCH_PATHS support

### ISSUE THREAD

**Issue by igorkulman** [yonaskolb/XcodeGen#560]
`HEADER_SEARCH_PATHS` seems not to be supported. I tried

```yml
targets:
  TWCrypto:    
    platform: iOS
    type: framework
    deploymentTarget: "10.0"
    sources:
    - TWCrypto/TWCrypto
    settings:
    - HEADER_SEARCH_PATHS: $SRCROOT/OpenSSL/include
    dependencies:
    - framework: TWCrypto/OpenSSL/lib/libcrypto.a
```

But the setting did not get pick up.

**Comment by yonaskolb** [comment]
`settings` is a dictionary, not an array. Try this:
```yml
targets:
  TWCrypto:    
    platform: iOS
    type: framework
    deploymentTarget: "10.0"
    sources:
    - TWCrypto/TWCrypto
    settings:
      HEADER_SEARCH_PATHS: $SRCROOT/OpenSSL/include
    dependencies:
    - framework: TWCrypto/OpenSSL/lib/libcrypto.a
```
