### ISSUE TITLE
UI Test Scheme Executable Not Set

### ISSUE THREAD

**Issue by keehun** [yonaskolb/XcodeGen#572]
Steps to reproduce:
1. Create a Target with type of `bundle.ui-testing`:
```yml
  ScreenshotTool:
    platform: iOS
    type: bundle.ui-testing
    sources:
      - ScreenshotTool
      - fastlane/SnapshotHelper.swift
    settings:
      BUNDLE_LOADER: "$(BUILT_PRODUCTS_DIR)/Name_Of_Host_App.app/Name_Of_Host_App"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
      SWIFT_VERSION: "4.0"
      TEST_HOST: "$(BUNDLE_LOADER)"
    dependencies:
      - target: Host_App_Target
```
2. Create a scheme for that UI test
```yml
  ScreenshotToolScheme:
    build:
      targets:
        Host_App_Target: [run, test]
        ScreenshotTool: [test]
    run:
      config: Debug
      targets:
        Host_App_Target: all
    test:
      targets:
        - MayflowerScreenshotTool
    profile:
      config: AppStore
    analyze:
      config: Debug
    archive:
      config: AppStore
```
3. Open the Scheme Editor in Xcode, and select the `Run` item

**Expected**
The "Host_App.app" should already be populated into the `Executable` dropdown field.

**Actual**
The `Executable` dropdown field shows "Ask On Launch"

**Note**
Looks like this is controlled in the `xcscheme` file for that UI test scheme. Under `LaunchAction` tag, it references the UI test target itself, _not_ the host app. Once it's changed to the Host App, recording UI tests and running them works well. Problem is, running `xcodegen` will overwrite that `xcscheme` file.
