### ISSUE TITLE
How Add new target into existing xcode project

### ISSUE THREAD

**Issue by Michael-Maher-BBN** [yonaskolb/XcodeGen#573]

**Comment by Michael-Maher-BBN** [comment]
??

**Comment by yonaskolb** [comment]
Hi @Michael-Maher-BBN.
To create the target I would suggest just using Xcode itself, which creates some starter files. Then you can add this target in the spec and include its root directory as a source. Let me know if you have any issues

**Comment by TheInkedEngineer** [comment]
@yonaskolb when I did so, for some reason it stopped going through the Scene delegate. Have any idea why? The spec I added is really basic

```
  BMDemoApp:
    type: application
    platform: iOS
    attributes:
      ProvisioningStyle: Automatic
    sources: [BMDemoApp]
    settings:
      TARGETED_DEVICE_FAMILY: 1
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
```
