### ISSUE TITLE
Support xcconfig

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#59]
# Motivation
Auto apply xcconfig configurations like this.
<img width="741" alt="xcode-configuration" src="https://user-images.githubusercontent.com/6007952/30695680-f4cd2ec8-9f13-11e7-922a-cc43b2d8c736.png">

# Current Problems
I notice documentations do mention about xcconfig but looks like it's not working as expected.

- Setting `configFiles` does not affect anything. (Bug? or maybe my spec is wrong)
- There is no way to set base xcconfigs for PBXProject.
- xcconfigs not being added to project

# Proposal
So this is my proposal.
- Support `baseConfiguration` for PBXProj
- Rename target's `configFiles` with `baseConfigurations` for consistency.
- (Optional) Rename `configs` to `configurations` since it looks like `xcconfig` and is misleading.

```project.yml
name: MyProject
configurations:
  Debug:
    baseConfiguration: configs/Debug.xcconfig
  OTA:
    baseConfiguration: configs/OTA.xcconfig
  Release:
    baseConfiguration: configs/Release.xcconfig
targets:
  MyApp:
    type: application
    platform: iOS
    sources: Sources/MyApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.toshi0383.hello
    baseConfigurations:
      Debug: configs/MyApp-Debug.xcconfig
      OTA: configs/MyApp-OTA.xcconfig
      Release: configs/MyApp-Release.xcconfig
```

If you guys feel happy with this outline, I can start working on a PR. 💪

**Comment by yonaskolb** [comment]
Hi @toshi0383, thanks for the suggestions!

Yeah, you're right there's no way to specify a project's xcconfig file. Setting `configFiles` on a target should be working though. Is it not?

In terms of adding them to the project, I'd like to keep defining configurations and applying xcconfig files in seperate dictionaries. While it's not hugely documented at the moment the `include` feature is highly used by myself and others, and seperating them makes the feature work better. Also it's nice to keep consistency between a project and a target in how things are defined.

About the renaming, I agree maybe `configs` to `configurations` would be better. I'd like to keep `configFiles` though, but would be open to `configurationFiles`. In either case, both the project and target properties should match. 
Obviously both of these are breaking changes, so would need a major version bump, or still read the old values.

Feel free to get a PR up and going! 👍

**Comment by toshi0383** [comment]
> Yeah, you're right there's no way to specify a project's xcconfig file. Setting configFiles on a target should be working though. Is it not?

Yeah maybe my spec is wrong. Would you mind sharing a working example spec for me?

> In terms of adding them to the project, I'd like to keep defining configurations and applying xcconfig files in seperate dictionaries.

Could you share outline spec? I don't see the whole picture yet, since I haven't used `include` feature. 
It's XcodeGen specific feature, right?
By the way I think `include` is also a bit misleading, because the name conflicts with xcconfig's `#include` feature.

> I agree maybe configs to configurations would be better.

Alright. I will fix this maybe in different PR.

> I'd like to keep configFiles though, but would be open to configurationFiles. In either case, both the project and target properties should match.

Great! I will take `configurationFiles`, because it's better suited to the Cocoa API naming conventions.

> Obviously both of these are breaking changes, so would need a major version bump, or still read the old values.

Sure, I am going to at first deprecate it and add warning message when people use the old values.
`[warning] configFile is deprecated. Use configurationFiles instead.`

**Comment by toshi0383** [comment]
> By the way I think include is also a bit misleading, because the name conflicts with xcconfig's #include feature.

Don't worry about this on this thread.
I might submit a new issue to ask about `include` feature. 😉

**Comment by toshi0383** [comment]
> Could you share outline spec? I don't see the whole picture yet, since I haven't used `include` feature. 

So this is what I came up with. What do you think?

```yml
name: MyProject
configurations:
  Debug: debug
  OTA: release
  Release: release
configurationFiles:
  Debug: configs/MyApp-Debug.xcconfig
  OTA: configs/MyApp-OTA.xcconfig
  Release: configs/MyApp-Release.xcconfig
targets:
  MyApp:
    type: application
    platform: iOS
    sources: Sources/MyApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.toshi0383.hello
    configurationFiles:
      Debug: configs/MyApp-Debug.xcconfig
      OTA: configs/MyApp-OTA.xcconfig
      Release: configs/MyApp-Release.xcconfig
```
