### ISSUE TITLE
Support bundling directory in copy bundle resources

### ISSUE THREAD

**Issue by thii** [yonaskolb/XcodeGen#592]
The following resources
```
Resources/file1.txt
Resources/file2.txt
```

will be bundled in the app bundle as:
```
MyApp.app/file1.txt
MyApp.app/file2.txt
```

Is there any way to specify the resources to be bundled as the following? Xcode supports it if you drag the whole directory into the `Copy Bundle Resources` build phase.
```
MyApp.app/Resources/file1.txt
MyApp.app/Resources/file2.txt
```

Currently there's a workaround for that by adding an arbitrary extension to the resource directory (e.g. `Resources.mybundle`), so XcodeGen will think that it is a file.

**Comment by tomquist** [comment]
Yes, that's possible. You can do this:
```yaml
sources:
  - path: Sources
    excludes:
    - Sources/Resources
  - path: Sources/Resources
    type: folder
```

**Comment by Arcovv** [comment]
I'm not sure your situation, but maybe I have the same problem with yours and solved now.

My project folder:
![image](https://user-images.githubusercontent.com/11262771/169743725-f92b76ff-f253-4d77-ae25-ba9fb339b2cd.png)

I have two `Info.plist` files for production and staging environments in `App/SupportingFiles/Production` and `App/SupportingFiles/Staging` folders. I need to split them into different targets.

And here is my solution in project.yml:
```yml
targetTemplates:
  App:
    type: application
    platform: iOS

targets:
  AppProduction:
    templates: 
      - App
    sources:
      - path: App
        excludes:
          - SupportingFiles/Staging

  AppStaging:
    templates: 
      - App
    sources:
      - path: App
        excludes:
          - SupportingFiles/Production
```
