### ISSUE TITLE
Independent Watch Apps Target Type - application.watchapp2-container

### ISSUE THREAD

**Issue by leogdion** [yonaskolb/XcodeGen#595]
There's a new target type for independent Apple Watch apps defined as `application.watchapp2-container`. It seems to act pretty as the iOS app did and contains the `application.watchapp2`.

If you try to use it now with `xcodegen` it defines it as:
`Parsing project spec failed: Unknown Target type: application.watchapp2-container`

**Comment by yonaskolb** [comment]
Thanks for raising @leogdion. It requires some changes in xcodeproj. I've noted your request here https://github.com/tuist/xcodeproj/issues/438
We'll try and get this in soon

**Comment by leogdion** [comment]
Thanks @yonaskolb  I started looking at `Sources/xcodeproj/Objects/Targets/PBXProductType.swift` to see what that might entail.

**Comment by yonaskolb** [comment]
Yeah if you'd like to add a PR to xcodeproj, that would be great!

**Comment by leogdion** [comment]
Added
https://github.com/tuist/xcodeproj/pull/441

Thanks @yonaskolb

**Comment by leogdion** [comment]
My current workaround is to use this for my target:
```yaml
  watchApp:
    type: application
    platform: watchOS
    dependencies:
      - target: watchApp.watchkitapp
    settings: 
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.company.watchApp
        SDKROOT: iphoneos
```
Then manually change the `productType` in the project.pbxproj file to `com.apple.product-type.application.watchapp2-container`. Also note I need the `SDKRoot` to be set to `iphoneos` for the target to work correctly.
