### ISSUE TITLE
buildPhase=headers does not work when type:framework.static

### ISSUE THREAD

**Issue by samchang8826** [yonaskolb/XcodeGen#609]
```
targets:
   xxxx:
    type: framework.static
    platform: iOS
    deploymentTarget: "12.0"
    sources:
      - path: xxx
        excludes:
          - "*[!h]"
        buildPhase: headers
```

the headers section on buildPhase is empty.
