### ISSUE TITLE
Cached .build always recompiles on CircleCI 

### ISSUE THREAD

**Issue by vastopa** [yonaskolb/XcodeGen#612]
Using `XcodeGen version 2.6.0 at f63f652988355145d3a56ea6bf7257d42e6fdbb7` on `CircleCI 2.0`

I am running `swift run xcodegen` in it's own job on CI and caching the `.build` output for reuse in my build job. Whenever I restore the cache, and then run `swift run xcodegen generate`, it will recompile the build dependencies. 

Here are the yaml aliases I've defined:
```
restore_xcodegen_cache: &restore_xcodegen_cache
  restore_cache:
    key: xcodegen-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}-{{ .Branch }}-{{ checksum "../Package.resolved" }}

xcodegen_deps: &xcodegen_deps
  <<: *defaults
  steps:
    - *shallow_checkout
    - *restore_xcodegen_cache
    - run:
        name: Build xcodegen dependencies if needed
        command: if [ ! -d "../.build" ]; then swift run xcodegen; fi
    - save_cache:
        key: xcodegen-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}-{{ .Branch }}-{{ checksum "../Package.resolved" }}
        paths:
          - ../.build/
    - *chat_failure_notification

xcodegen: &xcodegen
  run:
    name: Generate project file with Xcodegen
    command: |
      #!/bin/sh
      swift run xcodegen generate
```

I'm using the above aliases in my build job:
```
build: &build
  <<: *defaults
  steps:
    - *shallow_checkout
    - *set_carthage_env_var
    - *restore_cache
    - *restore_xcodegen_cache
    - *xcodegen
```

My thought would be that running `swift run xcodegen generate` after restoring the `.build` directory, would lead to just generating the project but instead the dependencies are recompiled. Does anyone have any ideas/solutions for this? When I perform the same steps locally, the call to `swift run xcodegen generate` will just generate the project and not do any recompilation. This adds ~35 seconds to my build step - would be nice to avoid that. 

Any thoughts/suggestions would be greatly appreciated!
