### ISSUE TITLE
Siri Shortcuts - Intents Extension and Intents Extension UI

### ISSUE THREAD

**Issue by kmentrobin** [yonaskolb/XcodeGen#623]
Hi, I have problem with adding Instents Extension to support Siri shortcuts. 

This is my project.yml file 

`name: TestIntents
targets:
  TestIntents:
    type: application
    platform: iOS
    deploymentTarget: 12.0
  IntentExtension:
    type: app-extension.intents-service
    platform: iOS
    deploymentTarget: 12.0
    sources:
      - path: IntentExtension/
    settings:
      base:
          INFOPLIST_FILE: IntentExtension/Info.plist`

When I run it I see IntentExtension but without Info.plist

**Comment by yonaskolb** [comment]
Hi @kmentrobin. Does an Info.plist file actually exist at the path? If you create the target through Xcode it will give you an `Info.plist` you can use. XcodeGen doesn't generate these by default (You can do this with `target.info` but it only has some basic settings to start with and you may need more the Xcode new target template can give you) https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target

**Comment by chc24** [comment]
@yonaskolb I believe this might be happening to me as well. I've been able to use XcodeGen to create a today extension, but when I create another target with `app-extension.intents-service`, the info-plist fails to generate and the extension is not recognized as an intents extension. Here is what my target looks like, and i've embedded this into the container app as follows:

```
targets:
  ExtensionIntents:
    type: app-extension.intents-service
    deploymentTarget: 11.0
    platform: iOS
    templates:
      - ExtensionIntentsTemplate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.project.Intents
        INFOPLIST_FILE: Info/Extensions/ExtensionIntentsInfo.plist
    sources:
      - path: Intents
```

And yes, an info.plist does exist at that path. When I create the intents target manually through xcode, everything looks good, but for my use case this extension needs to be regenerated every time.
