### ISSUE TITLE
Support sources glob patterns

### ISSUE THREAD

**Issue by PaulTaykalo** [yonaskolb/XcodeGen#631]
## **Issue**
Currently, when we're adding sources, we're doing this in the way we get all files inside source and then exclude files, we don't want them to be there
```
 sources: 
      - path: "MyProject/Sources"
        createIntermediateGroups: true
        excludes:      
          - "*/*Tests.*"
```

In development often it is nice to have Tests files right near files being tested
```
SomeFile.swift
SomeFileTests.swift
```

This will allow Xcode to jump between related sources as well

While we can easily exclude Test files from the original target, we cannot create test target which will include all files passing glob pattern

## **Suggestion**

to have an option that will allow only to include files, passing glob pattern

```
 sources: 
      - path: "MyProject/Sources"
        createIntermediateGroups: true
        includes-only:      
          - "*/*Tests.*"
```

## **Impact on existing realisization**
- Since this is an optional value, no projects will be affected
- undefined behaviour if `include` and `exclude` will be defined at the same time

P.S. This could be potentially done by using negation of `excludes`, but it seems that `glob` that is used in xxodegen doesn't like negation match
