### ISSUE TITLE
Code signing attributes don't set values in build settings

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#637]
Code signing attributes on a target:

```
    attributes:
      ProvisioningStyle: Manual
      DevelopmentTeam: MyTeam
```

Doesn't set the comparable Build Settings tab under Signing:

"Code Signing Style" Automatic!
"Development Team" empty!

However, ProvisioningStyle did seem to uncheck Automatically Manage Signing in the General tab

**Comment by yonaskolb** [comment]
Signing is set via build settings such as:
```yml
settings:
  CODE_SIGN_STYLE: ...
  CODE_SIGN_IDENTITY: ...
  DEVELOPMENT_TEAML: ...
  CODE_SIGN_ENTITLEMENTS: ..
```

https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md#configuring-build-settings
