### ISSUE TITLE
Issue with agvtool what-version can't find CURRENT_PROJECT_VERSION setting

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#649]
Using Fastlane action `get_build_number` uses `agvtool what-version --terse` which fails because the key CURRENT_PROJECT_VERSION is not set for the project. 

What is the best solution for this?

**Comment by yonaskolb** [comment]
Hi @brandtdaniels. It looks like `CURRENT_PROJECT_VERSION` is only being set on framework targets. You could set in on the whole project if you wanted to like this
```yml
settings:
  base:
    CURRENT_PROJECT_VERSION: 1
```

**Comment by brandtdaniels** [comment]
Our build number and version is stored in our plist. I would need to get that number from the plist.

**Comment by 4brunu** [comment]
@brandtdaniels Hey, I'm having the same problem.
Did you manage to solve the problem?
How?
Thanks

**Comment by yonaskolb** [comment]
How is this solved in projects created in Xcode? The project that gets created also doesn't have `CURRENT_PROJECT_VERSION` on the project level

**Comment by brandtdaniels** [comment]
I solved this by not using fastlane to bump the build number, but to use an environment variable set by our build server.

**Comment by brandtdaniels** [comment]
properties:
        CFBundleVersion: ${DS_BUILD_NUM}
        CFBundleShortVersionString: 0.13.0

**Comment by toshi0383** [comment]
FYI: You can also use plistbuddy to do it.
Also see: https://github.com/toshi0383/xcconfig-extractor#agvtool-compatibility

**Comment by Mauricevb** [comment]
This is works:

```yml
settings:
  base:
    VERSIONING_SYSTEM: "apple-generic"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    ...
info:
  properties:
    CFBundleShortVersionString: $(MARKETING_VERSION)
    CFBundleVersion: $(CURRENT_PROJECT_VERSION)
    ...
```
```bash
$ xcrun agvtool new-version 2 # Build number
$ xcrun agvtool new-marketing-version 2.0.0 # App version
```
