### ISSUE TITLE
Group target settings

### ISSUE THREAD

**Issue by mkkroliks** [yonaskolb/XcodeGen#653]
Hey! 🙂   Is there any way to group target settings?

I would like to share :

```
type: application
platform: iOS
sources:
  - path: MultipleTargets
dependencies:
  - target: Pictures
```

between multiple targets to prevent something like this:  
```
  App1:
    type: application
    bundleIdPrefix: "com.multipleTargets.App1"
    platform: iOS
    sources:
      - path: MultipleTargets
    dependencies:
      - target: Pictures
  App2:
    type: application
    bundleIdPrefix: "com.multipleTargets.App2"
    platform: iOS
    sources:
      - path: MultipleTargets
    dependencies:
      - target: Pictures
  App3:
    type: application
    bundleIdPrefix: "com.multipleTargets.App3"
    platform: iOS
    sources:
      - path: MultipleTargets
    dependencies:
      - target: Pictures
```
