### ISSUE TITLE
Adding a sources entry for a non-existent path

### ISSUE THREAD

**Issue by vlozko** [yonaskolb/XcodeGen#659]
I have the following entry in my config file:

```
targetTemplates:
  DynamicFrameworkWithResources:
    platform: iOS
    type: framework
    sources: 
      - Sources
      - Resources
```

The particular issue is that the Resources directory for a project does not exist. The reason why it's included is that a generated (via a run script phase), git ignored file is supposed to be eventually placed there and copied into our bundle. It's the only file that gets copied. I worry this will become an even bigger issue down the road when we start utilizing code generation tools.

The hacky way I've worked around this for now is to create the directory and commit in a dummy, empty file. Unfortunately, it's

1. A hack. I'd like to do things correctly.
2. It gets included into the final build products unless I add an excluded file exception.

Are there proper ways to solve this?

**Comment by bclymer** [comment]
Are you looking for `optional`? 

https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#sources

It allows you to specify a directory or file, but _not_ check if it exists at project generation time. 

```
targetTemplates:
  DynamicFrameworkWithResources:
    platform: iOS
    type: framework
    sources: 
      - Sources
      - path: Resources
        optional: true
```
