### ISSUE TITLE
coverageTargets not working with XcodeGen 2.10.0

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#699]
You can seen in the image I have added my target for coverageTargets, but when generating the project the "Gather code coverage for" is still set to all targets.

![Screen Shot 2019-10-28 at 5 14 15 PM](https://user-images.githubusercontent.com/1013676/67727412-8ef7c280-f9a6-11e9-8bfb-c8fbe5f0d2f8.png)

**Comment by brandtdaniels** [comment]
Also, this could probably work in Target Schemes as well
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme

**Comment by yonaskolb** [comment]
Which version of XcodeGen are you using @brandtdaniels?

cc @kateinoigakukun

**Comment by brandtdaniels** [comment]
2.10.0 as noted in the summary.

**Comment by 86** [comment]
@kateinoigakukun 
I compared a generated scheme and a manually edited scheme. Generated one has not `onlyGenerateCoverageForSpecifiedTarget = "YES"` attribute. It seems this is the cause.
![image](https://user-images.githubusercontent.com/774945/67832666-b759fb00-fb25-11e9-9925-b682b1d8dbfc.png)

**Comment by kateinoigakukun** [comment]
Thank you for your report and investigation. I forgot to apply the property @86 said. https://github.com/tuist/XcodeProj/pull/473

I'm creating a PR to fix this issue 🙇

**Comment by brandtdaniels** [comment]
@yonaskolb When do you plan on releasing 2.10.1?

**Comment by zenangst** [comment]
I still haven't manage to get this to work with version 2.13.0.

```
targets:
  MyApplication:
    type: application
    platform: tvOS
    configs:
      Debug: debug
      Release: release
    scheme:
      gatherCoverageData: true
      coverageTargets:
        - MyApplication
```

I'm referencing the target name.
Am I missing something obvious here?

**Comment by AlexLittlejohn** [comment]
This issue still exists in the latest release.

**Comment by yonaskolb** [comment]
Gathering coverage data across all targets is supported on target schemes and scheme definitions.
Target schemes however don't support setting custom coverage targets https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
Only full schemes do https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#test-action

```yml
target:
  MyApp:
    scheme:
      gatherCoverageData: true
      # this will gather code coverage to all targets since @kateinoigakukun's fix above
      # not possible to set specific coverage targets
```

```yml
schemes:
  MyScheme:
    build:
      targets:
        MyApp: all
       # list any other targets here
    test:
      gatherCoverageData: true
      coverageTargets: # optional customization of targets
        - MyApp 
       # list any other targets that build here
```

If someone wants to set custom code coverage targets on the simple helper scheme on target, that requires a new property on `TargetScheme`. Happy to accept a PR for that
