### ISSUE TITLE
SwiftPM dependencies don't link their required dependencies

### ISSUE THREAD

**Issue by JonasVautherin** [yonaskolb/XcodeGen#708]
Adding `transitivelyLinkDependencies: true` to my options or target has no effect on the resulting xcode project.

I am depending on SwiftPM packages using the `package` dependency type. For instance, I depend on `grpc-swift`, which depends on `swift-nio`, which itself builds `CNIOAtomics`. I can build grpc-swift with xcodegen ([project.yml here](https://github.com/JonasVautherin/grpc-swift/blob/nio/project.yml)), and in Xcode I see that it does build CNIOAtomics. Then from Carthage, I try to depend on that grpc-swift (the point of my using xcodegen being Carthage), and there, `CNIOAtomics` is missing. So `cartage update` works, but building the end project fails with "Missing required module 'CNIOAtomics'".

Now, if I add `swift-nio` to the `packages` of my end project, then it works, suggesting an error with transitive dependencies. I thought that maybe that was because I should set `transitivelyLinkDependencies: true`, but this has no effect on the resulting `project.pbxproj`.

Am I missing something? Is it wrong to use `transitivelyLinkDependencies` with SwiftPM packages?

**Comment by brentleyjones** [comment]
Ahh, `transitivelyLinkDependencies` wasn't updated to support SwiftPM packages when they were added. I'll see if I can get around to this in the next couple days.

**Comment by JonasVautherin** [comment]
That would be awesome! I'm trying to bring Carthage support to grpc-swift in a nice way, and I find xcodegen is a super clean way to deal with that.

I am not super advanced in Swift and I don't know the xcodegen codebase, but I could have a look if you pointed me to a place where to start :blush:. Otherwise I will gladly test and review you changes!

**Comment by brentleyjones** [comment]
@JonasVautherin I have a feeling it would be somewhere around https://github.com/yonaskolb/XcodeGen/blob/master/Sources/XcodeGenKit/PBXProjGenerator.swift#L1020-L1023

Though, thinking more about this, a similar thing happens when defining a dependency on a Carthage dependency that itself has another dependency. That isn't resolved with `transitivelyLinkDependencies`, which only links transitive declare dependencies in parent targets. I think this is currently handled by the `findCarthageFrameworks` for Carthage https://github.com/yonaskolb/XcodeGen/blob/master/Sources/XcodeGenKit/PBXProjGenerator.swift#L605-L608 (though I don't use it, so maybe it's not for that).

Either way, I think something outside of `transitivelyLinkDependencies` is needed.

@yonaskolb Do you have any thoughts on this?

**Comment by JonasVautherin** [comment]
I think that it would be a great feature. My understanding is that SwiftPM may slowly start supporting iOS with Xcode 11. But the fact is that projects using Carthage won't all switch in a day (if they ever do). Still, some projects now only support SwiftPM (that's the case for gRPC-Swift, for instance, were we've been struggling to keep support for Carthage, and that will probably go away with version 1.0.0).

I believe xcodegen is a super clean way to keep support for Carthage. But that requires the SPM dependencies (e.g. my xcodegen project for gRPC-Swift creates an `xcodeproj` that works with Carthage, but it loses the transitive dependencies of gRPC-Swift.

**Comment by JonasVautherin** [comment]
@yonaskolb: kindly pinging on that regard, I believe your opinion would be valuable!

**Comment by JonasVautherin** [comment]
Would somebody know a workaround for that? Or have an opinion on whether it would be possible to do it at all?

**Comment by brentleyjones** [comment]
@JonasVautherin Are you able to list the packages in `dependencies`, without having to add the repository to the `packages` section? If so, that seems like a reasonable workaround for now, similar to what we had to do before `findCarthageFrameworks`.

**Comment by hartbit** [comment]
I have the same issue. Is there a way to work around this in XcodeGen?

**Comment by yonaskolb** [comment]
Hi all. From what I understand Carthage doesn't support projects that have spm dependencies. You can find discussion around that here https://github.com/Carthage/Carthage/pull/1945 which is a PR to get Carthage to automatically support spm packages.

Perhaps I'm misunderstanding the issue here though. Can you accomplish what you want by manually creating the xcodeproj in Xcode?

**Comment by hartbit** [comment]
My issue is not related to Carthage as I don't use Carthage. I'm just defining a project with a SwiftPM package dependency to GRDB.swift (https://github.com/groue/GRDB.swift) and getting a `Missing required module 'CSQLite'` compilation error which I don't get if I create the Xcode project manually. It seemed related because CSQLite is a system target that GRDB depends on. Here's a project definition file to reproduce the issue:

```yaml
name: XcodeGenBug
options:
  bundleIdPrefix: com.hartbit
  deploymentTarget:
    iOS: "13.0"
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 4.6.2
targets:
  XcodeGenBug:
    type: application
    platform: iOS
    sources: [XcodeGenBug]
```

**Comment by JonasVautherin** [comment]
@yonaskolb from my understanding, I believe Carthage probably won't support SPM. That's why I was hoping to work around that with xcodegen. 

My issue is that newer project are tempted to only support SwiftPM, saying that it should soon support iOS as well, but there doesn't seem to be a solution for the transition period. So if I want to support Carthage in my library, maybe I should not depend on projects that only support SwiftPM, but that's not super convenient.

**Comment by JonasVautherin** [comment]
Could xcodegen do something like [this (documented on apple.com)](https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app) for instance?

**Comment by JonasVautherin** [comment]
Kindly pinging regarding my last link above. As far as I understand the Apple documentation, it is possible to add an SPM dependency to an xcodeproj using Xcode. Which gives me hope that there may be a way to generate that with xcodegen.

If that was possible, it would allow Carthage projects (that require an xcodeproj) to work with pure SPM projects thanks to xcodegen.

**Comment by yonaskolb** [comment]
@JonasVautherin unless I’m misunderstanding your specific question, XcodeGen already has this capability

**Comment by JonasVautherin** [comment]
@yonaskolb xcodegen allows adding an SPM dependency, but it does not follow its transitive dependencies, right? Or does it?

My issue here is really that: I add grpc-swift to my Project.yml, and I'm very happy with that. But the resulting xcodeproj lacks the dependencies of grpc-swift.

Does that make any sense at all? I may totally be missing something here...

**Comment by JonasVautherin** [comment]
I'm now confused whether this issue should be a "question" for an already-existing feature, a "won't fix" kind of bug, or a "feature request". Feel free to close if that's a "won't fix" issue.

On my end I'm now hoping that SwiftPM quickly overtakes all the other systems (especially on iOS), so that I can confidently drop support for other package management systems :+1:.

**Comment by yonaskolb** [comment]
@hartbit from the spec you posted your issue is that you're not making the packages dependencies of your target. I tested it on 2.15.1 and works fine for me if you do that:
```yml
name: XcodeGenBug
options:
  bundleIdPrefix: com.hartbit
  deploymentTarget:
    iOS: "13.0"
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 4.6.2
  GRDBCombine:
    url: https://github.com/groue/GRDBCombine
    from: 0.7.0
targets:
  XcodeGenBug:
    type: application
    platform: iOS
    sources: [XcodeGenBug]
    dependencies:
      - package: GRDB
      - package: GRDBCombine
```
I even tested just referencing the `GRDBCombine` package and that worked too
```yml
name: XcodeGenBug
options:
  bundleIdPrefix: com.hartbit
  deploymentTarget:
    iOS: "13.0"
packages:
  GRDBCombine:
    url: https://github.com/groue/GRDBCombine
    from: 0.7.0
targets:
  XcodeGenBug:
    type: application
    platform: iOS
    sources: [XcodeGenBug]
    dependencies:
      - package: GRDBCombine
```
