### ISSUE TITLE
How to use projectReferences?

### ISSUE THREAD

**Issue by acecilia** [yonaskolb/XcodeGen#717]
Hi:

I have been trying to use the new `projectReferences` option, but I could not make it work (Xcodegen 2.10.1). After adding the `projectReferences` and the scheme, the target of the referenced project is marked as `missing`:

<img width="1118" alt="Screenshot 2019-11-14 at 15 54 09" src="https://user-images.githubusercontent.com/7938671/68868023-10658980-06f7-11ea-916a-56c3ed336a28.png">

Is this a bug, or am I missing something?

Here is the example project: https://github.com/acecilia/XcodeGenProjectReference

Thanks!

**Comment by yonaskolb** [comment]
@kateinoigakukun

**Comment by kateinoigakukun** [comment]
@acecilia Thanks for reporting!
This behavior is expected because your `Example.xcodeproj` doesn't have `FooLib.xcodeproj` reference in project tree.

If you want to use `projectReferences` feature, you need to add `FooLib.xcodeproj` as a soure of `Example.xcodeproj` like below.

```yaml
name: Example

options:
  minimumXcodeGenVersion: 2.10.1

projectReferences:
  FooLib:
    path: FooLib/FooLib.xcodeproj
targets:
  ExampleTarget:
    type: framework
    platform: iOS
    sources:
      - FooLib/FooLib.xcodeproj

schemes:
  FooLib:
    build:
      targets:
        FooLib/FooLib: ["run"]
```

Or you can put `FooLib.xcodeproj` and `Example.xcodeproj` in same `xcworkspace`.
