### ISSUE TITLE
Can't Add Local Swift Package as Dependency

### ISSUE THREAD

**Issue by jsorge** [yonaskolb/XcodeGen#721]
Using Xcodegen v2.10.1 and adding a local Swift package to my project, and I want it to be a dependency for one of my targets. The following is not working for me:

```
name: MyApp
localPackages:
  - Modules/Utilities
packages:
  Pathos:
    from: 0.2.0
    url: https://github.com/dduan/Pathos.git
targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - MyApp/Sources
      - MyApp/Resources
    dependencies:
      - package: Utilities
    configFiles:
      Debug: xcconfigs/BindleWriter-Debug.xcconfig
      Release: xcconfigs/BindleWriter-Release.xcconfig
```

And the error I get is `Spec validation error: Target "MyApp" has an invalid package dependency "Utilities"`. If I alter the dependency on Utilities to be on Pathos instead (which is a remote package) then the project generates just fine.

Am I holding it wrong?

**Comment by yonaskolb** [comment]
Hi @jsorge, currently local packages are only supported when they mirror remote packages. There is mention of that buried here https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md

Additional work is required to support completely local packages

**Comment by jsorge** [comment]
Ah that makes sense. I hadn't seen that note before. Thanks for letting me know.

**Comment by AV8R-** [comment]
Hi @yonaskolb, what kind of additional work is required to make this feature work?
Actually I tried to remove any package validation form SpecValidation.swift (that was on line 168) and removed `guard` statement in PBXProjGenerator.swift on line 630.

And it works for me. Except I don't have any remote package validation for now.
What should I do additionally to make a pull request for this feature?

**Comment by WilliamIzzo83** [comment]
Hi everybody

I'm kinda interested too. Are there any news about this?

**Comment by freddi-kit** [comment]
I made a pull request and it would help this issue => https://github.com/yonaskolb/XcodeGen/pull/796

**Comment by WilliamIzzo83** [comment]
Great work guys. Thank you so much! Waiting for a new release :D

**Comment by freddi-kit** [comment]
Hello. v2.15.0 is released and we can use local Swift Package from now by following format.
Thank you all!

```yml
name: GennedProj
...
packages:
  MyLibrary: 
    path: Packages/MyLibrary
targets:
  GennedProj:
    ...
    dependencies:
      - package: MyLibrary
```

**Comment by ThePredators** [comment]
Hello,

im under version 2.35.0 and unfortunately this doesn't work. Xcode find the packages as they are listed in project structure -> Packages, but i cannot import these dependencies !!

**Comment by fnc12** [comment]
Hello.

I am using `Version: 2.41.0`, my `project.yml` looks like this:
```yaml
packages:
  RealityKitContent:
    path: Packages/RealityKitContent
....
targets:
  my-app-for-visionos:
    dependencies:
      - package: RealityKitContent
        product: RealityKitContent
```
It runs `xcodegen` with no error and the target is linked against `RealityKitContent` static lib but the project compiles with error `Missing package product 'RealityKitContent'`. When I go to project settings -> Package Dependencies it turns out dependency list is empty. If I add local swift package manually right from `Packages/RealityKitContent` path (the path is correct) it starts compiling well. If I change `package: RealityKitContent` to let's say `package: RealityKitContent2` then `xcodegen` script fails. It means `xcodegen` knows about the package but somehow doesn't add it to package dependencies on the project level. How to solve this? Thanks

**Comment by ThePredators** [comment]
By the if someone still have this issue i fixed it using this. The local package has to be inside a folder called : "local" !!

Thats the trick !
```yml
...
targets:
  my_target:
    platform: iOS
    type: application
    settings:
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_NAME: ${APP_NAME}-us
    sources:
      - path: my_target
    configFiles:
      Debug: Config/xcconfig/Debug.xcconfig
      Release: Config/xcconfig/Release.xcconfig
    dependencies:
      - package: MyPackage
...
packages:
      MyPackage:
        path: ./local/MyPackage
```

Somewhere else if your package has products then you have to do like this ! (Add product in dependencies)

@fnc12 
Use case : AppCenter dependency

```yml
targets:
  my_target:
    platform: iOS
    type: application
    settings:
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_NAME: ${APP_NAME}-us
    sources:
      - path: my_target
    configFiles:
      Debug: Config/xcconfig/Debug.xcconfig
      Release: Config/xcconfig/Release.xcconfig
    dependencies:
      - package: AppCenter
         product: AppCenterAnalytics
      - package: AppCenter
         product: AppCenterCrashes
...
packages:
  AppCenter:
    path: ./local/appcenter-sdk-apple
```

Let me know if this resolve the issue on your side.
