### ISSUE TITLE
Can't run Today Extension scheme (appex is not application bundle)

### ISSUE THREAD

**Issue by chc24** [yonaskolb/XcodeGen#727]
Hello - I'm having issues with adding a today extension via xcodegen and was hoping you could help out. Here is what yaml looks like
```
targets:
  MainTarget:
    dependencies:
      - target: TodayExtension
        embed: true
        codeSign: false
        buildPhase:
          copyFiles:
            destination: plugins
  
  TodayExtension:
    type: app-extension
    templates: 
      - ExtensionTemplate
    platform: iOS
    deploymentTarget: 11.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: _
        INFOPLIST_FILE: Info/Extensions/_.plist
    sources:
      - path: TodayExtension/
    dependencies: 
      - sdk: NotificationCenter.framework
```
The xcodegen runs fine, I see a scheme created for my extension, and the associated product TodayExtension.appex in my products folder. However, when I try to run the extension's scheme, I get the following error message: 

```
Unable to install “TodayExtension”
Domain: com.apple.platform.iphoneos
Code: -1
Recovery Suggestion: “TodayExtension” cannot be installed on your iPhone (2). TodayExtension.appex is not an application bundle
--
```

Furthermore, when running the container app, I see the extension available in the Widgets section of iOS, with the error message "Unable to load" displayed.

Any guidance would be appreciated. Thank you!
