### ISSUE TITLE
Issue with Siri Intents + Siri Intents UI

### ISSUE THREAD

**Issue by chc24** [yonaskolb/XcodeGen#738]
I've been able to use XcodeGen to create a today extension, but when I create another target with app-extension.intents-service, the info-plist fails to generate and the extension is not recognized as an intents extension. Here is what my target looks like, and i've embedded this into the container app as follows:
```
targets:
  ExtensionIntents:
    type: app-extension.intents-service
    deploymentTarget: 11.0
    platform: iOS
    templates:
      - ExtensionIntentsTemplate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.project.Intents
        INFOPLIST_FILE: Info/Extensions/ExtensionIntentsInfo.plist
    sources:
      - path: Intents
Main App:

MainApp:
  [...]
  dependencies:
      - target: IntentsExtension
         embed: true
        codeSign: false
        buildPhase:
          copyFiles:
            destination: plugins
```
And yes, an info.plist does exist at that path. When I create the intents target manually through xcode, everything looks good, but for my use case this extension needs to be regenerated every time.
