### ISSUE TITLE
[Quesion] How to set the default Build Configuration for "Run"

### ISSUE THREAD

**Issue by touyu** [yonaskolb/XcodeGen#741]
Hi, Thanks for the useful library.

I wanna to set the default Build Configuration for "Run".

I wrote the following project.yml but it didn't work (some omitted)

```yaml
name: title
configs:
  Staging Debug: debug
  Production Debug: debug
  Production Release: release
targets:
  App:
    scheme:
      App:
        run:
          config: Staging Debug
```

What can I do to make it work well?

**Comment by toshi0383** [comment]
Hi @touyu 👋
Does top-level `schemes` work for you?
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#environment-variable

**Comment by touyu** [comment]
@toshi0383 Thank you! It worked as I expected!

```yaml
name: title
configs:
  Staging Debug: debug
  Production Debug: debug
  Production Release: release
schemes:
  App:
    build:
      targets:
        App: all
    run:
      config: Staging Debug
targets:
  App:
```
