### ISSUE TITLE
SwiftPM packages linked into static libraries

### ISSUE THREAD

**Issue by rastersize** [yonaskolb/XcodeGen#748]
Hey! I seem to have ran into a bug with the SwiftPM package integration for static libraries. When a static library depends on an SDK (e.g. Foundation, UIKit, …) all SwiftPM packages will also be linked into it. Adding other types of dependencies doesn’t seem to have any impact. It seems like it’s only when a static library depends on both a SwiftPM package and an SDK that the issue occurs.

I was able to reproduce with latest master. See an example sing this small modification of the SPM test fixture:

```yaml
name: SPM
packages:
  Codability:
    url: https://github.com/yonaskolb/Codability
    majorVersion: 0.2.1
localPackages:
 - ../../.. #XcodeGen itself
targets:
  App:
    type: application
    platform: iOS
    sources: [SPM]
    scheme: {}
    dependencies:
      - package: Codability
      - target: StaticLibrary
  StaticLibrary:
    type: library.static
    platform: iOS
    sources: StaticLibrary
    dependencies:
      - package: Codability
      - sdk: UIKit.framework # <- the addition
```

## Screenshot
![Screenshot of Xcode with the incorrect linkage of the SwiftPM package](https://user-images.githubusercontent.com/23453/71688412-ce0f0f00-2d6d-11ea-9d01-c08f9ec42876.png)

**Comment by chrisballinger** [comment]
I am also seeing this issue, for a similar configuration. I think it might be a bug in SPM itself.

For instance:

```yml
name: PRODUCTNAME
deploymentTarget: "12.0"
options:
  bundleIdPrefix: com.rightpoint
packages:
  BonMot:
    url: https://github.com/Rightpoint/BonMot.git
    from: 5.5.0
  Anchorage:
    url: https://github.com/Rightpoint/Anchorage.git
    from: 4.4.0
  Swiftilities:
    url: https://github.com/Rightpoint/Swiftilities.git
    branch: feature/swift-package-manager
configs:
  Debug: debug
  Develop: release
  Sprint: release
  AppStore: release
configFiles:
  Debug: xcconfig/Debug.xcconfig
  Develop: xcconfig/Develop.xcconfig
  Sprint: xcconfig/Sprint.xcconfig
  AppStore: xcconfig/AppStore.xcconfig
settings:
  PRODUCT_MODULE_NAME: $(TARGET_NAME)
targets:
  PRODUCTNAME:
    scheme:
      testTargets:
        - PRODUCTNAMETests
        - ServicesTests
    type: application
    platform: iOS
    sources: [Sources]
    dependencies:
      - target: Services
      - package: BonMot
      - package: Anchorage
      - package: Swiftilities
  PRODUCTNAMETests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: PRODUCTNAME
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/debug-PRODUCTNAME.app/debug-PRODUCTNAME
  ServicesTests:
    type: bundle.unit-test
    platform: iOS
    sources: [ServicesTests]
    dependencies:
      - target: Services
  Services:
    type: library.static
    platform: iOS
    sources: [Services]
    dependencies:
      - package: Swiftilities
```

I think just having any static library with a SPM dependency shared with an app target causes duplicate symbol issues.
