### ISSUE TITLE
Invalid version in packages makes Xcode crash

### ISSUE THREAD

**Issue by basvankuijck** [yonaskolb/XcodeGen#754]
* XcodeGen version: 2.11.0

I accidentally added the following package to my `packages` list:

```yaml
RxSwift:
  url: https://github.com/ReactiveX/RxSwift.git
  from: master
```
Where `from: master`, obviously, should either be `from: 5.0.1` or `branch: master`

'Unfortunately' xcodegen runs succesfully, but once I try to open the generated project, Xcode immediatelly shuts down for that specific project.

After some trial-n-error I found out it was of this specific issue.   
Which ofcourse should not be the way someone defines package dependencies, but a typo is easily made.
