### ISSUE TITLE
Localized resources are not detected correctly

### ISSUE THREAD

**Issue by djbe** [yonaskolb/XcodeGen#763]
I seem to be hitting the exact same issue as #80, namely that my `Localizable.strings(dict)` files (and `InfoPlist.strings` files) are not detected correctly and seen as loose files:

<img width="283" alt="Screenshot 2020-01-29 at 02 19 00" src="https://user-images.githubusercontent.com/641356/73319861-eb84ab00-423d-11ea-9132-2decc64ec534.png">

As you can see, strings files for storyboards are seen correctly, whereas normal strings files are not seen as language variations of the same file.

The directory structure is correct though:
```yaml
Application
  - Resources
    - Base.lproj
      - Authentication.storyboard
      - ... (only .storyboard files)
    - en.lproj
      - Authentication.strings
      - ... (other .strings files for storyboards)
      - InfoPlist.strings
      - Localizable.strings
      - Localizable.stringsdict
    - fr.lproj
      - Authentication.strings
      - ... (other .strings files for storyboards)
      - InfoPlist.strings
      - Localizable.strings
      - Localizable.stringsdict
```

My project file (mostly, the relevant bits):
```yaml
name: MultiSelector
targets:
  MultiSelector:
    type: application
    platform: iOS
    sources:
      - Application
    settings:
      base:
        INFOPLIST_FILE: Application/Resources/Info.plist
        PRODUCT_NAME: $(TARGET_NAME)
        SWIFT_VERSION: 5.0
```

Also tried using XcodeGen in another project, same issue, which is worse there 'cause that project has +-10 languages.
