### ISSUE TITLE
Invalid scheme settings generated for custom watch

### ISSUE THREAD

**Issue by nvapp360** [yonaskolb/XcodeGen#764]
When i created a watch scheme with different name, the scheme points to the {myApp}.app instead of {MyWatchApp}.app.

I didnt find any option to set the Executable* to point to the right .app file.

Executable* - _(Watch) Scheme -> Run -> Info -> Executable_

```
schemes:
  'Apple Watch':
     build:
       targets:
         Development: all
       parallelizeBuild: true
       buildImplicitDependencies: true
     run:
       config: Debug
       targets: MyWatchApp
```

This created the scheme, but the executable target was _{MyApp.app}_ instead of _{MyWatchApp.app}_

Can you point out if I am missing anything here?
