### ISSUE TITLE
Crash error occurred with XcodeGen 2.13.0 when including legacy targets

### ISSUE THREAD

**Issue by kkoudev** [yonaskolb/XcodeGen#769]
It is occurred crash in my project with XcodeGen 2.13.0.
This crash seems to occur when there is a legacy target.
And, this crash is not occurred with XcodeGen 2.12.0.

My project definition that seems to be the cause is below.

```
targets:
  MyApp:
    type: application
    platform: iOS
    dependencies:
      - target: build-env
        embed: false

  build-env:
    type: ""
    platform: iOS
    legacy:
      toolPath: $(SRCROOT)/../scripts/build_env_ios.sh
      arguments: $(ACTION)
      workingDirectory: $(SRCROOT)/..
      passSettings: true
```
