### ISSUE TITLE
Version can't be parsed in latest release

### ISSUE THREAD

**Issue by mbuchetics** [yonaskolb/XcodeGen#770]
```
packages:
  AlamofireImage:
    url: https://github.com/Alamofire/AlamofireImage
    revision: "4.0.0-beta.5"
```

This leads to the following error:
`Parsing project spec failed: Invalid version: 4.0.0-beta.5`

It used to work fine. I changed it to use the git revision for a workaround.
