### ISSUE TITLE
Consistency issue: unexpected multiple parents for object `xcconfig`

### ISSUE THREAD

**Issue by chrisballinger** [yonaskolb/XcodeGen#771]
When using custom xcconfigs at the project level, it seems that Xcodegen generates an orphaned group for the xcconfigs, which causes CocoaPods to fail until the project file is "fixed" by Xcode.

For example, given the following `project.yml`:

```yml
name: PRODUCTNAME
options:
  bundleIdPrefix: com.rightpoint
packages:
  BonMot:
    url: https://github.com/Rightpoint/BonMot.git
    from: 5.5.0
  Anchorage:
    url: https://github.com/Rightpoint/Anchorage.git
    from: 4.4.0
configs:
  Debug: debug
  Develop: release
  Sprint: release
  AppStore: release
configFiles:
  Debug: PRODUCTNAME/Resources/xcconfig/Debug.xcconfig
  Develop: PRODUCTNAME/Resources/xcconfig/Develop.xcconfig
  Sprint: PRODUCTNAME/Resources/xcconfig/Sprint.xcconfig
  AppStore: PRODUCTNAME/Resources/xcconfig/AppStore.xcconfig
targets:
  PRODUCTNAME:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: [PRODUCTNAME]
    dependencies:
      - target: Services
      - package: BonMot
      - package: Anchorage
  PRODUCTNAMETests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.0"
    sources: [PRODUCTNAMETests]
    dependencies:
      - target: Services
  Services:
    type: framework
    platform: iOS
    sources: [Services]
```

It will generate an Xcode project that is deemed invalid by the [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) gem:

```
$ bundle exec pod install
...
RuntimeError - [Xcodeproj] Consistency issue: unexpected multiple parents for object `xcconfig`: [<PBXGroup path=`Resources` UUID=`42D132E167CA6DBCCDED2615`>, <PBXGroup UUID=`65C752E3E9E65C0DF852998A`>]
```

Curiously, if you simply open the `PRODUCTNAME.xcodeproj` in Xcode, change any setting back and forth, and then run `pod install` again, it succeeds. It looks like this is because Xcode does some sort of error correction on the generated project file. Here's an interesting part of the diff.

```diff
-                               F1BE11E77973887FDB838436 /* xcconfig */,
```

Although this is sort of an issue at the intersection of XcodeGen and CocoaPods - because allowing Xcode to auto-fix the project file fixes the CocoaPods/Xcodeproj issue - I think that ultimately this is a defect in XcodeGen.

### Workaround
- Open generated `.xcodeproj` file in Xcode, change any setting back and forth to allow Xcode to fix the orphaned group
