### ISSUE TITLE
When trying to better isolate public and private headers, multiple group folders are created in the resulting Xcode project

### ISSUE THREAD

**Issue by mobileben** [yonaskolb/XcodeGen#773]
I was looking towards moving away from Pods and using prebuilt libraries. As part of the process I was experimenting using `xcodegen` to create Xcode project files for the pods.

When pods builds, it has a method for creating umbrella headers and public headers. For the most part I've been successful at creating Xcode projects which can build each pod. However I've run into a problem with FLEX. The podspec for FLEX indicates only one public header "FLEXManager.h". All their source is placed under a "Classes" directory. I tried using this rule to make "FLEXManager.h" public.

```
    sources:
      - path: ../Pods/FLEX/Classes/FLEXManager.h
        headerVisibility: public
      - path: ../Pods/FLEX/Classes/
        includes: 
          - "**/*.[hm]"
        excludes: 
          - "FLEXManager.h"
        headerVisibility: private
```

The net result of this, however is it creates 2 Classes group folders.

<img width="195" alt="Screen Shot 2020-02-05 at 11 48 51 AM" src="https://user-images.githubusercontent.com/536780/73877498-992f2580-480d-11ea-9256-6358e05c12e5.png">

I've also tried this variation and it seems to nest a Classes group folder underneath another.

```
    sources:
      - path: ../Pods/FLEX/Classes/FLEXManager.h
        headerVisibility: public
        group: Classes
      - path: ../Pods/FLEX/Classes/
        includes: 
          - "**/*.[hm]"
        excludes: 
          - "FLEXManager.h"
        headerVisibility: private
        group: Classes
```
<img width="225" alt="Screen Shot 2020-02-05 at 11 47 25 AM" src="https://user-images.githubusercontent.com/536780/73877539-b663f400-480d-11ea-98b4-9750483b3474.png">

I would expect only one Classes folder.

I've tried other variations that have resulted in one Classes folder, but in doing so, "FLEXManager.h" is treated as private.

Is there either a way of handling this properly? Or is this an issue with xcodegen?
