### ISSUE TITLE
[Question] Star dependencies issue

### ISSUE THREAD

**Issue by mackoj** [yonaskolb/XcodeGen#774]
Hi,

I have a dependency issue.

My app depend on multiple Framework that dependents to the same SPM dependency. 

App -> FrameworkA -> SPM-Dependency1
App -> FrameworkB -> SPM-Dependency1
App -> SPM-Dependency1

I have this error message 

```
Swift package product 'SPM-Dependency1' is linked as a static library by 'App' and 'FrameworkA'. This will result in duplication of library code.
```

How should I express this with `XcodeGen` ?

Possible solutions:

- How can I say that I have weak dependency on `SPM-Dependency1` ?
- How can I say that `SPM-Dependency1` should be dynamically linked to everyone ?

Thanks,

**Comment by mackoj** [comment]
I did try this it did compile but I have to remove `SPM-Dependency1` from the `App`.

```
  FrameworkA:
    type: framework
    platform: iOS
    sources: [FrameworkA]
    dependencies:
      - package: SPM-Dependency1
        link: false
```
