### ISSUE TITLE
How to include different GoogleService-Info.plist for different build configurations?

### ISSUE THREAD

**Issue by kornerr** [yonaskolb/XcodeGen#781]
I need different plist files for stage and release builds.
Is there a way to include different GoogleService-Info.plist for different build configurations?

**Comment by liamnichols** [comment]
I don't think the project spec allows for conditionally including files based on build config, only target... I work around this by expanding build settings into a single plist file using a custom build rule... 

In my spec, I have a settings group defined like this:

```yml
settingGroups:
  # AppKeys defines custom build settings that often resemble build secrets or configuration
  # dependent settings. These values can then be injected into the binary or associated
  # bundle resources during other steps in the build process.
  AppKeys:
    base:
      # The API Key is for the Firebase project and remains the same across all "Apps" (Build Configurations)
      GOOGLE_API_KEY: FFFFFFFFFFFFFFFF
    configs:
      Debug:
        GOOGLE_APP_ID: AAAAAAAAAAAAAAAA
        GOOGLE_CLIENT_ID: AAAAAAAAAAAAAAAA-AAAAAAAAAAAAAAAA.apps.googleusercontent.com
        GOOGLE_REV_CLIENT_ID: com.googleusercontent.apps. AAAAAAAAAAAAAAAA-AAAAAAAAAAAAAAAA
      Testing:
        GOOGLE_APP_ID: BBBBBBBBBBBBBBBB
        GOOGLE_CLIENT_ID: BBBBBBBBBBBBBBBB-BBBBBBBBBBBBBBBB.apps.googleusercontent.com
        GOOGLE_REV_CLIENT_ID: com.googleusercontent.apps.BBBBBBBBBBBBBBBB-BBBBBBBBBBBBBBBB
      Release:
        GOOGLE_APP_ID: CCCCCCCCCCCCCCCC
        GOOGLE_CLIENT_ID: CCCCCCCCCCCCCCCC-CCCCCCCCCCCCCCCC.apps.googleusercontent.com
        GOOGLE_REV_CLIENT_ID: com.googleusercontent.apps.CCCCCCCCCCCCCCCC-CCCCCCCCCCCCCCCC
```

Since the build system in Xcode will not do the variable expansion in regular plist files like it does in Info.plist or Entitlement files, we have to use a different tool and a custom build rule.. I build a small tool called [PlistPal](https://github.com/liamnichols/plistpal) to do just that:

```yml
#
# Targets
#
targets:
  # Global represents the core iOS application target
  Global:
    templates: [GlobalTargetBase]
    type: application
    settings:
      groups: [AppKeys]
    buildRules:
      # The PlistPal build rule will manually package each file with the `.plist` extension by first running
      # it through the `plistpal` command line tool where it will expand variables using the build settings
      # in the current environment. This is used to inject keys into configuration files such as the
      # GoogleService-Info.plist where the keys vary between build configurations.
      - name: "[CKPD] Run PlistPal"
        filePattern: "*.plist"
        script: "mint run PlistPal plistpal --input \"${SCRIPT_INPUT_FILE}\" --output \"${SCRIPT_OUTPUT_FILE_0}\" --format binary --expand-variables"
        outputFiles: ["$(DERIVED_FILE_DIR)/$(INPUT_FILE_NAME)"]
```

Then my **GoogleService-Info.plist** file looks like the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>AD_UNIT_ID_FOR_BANNER_TEST</key>
        <string>...</string>
        <key>AD_UNIT_ID_FOR_INTERSTITIAL_TEST</key>
        <string>...</string>
        <key>CLIENT_ID</key>
        <string>${GOOGLE_CLIENT_ID}</string>
        <key>REVERSED_CLIENT_ID</key>
        <string>${GOOGLE_REV_CLIENT_ID}</string>
        <key>API_KEY</key>
        <string>${GOOGLE_API_KEY}</string>
        <key>GCM_SENDER_ID</key>
        <string>...</string>
        <key>PLIST_VERSION</key>
        <string>1</string>
        <key>BUNDLE_ID</key>
        <string>${PRODUCT_BUNDLE_IDENTIFIER}</string>
        <key>PROJECT_ID</key>
        <string>...</string>
        <key>STORAGE_BUCKET</key>
        <string>...</string>
        <key>IS_ADS_ENABLED</key>
        <true/>
        <key>IS_ANALYTICS_ENABLED</key>
        <true/>
        <key>IS_APPINVITE_ENABLED</key>
        <false/>
        <key>IS_GCM_ENABLED</key>
        <true/>
        <key>IS_SIGNIN_ENABLED</key>
        <true/>
        <key>GOOGLE_APP_ID</key>
        <string>${GOOGLE_APP_ID}</string>
        <key>DATABASE_URL</key>
        <string>https://cookpad-jp-api-project-930836009540.firebaseio.com</string>
</dict>
</plist>
```

If you only want to run that one specific plist via PlistPal then you can also do the same with a preBuildScript, hope it helps!

Note you might also need to declare some of the other properties if you are using multiple Firebase Projects... I only have to inject the three since I use one project with multiple apps within it so only the app specific values differ

**Comment by liamnichols** [comment]
I don't think the project spec allows for conditionally including files based on build config, only target... I work around this by expanding build settings into a single plist file using a custom build rule... 

In my spec, I have a settings group defined like this:

```yml
settingGroups:
  # AppKeys defines custom build settings that often resemble build secrets or configuration
  # dependent settings. These values can then be injected into the binary or associated
  # bundle resources during other steps in the build process.
  AppKeys:
    base:
      # The API Key is for the Firebase project and remains the same across all "Apps" (Build Configurations)
      GOOGLE_API_KEY: FFFFFFFFFFFFFFFF
    configs:
      Debug:
        GOOGLE_APP_ID: AAAAAAAAAAAAAAAA
        GOOGLE_CLIENT_ID: AAAAAAAAAAAAAAAA-AAAAAAAAAAAAAAAA.apps.googleusercontent.com
        GOOGLE_REV_CLIENT_ID: com.googleusercontent.apps. AAAAAAAAAAAAAAAA-AAAAAAAAAAAAAAAA
      Testing:
        GOOGLE_APP_ID: BBBBBBBBBBBBBBBB
        GOOGLE_CLIENT_ID: BBBBBBBBBBBBBBBB-BBBBBBBBBBBBBBBB.apps.googleusercontent.com
        GOOGLE_REV_CLIENT_ID: com.googleusercontent.apps.BBBBBBBBBBBBBBBB-BBBBBBBBBBBBBBBB
      Release:
        GOOGLE_APP_ID: CCCCCCCCCCCCCCCC
        GOOGLE_CLIENT_ID: CCCCCCCCCCCCCCCC-CCCCCCCCCCCCCCCC.apps.googleusercontent.com
        GOOGLE_REV_CLIENT_ID: com.googleusercontent.apps.CCCCCCCCCCCCCCCC-CCCCCCCCCCCCCCCC
```

Since the build system in Xcode will not do the variable expansion in regular plist files like it does in Info.plist or Entitlement files, we have to use a different tool and a custom build rule.. I build a small tool called [PlistPal](https://github.com/liamnichols/plistpal) to do just that:

```yml
#
# Targets
#
targets:
  # Global represents the core iOS application target
  Global:
    templates: [GlobalTargetBase]
    type: application
    settings:
      groups: [AppKeys]
    buildRules:
      # The PlistPal build rule will manually package each file with the `.plist` extension by first running
      # it through the `plistpal` command line tool where it will expand variables using the build settings
      # in the current environment. This is used to inject keys into configuration files such as the
      # GoogleService-Info.plist where the keys vary between build configurations.
      - name: "[CKPD] Run PlistPal"
        filePattern: "*.plist"
        script: "mint run PlistPal plistpal --input \"${SCRIPT_INPUT_FILE}\" --output \"${SCRIPT_OUTPUT_FILE_0}\" --format binary --expand-variables"
        outputFiles: ["$(DERIVED_FILE_DIR)/$(INPUT_FILE_NAME)"]
```

Then my **GoogleService-Info.plist** file looks like the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>AD_UNIT_ID_FOR_BANNER_TEST</key>
        <string>...</string>
        <key>AD_UNIT_ID_FOR_INTERSTITIAL_TEST</key>
        <string>...</string>
        <key>CLIENT_ID</key>
        <string>${GOOGLE_CLIENT_ID}</string>
        <key>REVERSED_CLIENT_ID</key>
        <string>${GOOGLE_REV_CLIENT_ID}</string>
        <key>API_KEY</key>
        <string>${GOOGLE_API_KEY}</string>
        <key>GCM_SENDER_ID</key>
        <string>...</string>
        <key>PLIST_VERSION</key>
        <string>1</string>
        <key>BUNDLE_ID</key>
        <string>${PRODUCT_BUNDLE_IDENTIFIER}</string>
        <key>PROJECT_ID</key>
        <string>...</string>
        <key>STORAGE_BUCKET</key>
        <string>...</string>
        <key>IS_ADS_ENABLED</key>
        <true/>
        <key>IS_ANALYTICS_ENABLED</key>
        <true/>
        <key>IS_APPINVITE_ENABLED</key>
        <false/>
        <key>IS_GCM_ENABLED</key>
        <true/>
        <key>IS_SIGNIN_ENABLED</key>
        <true/>
        <key>GOOGLE_APP_ID</key>
        <string>${GOOGLE_APP_ID}</string>
        <key>DATABASE_URL</key>
        <string>...</string>
</dict>
</plist>
```

If you only want to run that one specific plist via PlistPal then you can also do the same with a preBuildScript, hope it helps!

Note you might also need to declare some of the other properties if you are using multiple Firebase Projects... I only have to inject the three since I use one project with multiple apps within it so only the app specific values differ
