### ISSUE TITLE
member of multiple groups indicates a malformed project or loss of `compilerFlags`

### ISSUE THREAD

**Issue by mobileben** [yonaskolb/XcodeGen#782]
We are looking to move away from pods. As part of the process, we care converting the pods to `yml` so we can generate Xcode project files. This is a precautionary step in case we ever want to be able to debug a pod.

I'm working on FBSDKCoreKit, which has one file which doesn't use ARC. However, I am having a difficult time getting it to work right.

It's either my syntax/ordering or perhaps a bug.

If I use this to define the sources

```
    sources:
      - path: ../Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal_NoARC/FBSDKDynamicFrameworkLoader.m
        compilerFlags: "-fno-objc-arc"
      - path: ../Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit
        includes: "**/*.[hm]"
        excludes: Internal_NoARC/FBSDKDynamicFrameworkLoader.m
```

I receive a warning like the following. The build will work, however.

> 2020-02-13 14:03:55.266 xcodebuild[4804:1782108] warning:  The file reference for "../Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal_NoARC" is a member of multiple groups ("FBSDKCoreKit" and ""); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.

Note that I've gotten rid of the `excludes` and the same error message will result. 

I tried to re-order, but ordering does seem to matter, since if I re-order like the following

```
    sources:
      - path: ../Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit
        includes: "**/*.[hm]"
        excludes: Internal_NoARC/FBSDKDynamicFrameworkLoader.m
      - path: ../Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal_NoARC/FBSDKDynamicFrameworkLoader.m
        compilerFlags: "-fno-objc-arc"
```

`-fno-objc-arc` will not be set.

<img width="982" alt="Screen Shot 2020-02-13 at 2 09 14 PM" src="https://user-images.githubusercontent.com/536780/74483108-9ca85980-4e6a-11ea-9dc7-19927e352e57.png">

Is my syntax incorrect? Or is this a case where xcodegen cannot properly handle it? Or do I just accept the warning and ignore it?
