### ISSUE TITLE
Dependencies: SPM dynamic dependency embed & sign

### ISSUE THREAD

**Issue by alexruperez** [yonaskolb/XcodeGen#784]
Similar to #271 but for Swift Package Manager dynamic dependencies declared like:

```swift
// swift-tools-version:5.1
import PackageDescription

let package = Package(
    name: "Components",
    platforms: [
        .iOS(.v12),
    ],
    products: [
        .library(name: "Components", type: .dynamic, targets: ["Components"]),
    ],
    targets: [
        .target(name: "Components", dependencies: []),
    ],
    swiftLanguageVersions: [.v5]
)
```

My project.yml is like:
```yaml
    type: application
    platform: iOS
    sources: Sources
    dependencies:
      - package: Components
        embed: true
```

I want my dynamic SPM dependency as Embed & Sign for application target:

![Captura de pantalla 2020-02-19 a las 16 35 06](https://user-images.githubusercontent.com/297950/74848318-d7f9cb00-5337-11ea-861a-854259f0c7f8.jpg)

To be included here:

![Captura de pantalla 2020-02-19 a las 16 35 34](https://user-images.githubusercontent.com/297950/74848408-eea02200-5337-11ea-998a-b36b9e9f9084.jpg)

@yonaskolb can you help me with config? Thanks! 😃
