### ISSUE TITLE
postGenCommand not executed even after the project file was created

### ISSUE THREAD

**Issue by nvapp360** [yonaskolb/XcodeGen#786]
I have set the postGenCommand but it is not executed even after the project file is created successfully. The project file is created and is usable. There are no configuration issues too. Is there any specifics that I need to check? 

```
name: ProjectName
options:
  postGenCommand: pod install
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "11.0"
  createIntermediateGroups: true
```
