### ISSUE TITLE
Adding common Localizable.strings files

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#80]
I have these Localizable settings under `resources/language` directory.
```
resources/language/
├── Base.lproj
│   └── Localizable.strings
└── ja.lproj
    └── Localizable.strings
```

I want to import them into separated target.
```yml
targets:
  LGTM:
    platform: macOS
    type: application
    sources:
      - LGTM
      - resources/language
  LGTM_iOS:
    platform: iOS
    type: application
    sources:
      - LGTM_iOS
      - resources/language
```

This spec ends-up with the files only added to `LGTM` target.
<img width="622" alt="screen shot 2017-09-30 at 7 29 25" src="https://user-images.githubusercontent.com/6007952/31038344-2e862284-a5b1-11e7-9c8f-e15a473a1dd1.png">

Also on Xcode, both files are displayed as same name, so maybe it's better if we could display the parent directory names for `Localizable.strings`.
