### ISSUE TITLE
Local package tesst in test target.

### ISSUE THREAD

**Issue by mkkroliks** [yonaskolb/XcodeGen#809]
Is there an option to add a local package tests target to the scheme? I'm trying to achieve this:

![Screen Shot 2020-03-19 at 15 57 11](https://user-images.githubusercontent.com/2151961/77081538-18ae3800-69fb-11ea-9860-06f8f87cce93.png)

My code:

```
packages: 
   SPMLocal:
       url: https://it.can/be/anything
       from: 2.0.0
localPackages: 
  - ../SPMLocal

ProjectUnitTests:
    build:
      targets:
        SPMLocal/SPMLocalTests: [test]

```
I'm getting an error because SPMLocal is not found as a `projectReference`. When I'm adding SPMLocal as a projectReference I'm getting an error that `.pbxproj` can't be found.
