### ISSUE TITLE
How to create a Static Framework target?

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#813]
I looked for the documentation for it, but couldn't find.
So will leave this issue as an instruction.
Please tell me if anything is missing on my side. 
Thought initially that `type: framework.static` would do, but didn't. The app failed to install.

### project.yml

```yml
targets
  Abceed:
    platform: iOS
    type: application
    sources:
      - Abceed
    dependencies:
      - target: AbceedUI
        link: false # link is unnecessary
        embed: false # embed is unnecessary
  AbceedUI:
    platform: iOS
    type: framework
    settings:
      MACH_O_TYPE: staticlib
    sources:
      - AbceedUI
```

### confirm

that resulted artifact is really a static framework:

```console
$ file /Users/t8s/Library/Developer/Xcode/DerivedData/Abceed-egznkqfzvpchhxdxyqozquwpzdyi/Build/Products/Debug-iphonesimulator/AbceedUI.framework/AbceedUI
/Users/t8s/Library/Developer/Xcode/DerivedData/Abceed-egznkqfzvpchhxdxyqozquwpzdyi/Build/Products/Debug-iphonesimulator/AbceedUI.framework/AbceedUI: current ar archive
```

and it is eventually merged into the executable.

```console
$ strings /Users/t8s/Library/Developer/Xcode/DerivedData/Abceed-egznkqfzvpchhxdxyqozquwpzdyi/Build/Products/Debug-iphonesimulator/Abceed.app/Abceed | grep AbceedUI | head
_TtC8AbceedUI8BookCell
/Users/t8s/dev/tmp/abceed/AbceedUI/BookDetailViewController.swift
AbceedUIBundle
AbceedUI.BookDetailViewController
_TtC8AbceedUI24BookDetailViewController
_TtC8AbceedUIP33_E8918023CBE8327D8ADC478372B8E4B613ThumbnailView
_TtC8AbceedUIP33_E8918023CBE8327D8ADC478372B8E4B66Button
_TtC8AbceedUIP33_E8918023CBE8327D8ADC478372B8E4B612MybookButton
_TtC8AbceedUIP33_E8918023CBE8327D8ADC478372B8E4B69BuyButton
/Users/t8s/dev/tmp/abceed/AbceedUI/BookListCollectionCell.swift
```

Working example: https://github.com/toshi0383/abceed

**Comment by jsorge** [comment]
The target type needs to be `library.static`. So your example would look like this:

```
  AbceedUI:
    platform: iOS
    type: library.static
    sources:
      - AbceedUI
```
