### ISSUE TITLE
Independent Watch App - Invalid Archive - TestFlight Rejection

### ISSUE THREAD

**Issue by leogdion** [yonaskolb/XcodeGen#845]
As a followup to issue #595 ...

With an archive built from an XcodeGen Xcode project, I ran into an issue with **deploying the Watch app to TestFlight**: 
<img width="630" alt="Screen Shot 2020-04-23 at 8 04 09 AM" src="https://user-images.githubusercontent.com/1036388/80218068-af7b9f00-860e-11ea-8e8b-5575688da958.png">

Using an Xcode project created via Xcode, deployment to TestFlight worked fine. 

Here's **the differences between the two archives' .app file**:
<img width="1392" alt="Screen Shot 2020-04-24 at 9 38 34 AM" src="https://user-images.githubusercontent.com/1036388/80218698-83ace900-860f-11ea-8e18-e0f39895f896.png">

The big differences I notice are:

- Notice the compiled _Launchscreen.storyboardc_ under _Base.lproj_ which Xcode adds automatically.
- As well the _Assets.car_ file containing the app icons.

**Both of these contain no source, so Xcode appears to be adding these automatically during archiving.**

Here's what my _project.yml_ looks like:
```yml
name: Heartwitch
options:
  bundleIdPrefix: com.brightdigit
settings:
  DEVELOPMENT_TEAM: MLT7M394S7
  CODE_SIGN_IDENTITY: "Apple Development"
  CODE_SIGN_STYLE: Automatic
  MARKETING_VERSION: "1.1"
  CURRENT_PROJECT_VERSION: "28"
  SDKROOT: iphoneos
packages:
  HeartwitchKit:
    path: ./Packages/HeartwitchKit
fileGroups:
  - "Assets"
targets:
  Heartwitch-watchOS-app.watchkitapp.watchkitextension:
    type: watchkit2-extension
    platform: watchOS
    dependencies:
      - package: HeartwitchKit
      - sdk: HealthKit.framework
    sources: 
      - path: "Sources/Extension"
        name: Sources
        group: Extension
      - path: "PLists/Extension"
        name: Support
        group: Extension
    entitlements:
      path: PLists/Extension/Extension.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    info: 
      path: PLists/Extension/Info.plist
      properties:
        WKWatchOnly: true
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Heartwitch
        NSExtension:
            NSExtensionAttributes:
              WKAppBundleIdentifier : com.brightdigit.Heartwitch-watchOS-app.watchkitapp
            NSExtensionPointIdentifier: com.apple.watchkit
        WKBackgroundModes: ["workout-processing"]
        NSHealthShareUsageDescription: "Heartwitch would like to have permission to read these samples for broadcast."
        NSHealthUpdateUsageDescription: "Heartwitch would like to have permission to update workouts and health samples."
  Heartwitch-watchOS-app.watchkitapp:
    type: application.watchapp2
    platform: watchOS
    dependencies:
      - target: "Heartwitch-watchOS-app.watchkitapp.watchkitextension"
    sources: 
      - path: "Sources/Application"
        name: Sources
        group: Application
      - path: "PLists/Application"
        name: Support
        group: Application
    info:
      path: PLists/Application/Info.plist
      properties:
        WKWatchKitApp: true
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Heartwitch
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      PRODUCT_NAME: Heartwitch
      PRODUCT_MODULE_NAME: Heartwitch_watchOS_app_watchkitapp_watchkitextension
      IBSC_MODULE: Heartwitch_watchOS_app_watchkitapp_watchkitextension
  Heartwitch-watchOS-app:
    type: application.watchapp2-container
    platform: iOS
    dependencies:
      - target: "Heartwitch-watchOS-app.watchkitapp"
    sources: 
      - path: "PLists/Container"
        name: Support
        group: Container
    info:
      path: plists/Container/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        NSHealthShareUsageDescription: "Heartwitch would like to have permission to read these samples for broadcast."
        NSHealthUpdateUsageDescription: "Heartwitch would like to have permission to update workouts and health samples."
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Heartwitch
    settings:
      PRODUCT_NAME: Heartwitch
      TARGETED_DEVICE_FAMILY: 1
```

Let me know if you have any thoughts on this or how I might need to correct my _project.yml_ file.

Thanks,
Leo
