### ISSUE TITLE
Support for ${platform} within template and access to ${target_name} without platform suffix

### ISSUE THREAD

**Issue by daltonclaybrook** [yonaskolb/XcodeGen#848]
When a target is defined with multiple platforms, XcodeGen will generate a unique target for each platform and append the platform name as a suffix. For example, given this spec:
```yaml
PlatformDemoKit:
    type: framework
    platform: [iOS, tvOS, watchOS]
    templates:
        - SharedSource
```
two platforms will be generated: `PlatformDemoKit_iOS` and `PlatformDemoKit_tvOS`. When accessing the `${target_name}` variable from a template, the variable seems to include this suffix, which makes sense because it is part of the full target name.

I believe it would also be beneficial to be able to access the target name without the platform suffix and to have access to the `${platform}` variable from within a template. This would make templates much more flexible.

Consider the following template:
```yaml
targetTemplates:
    SharedSource:
        sources:
            - path: ${target_name_no_suffix}
              includes:
                  - "Shared/**"
                  - "*${platform}*/**"
```
This template is very similar to the way my targets are set up in my project today. Namely, all platforms for a target share the same root directory (the target name without the suffix). Beneath that, shared sources live in a `Shared` directory, and platform-specific sources live in a directory that contains the platform name. For example, if a source file lives at `iOS+tvOS/Foo.swift`, it will be included in `PlatformDemoKit_iOS` and `PlatformDemoKit_tvOS`, but not `PlatformDemoKit_watchOS`.

This does not appear to be possible today using templates because I cannot access the target name without the platform suffix, nor can I access the `${platform}` variable.

I used `${target_name_no_suffix}` above for illustration purposes, but I do not have a great idea for what the actual name should be. Perhaps something like `${target_root}` or `${target_prefix}`?

Please let me know if I'm overlooking an existing XcodeGen feature that makes this request superfluous. I'm aware of the `templateAttributes` field, but these attributes seem useful as standard variables along with `${target_name}.
