### ISSUE TITLE
Multi-platform target dependency on another multi-platform target

### ISSUE THREAD

**Issue by mattrobmattrob** [yonaskolb/XcodeGen#854]
Reference a multi-platform target from another multi-platform target declaration.

**Desired:**

So, spec similar to this:
```
name: Frameworks
targets:
  Foo:
    type: framework
    platform: [iOS, watchOS]
    sources: [Foo]
  Bar:
    type: framework
    platform: [iOS, watchOS]
    sources: [Bar]
    dependencies:
      - target: Foo
```
The resolved dependency should be something like `Foo_iOS` (in `Bar_iOS`) and `Foo_watchOS` (in `Bar_watchOS`). It won't resolve since there's no real `Foo` target since it's multi-platform.

```
$ xcodegen
2 Spec validations errors:
	- Target "Bar_iOS" has invalid dependency: "Foo"
	- Target "Bar_watchOS" has invalid dependency: "Foo"
```

**Workaround:**

Here's an example of what the inferred spec should be, for clarity:
```
name: Frameworks
targets:
  Foo:
    type: framework
    platform: [iOS, watchOS]
    sources: [Foo]
  Bar_iOS:
    type: framework
    platform: iOS
    sources: [Bar]
    dependencies:
      - target: Foo_iOS
  Bar_watchOS:
    type: framework
    platform: watchOS
    sources: [Bar]
    dependencies:
      - target: Foo_watchOS
```
```
$ xcodegen
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/mattrobinson/Desktop/xcodegen_test/Frameworks.xcodeproj
```

**Question:**

Will this require changes to `xcodegen` to support this functionality or is there already a way to do this without a duplicated target reference?

**Comment by mattrobmattrob** [comment]
🤦 Solved this myself embarrassingly quickly using the templating feature. Example:

```
name: Frameworks
schemes:
  All:
    build:
      targets:
        Foo_iOS: all
        Foo_watchOS: all
        Bar_iOS: all
        Bar_watchOS: all
targets:
  Foo:
    type: framework
    platform: [iOS, watchOS]
    sources: [Foo]
  Bar:
    type: framework
    platform: [iOS, watchOS]
    sources: [Bar]
    dependencies:
      - target: Foo_${platform}
```

This will create `Frameworks.xcodeproj` and the `All` scheme works as expected. 👍
