### ISSUE TITLE
Is it possible to add resources by pattern?

### ISSUE THREAD

**Issue by Beniamiiin** [yonaskolb/XcodeGen#855]
I tried this way, but it doesn't work.
```
sources:
- path: ../../Carthage/Build/iOS/Intercom.framework/*.bundle
  buildPhase: resources
- path: ../../Carthage/Build/iOS/IDNowSDK.framework/*.jpg
  buildPhase: resources
- path: ../../Carthage/Build/iOS/IDNowSDK.framework/*.bundle
  buildPhase: resources
- path: ../../Carthage/Build/iOS/IDNowSDK.framework/*.mp4
  buildPhase: resources
```

**Comment by brentleyjones** [comment]
Does this work for you?
```
- path: ../../Carthage/Build/iOS/Intercom.framework/
   buildPhase: resources
   includes:
     - '**/*.bundle'
- path: ../../Carthage/Build/iOS/IDNowSDK.framework/
   buildPhase: resources
   includes:
     - '**/*.bundle'
     - '**/*.jpg'
     - '**/*.mp4'
```
