### ISSUE TITLE
Link and embed all nested Carthage dependencies for macOS

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#86]
# Motivation
With spec like this,
```yml
targets:
  LGTM:
    platform: macOS
    type: application
    sources: LGTM
    dependencies:
      - target: LGTMKit_macOS
  LGTMKit:
    type: framework
    platform: [iOS, macOS]
    sources: LGTMKit
    dependencies:
      - carthage: APIKit
```
Generate xcodeproj like this.
<img width="708" alt="screen shot 2017-10-14 at 5 49 12" src="https://user-images.githubusercontent.com/6007952/31565907-732dd402-b0a3-11e7-9266-ca0ed511a4d4.png">

Related: https://github.com/yonaskolb/XcodeGen/pull/82
