### ISSUE TITLE
Add dependency but not compile it

### ISSUE THREAD

**Issue by skelet2394** [yonaskolb/XcodeGen#868]
I'm trying to add binary from SPM-package to dependencies, but this binary is just running in one of Build Phasses on x86-64 arch and must not be included in compilation process of iOS app.

Thats how I include binary in project
```
packages:
  R.Swift:
    url: https://github.com/mac-cain13/R.swift
    from: 5.0.0

targets:
  Shared:
    dependencies:
      - package: R.Swift
        product: rswift
```

But this way it also appears in "Frameworks and Libraries" section and compiler gives me error:
`***.xcodeproj Building for iOS, but the linked item 'rswift' is building for macOS. You may need to configure 'rswift' to build for iOS.'
After i delete from this section (dependency only appear in "Dependencies" section in Build Phases) everything becomes fine

Is there any way i can fix it using xcodegen without external scripts removing it after generation?
