### ISSUE TITLE
`transitivelyLinkDependencies` does not embed all

### ISSUE THREAD

**Issue by akaralar** [yonaskolb/XcodeGen#870]
Hello, we are using xcodegen and our setup looks like

1 main app project - 1 target
30 projects for "modules" that consists of
- a dynamic framework target
- an app target (playground for the framework) that embeds the dynamic framework target

Let's say we have dynamic frameworks `A`, `A1`, `A2`, `A3`, and `A11`, all of which are in separate projects, so that 
( `->` means `depends on`)
```
A -> A1 -> A11
A -> A2
A -> A3
```

and also in the same project with dynamic framework `A`, there is also an app target, `A-Playground`, so that
```
A-Playground -> A
```

We normally add every dependency explicitly in the main app target so all of the dynamic frameworks are embedded correctly, no problems

However for `A-Playground`, when I set `transitivelyLinkDependencies: true`, I see that `A1`, `A2` and `A3` are linked and embedded properly, however `A11` isn't. Is this expected behavior?

<details><summary> Our directory structure and .yml definitions </summary>

  <details><summary>Directory structure</summary>

```
├── A
│   ├── A
│   │   ├── Info.plist
│   │   ├── A.h
│   │   └── src
│   │       └── A.swift
│   ├── A.xcodeproj
│   └── A.yml
├── A1
│   ├── A1
│   │   ├── Info.plist
│   │   ├── A1.h
│   │   └── src
│   │       └── A1.swift
│   ├── A1.xcodeproj
│   └── A1.yml
├── A2
│   ├── A2
│   │   ├── Info.plist
│   │   ├── A2.h
│   │   └── src
│   │       └── A2.swift
│   ├── A2.xcodeproj
│   └── A2.yml
├── A3
│   ├── A3
│   │   ├── Info.plist
│   │   ├── A3.h
│   │   └── src
│   │       └── A3.swift
│   ├── A3.xcodeproj
│   └── A3.yml
├── A11
│   ├── A11
│   │   ├── Info.plist
│   │   ├── A11.h
│   │   └── src
│   │       └── A11.swift
│   ├── A11.xcodeproj
│   └── A11.yml
└── framework_templates.yml
```
</details>

<details><summary> A.yml </summary>

```yml
name: A
include:
  - path: ../framework_templates.yml
    relative: true
projectReferences:
  A1:
    path: ../A1/A1.xcodeproj
  A2:
    path: ../A2/A2.xcodeproj
  A3:
    path: ../A3/A3.xcodeproj

targets:
  A:
    platform: iOS
    type: framework
    templates:
      - DynamicFramework
    templateAttributes:
      targetName: A
      moduleName: A
    dependencies:
      - target: A1/A1
      - target: A2/A2
      - target: A3/A3

  A-Playground:
    platform: iOS
    type: application
    templates:
      - PlaygroundApp
    templateAttributes:
      targetName: A-Playground
      moduleName: A
    dependencies:
      - target: A
```

</details>

<details><summary> A1.yml </summary>

```yml
name: A1
include:
  - path: ../framework_templates.yml
    relative: true
projectReferences:
  A11:
    path: ../A11/A11.xcodeproj

targets:
  A1:
    platform: iOS
    type: framework
    templates:
      - DynamicFramework
    templateAttributes:
      targetName: A1
      moduleName: A1
    dependencies:
      - target: A11/A11
```

</details>

<details> 
<summary>  framework_templates.yml </summary>

```yml
targetTemplates:
  DynamicFramework:
    sources:
      - ${moduleName}/${targetName}
    scheme:
      gatherCoverageData: true

  PlaygroundApp:
    sources:
      - ${moduleName}/${targetName}
    transitivelyLinkDependencies: true
    dependencies:
      - target: ${moduleName}

```

</details>

PS: I left unrelated stuff (like configs, test targets etc) out for easier visual parsing of yml files, if you're interested I can share the full blown versions, but I don't think there is anything related to dependencies etc there.

</details>
