### ISSUE TITLE
DeploymentTarget and configFiles in options from Yaml file affect each other？

### ISSUE THREAD

**Issue by sfdux** [yonaskolb/XcodeGen#874]
I have a question for deploymentTarget and configFiles in options. See my yaml 
 file below: 
name: XXX

options:
  minimumXcodeGenVersion: "2.11.0"
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: "10.0"
  generateEmptyDirectories: true
configFiles:
    Debug: "xcconfig/Project-Debug.xcconfig"
    Release: "xcconfig/Project-Release.xcconfig"

But the value of iOS Deployment Target is empty...See the screenshot below:
![image](https://user-images.githubusercontent.com/298430/83245942-04916e80-a1d4-11ea-8c61-65abe97a3079.png)

If I remove the configFiles from my yaml file, iOS Deployment Target is "10.0". It's very strange. 
Who can help me？😂😂

**Comment by yonaskolb** [comment]
Hi @sfdux, can you show your build settings page, filtered for `DEPLOYMENT_TARGET`?
<img width="925" alt="Screen Shot 2020-05-30 at 10 52 11 am" src="https://user-images.githubusercontent.com/2393781/83315488-9f855980-a263-11ea-8b41-c5030268aad5.png">

**Comment by sfdux** [comment]
Thanks for your prompt reply. See my build settings page below:
![image](https://user-images.githubusercontent.com/298430/83353100-c5ede680-a382-11ea-9f8c-a4f259ea9dcb.png)
My yaml file:
name: ToosieSlide
options:
  minimumXcodeGenVersion: "2.11.0"
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: "10.0"
  generateEmptyDirectories: true
configFiles:
  Debug: "xcconfig/Project-Debug.xcconfig"
  Release: "xcconfig/Project-Release.xcconfig"
targets:
... DEPLOYMENT_TARGET is Not iOS 10.0?🤔

**Comment by sfdux** [comment]
Thanks for your prompt reply. See my build settings page below:
![image](https://user-images.githubusercontent.com/298430/83353259-d6529100-a383-11ea-9db7-757988eb4d3f.png)
My Yaml File:
name: ToosieSlide
options:
minimumXcodeGenVersion: "2.11.0"
indentWidth: 2
tabWidth: 2
deploymentTarget:
iOS: "10.0"
generateEmptyDirectories: true
configFiles:
Debug: "xcconfig/Project-Debug.xcconfig"
Release: "xcconfig/Project-Release.xcconfig"
targets:
... 
Why DEPLOYMENT_TARGET is not iOS 10.0 in build settings page?🤔

**Comment by shakfu** [comment]
I have a similar problem: `deploymentTarget` is not having any effect at the project or target level (I have `configFiles` set at the project level):

Ideally, I thought (as per the docs), that I should be able to do something like this:

```yaml
name: demo
options:
  bundleIdPrefix: org.me
  deploymentTarget:
    macOS: "10.13"
settings:
  CODE_SIGN_IDENTITY: "-"
  DEVELOPMENT_TEAM: ""
  GCC_OPTIMIZATION_LEVEL: 0
  GCC_NO_COMMON_BLOCKS: No
  HEADER_SEARCH_PATHS:
    - $(PROJECT_HEADERS)
  INFOPLIST_FILE: $(SRCROOT)/../../../Info.plist
  LIBRARY_SEARCH_PATHS: $(PROJECT_LIBS)
  OTHER_LDFLAGS:
    - $(PROJECT_LDFLAGS)
  PRODUCT_NAME: $(TARGET_NAME)
configFiles:
  Debug: project.xcconfig
  Release: project.xcconfig
targets:
  foo:
    type: bundle
    platform: macOS
    sources:
      - foo.c
    dependencies:
      - sdk: CoreFoundation.framework
```

But I am having to actually to forgo `deploymentTarget` and set it at `target.settings` level:

```yaml
name: demo
options:
  bundleIdPrefix: org.me
settings:
  CODE_SIGN_IDENTITY: "-"
  DEVELOPMENT_TEAM: ""
  GCC_OPTIMIZATION_LEVEL: 0
  GCC_NO_COMMON_BLOCKS: No
  HEADER_SEARCH_PATHS:
    - $(PROJECT_HEADERS)
  INFOPLIST_FILE: $(SRCROOT)/../../../Info.plist
  LIBRARY_SEARCH_PATHS: $(PROJECT_LIBS)
  OTHER_LDFLAGS:
    - $(PROJECT_LDFLAGS)
  PRODUCT_NAME: $(TARGET_NAME)
configFiles:
  Debug: project.xcconfig
  Release: project.xcconfig
targets:
  foo:
    type: bundle
    platform: macOS
    sources:
      - foo.c
    dependencies:
      - sdk: CoreFoundation.framework
    settings:
      MACOSX_DEPLOYMENT_TARGET: "10.13"
```

It's no biggie, but I'd you should know since it directly contradicts what you have in the documented spec.
