### ISSUE TITLE
Glob not fully supported?

### ISSUE THREAD

**Issue by rvi** [yonaskolb/XcodeGen#886]
Hi,

I'm aware that Glob support was introduced with [this PR](https://github.com/yonaskolb/XcodeGen/pull/636).

That said it seems to work only to exclude some files. I'd like to include all Localizable.strings of my project in my app target. 

Something like:
```yml
targetTemplates:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - **/*.strings
```

Is it possible?
Thanks.

**Comment by yonaskolb** [comment]
Hi @rvi. A glob can be applied to either a `includes` or `excludes`. Try this
```yml
targetTemplates:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - path: {SOME_DIRECTORY}
       includes: [**/*.strings]
```
Also, not sure if you're trying to use a template or not, otherwise use `targets` instead of `targetTemplates`
