### ISSUE TITLE
createIntermediateGroups doesn't work for files outside of the project directory

### ISSUE THREAD

**Issue by segiddins** [yonaskolb/XcodeGen#889]
With the following project yaml:

```
---
name: Foo
options:
    createIntermediateGroups: true
targets:
    Foo-Target:
        type: framework
        platform: iOS
        sources:
            - { path: "../Source/A.h" }
            - { path: "../Source/A.swift" }
            - { path: "../Example/Source/A.swift" }
            - { path: "../Example/Source/B.swift" }
            - { path: "../Example/Source/C.swift" }
```

Two different top-level groups get created name `Source`

Ideally, group nesting would continue to happen for sources outside of the project directory, since Xcode supports that -- having a parent group (say Foo in this case, if that's the name of `..`), or directly nesting `Source` & `Example` as toplevel groups, would help de-clutter the project and avoid the proliferation of thousands of groups named `Sources` (in our actual generated project)
