### ISSUE TITLE
Clear default build settings

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#89]
It would be nice if there were a way to clear the default settings XcodeGen provides. This is useful if you define all your settings in xcconfig files, so when you generate the project, you don't want its default settings to shadow yours. I almost expected it to with this configuration:

```yaml
name: Project
settings:
  base: []
targets:
  Project:
    type: application
    platform: iOS
```

But I understand these `base` settings are just additive to the project. In the meantime I might use [xcodeproj](https://github.com/cocoapods/xcodeproj) to wipe these settings out after project generation.
