### ISSUE TITLE
Resource files included in fileGroups don't get correctly added to targets

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#90]
With this configuration:

```yaml
name: Project
fileGroups:
  - Resources
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Resources
```

And this file structure:

```
.
├── Resources
│   └── en.lproj
│       └── Localizable.strings
└── project.yml
```

You end up with a project that doesn't have the `Localizable.strings` in the correct file path, associated with the target:

![image](https://user-images.githubusercontent.com/283886/31635106-8eee2826-b27a-11e7-8e8e-df4943c72ed5.png)

But you do end up with a reference in "Recovered References" that is correctly associated with the target:

![image](https://user-images.githubusercontent.com/283886/31635128-9e077100-b27a-11e7-9536-e75226022241.png)

Example project: [XcodeGenTest4.zip](https://github.com/yonaskolb/XcodeGen/files/1389068/XcodeGenTest4.zip)
