### ISSUE TITLE
Embed and CodeSign Options Don't Work for SDK Dependencies

### ISSUE THREAD

**Issue by leogdion** [yonaskolb/XcodeGen#905]
Regardless of settings in my `project.yml` under `dependencies`:
```
targets:
  CairoSVG:
    dependencies:
    - sdk: "Dependencies/libpng/1.6.37/lib/libpng16.16.dylib"
      root: SOURCE_ROOT
      embed: true
      implicit: true
      codeSign: true
...
```
<img width="544" alt="Screen Shot 2020-06-30 at 2 00 38 PM" src="https://user-images.githubusercontent.com/1036388/86160722-2c793800-bada-11ea-95b2-ba8be9c9d105.png">

If I added the dependencies in sources as well then they are embedded, however code signing doesn't work.
