### ISSUE TITLE
Use a Swift Package Product as a Dependency?

### ISSUE THREAD

**Issue by jsorge** [yonaskolb/XcodeGen#906]
I've got a Swift Package which has 2 output products that I want to use as dependencies in my project. Currently Xcodegen lets me link a package by name but my main target that I'm building needs to link to the products outputted by my Swift package. Is there a way to do this? Happy to provide some sample Package manifest and Xcodegen project files if that would be helpful.

**Comment by kwridan** [comment]
Hi @jsorge 

I believe this can be done by specifying both the `package:` and `product:` as a dependency.

e.g.

```yaml
name: MyApp
options:
  bundleIdPrefix: my.bundle.id
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 2.0.0
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [MyApp]
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: ComposableArchitecture
        product: ComposableCoreLocation
```

Both libraries will end up getting linked in the generated project

<img width="651" alt="Screenshot 2020-07-11 at 17 14 27" src="https://user-images.githubusercontent.com/11914919/87228577-0a18d180-c39a-11ea-8df5-8eacfa6cc24f.png">

Hope this helps!
