### ISSUE TITLE
Ability to copy bundle product types into other targets

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#91]
With this configuration:

```yaml
name: Project
targets:
  Project:
    type: framework
    platform: iOS
    dependencies:
      - target: ProjectResources
  ProjectResources:
    type: bundle
    platform: iOS
```

You can create a framework target, and an associated resource bundle for that target. But it doesn't seem like there's any way for you to add `ProjectResources` in this case to the copy resources phase of `Project`.

This would be very nice to support for the case where you have static libraries and resource bundles, since that's the only way to vend resources and not have conflicts with the targets linking the final library.
