### ISSUE TITLE
Settings configs generation is unstable when using name pattern match

### ISSUE THREAD

**Issue by ikarishinjigao** [yonaskolb/XcodeGen#910]
According to the [Settings documentation](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#settings), for example, we can use `production` key to apply some configs to `Release Production` and `Debug Production` scheme at the same time, but if I add the same config to both `production` and `Release Production`, the generated configs are not stable.

There is a example configs:
```yaml
targets:
  SomeTargget:
    settings:
      configs:
        release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) RLEASE
        Release Production:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) RLEASE PRODUCTION
```

expected result:
![Screen Shot 2020-07-15 at 17 19 24](https://user-images.githubusercontent.com/9335999/87521437-5a0bd700-c6bf-11ea-8ff4-216094f82dc2.png)

But when I run `xcodegen` like 3 times, the `SWIFT_ACTIVE_COMPILATION_CONDITIONS` may change to `RELEASE` which is unstable result, maybe add some warning or change the 'name pattern match' priority lower than the `exact match` to make sure that the `Release Production` overwrite the `release` one ?
