### ISSUE TITLE
Capabilities - App Group

### ISSUE THREAD

**Issue by techinpark** [yonaskolb/XcodeGen#919]
Hello!
I would like to know how to add `App Group`  configuration in xcodegen

![image](https://user-images.githubusercontent.com/45546296/89042697-5005fb80-d382-11ea-97ea-9137e5875e65.png)

And where to find more information about how to configure this part.
I can't find in offical documentations.

Thanks 😄

**Comment by techinpark** [comment]
self-answering problems

### Solution

```yml
targets:
  App:
    info:
      path: App/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    entitlements:
      path: App/App.entitlements
      properties:
        com.apple.security.application-groups: group.com.xxx.xxx
```
