### ISSUE TITLE
Frameworks and static library targets should be linked (and sometimes copied) into their dependent targets

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#92]
Currently if you create a configuration like this:

```yaml
name: Project
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - target: Module
  Module:
    type: framework
    platform: iOS
    sources:
      - ModuleSources
```

And generate a project, the `Module.framework` is copied into the `Project.app` target, but isn't linked in the "Link Binary and Libraries" phase (as is happening if you just use a vendored framework.

This is the same if you change `type: framework` to `type: library.static` with the one difference that static libraries should be linked, but shouldn't be copied, into the final `.app`
