### ISSUE TITLE
Not embedding project reference targets in multiple targets

### ISSUE THREAD

**Issue by sky-duartecosta** [yonaskolb/XcodeGen#933]
I have a project reference to be embedded in my main project, using its targets, but it only gets embedded in one target.

```
projectReferences:
  MyProject:
    path: Projects/MyProject/MyProject.xcodeproj
```

Targets:

```
MyTarget:
  dependencies:
      - target: MyProject.xcodeproj/MyProject.xcodeproj
        link: true
        embed: true

MyTargetOne:
  dependencies:
      - target: MyProject.xcodeproj/MyProject.xcodeproj
        link: true
        embed: true
```

Only one of the targets is embedded.

**Comment by MatheusMBispo** [comment]
This is happening with my project too 😕

**Comment by bluesource** [comment]
For me too. The depended targets are embedded only on the alphabetical sorted first target. 
I have 4 targets, which are defined by a template. The template define the dependencies. The dependencies are only embedded in the first target.

**Comment by mqzkim** [comment]
Could I ask this is intended spec.. or bug? Are there any updates?

**Comment by yonaskolb** [comment]
This is not intended behaviour, and should be treated a bug. I haven't had a chance to look into this. 
PR's welcome, even if all the PR does is add a test case that demonstrates this.

**Comment by mqzkim** [comment]
I just made a project which can reproduce this bug 100%.
When I add a file in `TargetExample` target, `Core` framework disappeared.

(cf. When I made the application target to top order of targets in project, the bug doesn't occur.
-> ex. If I change the name `TargetExample` to `000_TargetExample`, `Core` framework doesn't disappear.)


https://github.com/mqzkim/xcodegen-test

Here are `project.yml` files below.

`Core/project.yml`
```
name: Core
options:
  bundleIdPrefix: com.xcodgentest
targets:
  Core:
    sources: Core
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
```

`Target/project.yml`
```
name: Target
options:
  bundleIdPrefix: com.xcodgentest
projectReferences:
  Core:
    path: ../Core/Core.xcodeproj
targets:
  Target:
    sources: Target
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    dependencies:
      - target: Core/Core
  TargetExample:
    sources: TargetExample
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    transitivelyLinkDependencies: true
    dependencies:
      - target: Target
```

**Comment by mqzkim** [comment]
<img width="469" alt="스크린샷 2021-07-19 오후 3 36 02" src="https://user-images.githubusercontent.com/10410095/126114773-bd8e0334-dd8f-4ad9-88db-9bc60acbbbf2.png">

This is a screenshot from `Target.xcodeproj/project.pbxproj` file.
Products has two `Core.framework` files with different hash.
When I removed one of `Core.framework` file reference and related codes(`38C96BECA2E477A652351E8D`), the bug not occurred.

**Comment by mqzkim** [comment]
> This is not intended behaviour, and should be treated a bug. I haven't had a chance to look into this.
> PR's welcome, even if all the PR does is add a test case that demonstrates this.

@yonaskolb 
I just added PR with test case.
Thanks.

**Comment by ildar-gilfanov** [comment]
Hi, guys! Could you finish this bug fix? The issue is very annoying 😩

**Comment by mthole** [comment]
This might be related to https://github.com/yonaskolb/XcodeGen/issues/1017 ?

**Comment by kbhavyas** [comment]
Hi, I have an xcodeproject and I am migrating it using xcodegen. I too have the same issue that is only one of the targets embeds the dependency. However, if I open the original project and generate the new one. I don't have the problem. Could you please let me know the possible reason and the way to overcome this issue without openening original xcodeproject.

Thanks.

**Comment by zencodex** [comment]
I found a solution:

original code:
```
MyTarget:
  dependencies:
      - target: MyProject/MyProject
        link: true
        embed: true

MyTargetOne:
  dependencies:
      - target: MyProject/MyProject
        link: true
        embed: true
```

CHANGE TO:

```
MyTarget:
  dependencies:
      - target: MyProject/MyProject
        implicit: true
        link: true
        embed: true

MyTargetOne:
  dependencies:
      - target: MyProject/MyProject
        implicit: true
        link: true
        embed: true
```

add ` implicit: true` work well for me.
