### ISSUE TITLE
Support for SwiftPM subpackages?

### ISSUE THREAD

**Issue by JonasVautherin** [yonaskolb/XcodeGen#963]
Does XcodeGen support SPM subpackages, as defined here? https://github.com/ddunbar/swift-evolution/blob/multi-package-repos/proposals/NNNN-swiftpm-multi-package-repos.md

**Comment by JonasVautherin** [comment]
Using it [here](https://github.com/mavlink/MAVSDK-Swift-Example/blob/main/project.yml#L9-L15):

```
packages:
  Mavsdk:
    url: https://github.com/MAVLink/MAVSDK-Swift
    exactVersion: 1.1.0
  FFmpeg-iOS:
    url: https://github.com/kewlbear/FFmpeg-iOS
    minorVersion: 0.0.3
```

Does that help?
