### ISSUE TITLE
Xcode SPM dependency support: Dynamic vs Static

### ISSUE THREAD

**Issue by edulpn** [yonaskolb/XcodeGen#972]
I understand that Xcodegen has the feature to add Swift Packages as a Dependency to a Target. When I tested it, Xcodegen adds the dependency to the project (managed by Xcode) and also links it to any targets that specify it on the project spec.
In my specific use case, I have multiple targets in my project, and some of them share the same dependency. If I just add the same package as a dependency to multiple targets, I get the following error on build:

```
Showing Recent Messages
Swift package product 'XXX' is linked as a static library by 'YYY' and 3 other targets. This will result in duplication of library code.
```

As I understand from previous searches (from here, for example, https://forums.swift.org/t/how-to-link-a-swift-package-as-dynamic/32062/6) this is a bug on Xcode, where it, by default, links packages `statically`, instead of `dynamically`.
What is the "designed" way to do this on a project generated by Xcodegen? The link above mentions that one of the ways around this bug is creating a `dynamic` framework that links the `static` packages and then linking the "shim" framework to the multiple targets as a dependency.

**Comment by edulpn** [comment]
I tried doing this "shim" framework strategy like this:

```
packages:
  MySPMPackage:
    url: git@github.com:My/SPM.git
    from: 1.0.0

targets:
  SPMDependencies:
    type: framework
    platform: iOS
    dependencies:
      - package: MySPMPackage

  Target1:
    type: framework
    platform: iOS
    dependencies:
      - target: SPMDependencies

  Target2:
    type: framework
    platform: iOS
    dependencies:
      - target: SPMDependencies

  App:
    type: application
    platform: iOS
    dependencies:
      - target: Target1
      - target: Target2
```

But I'm still getting some of the static linking/code duplication errors.

**Comment by edulpn** [comment]
I also tried to set the package `link` property to `false`, it does indeed not add the package to the `Frameworks and Libraries` section, but it also gives lots of linking issues/Undefined symbol errors, which is the actual expected behavior.

**Comment by 1oo7** [comment]
@edulpn wrote:
>   Target1:
>    type: framework
>    dependencies:
>     - target: SPMDependencies

If the default behavior for frameworks is to embed dependencies then you would also need to explicitly NOT embed SPMDependencies in your frameworks. Only embed it in your app itself. Otherwise you'd have multiple copies of SPMDependencies embedded in each of these other frameworks, leading to the code duplication error. (If Stevia was a dynamic instead of static library, you'd get a warning instead of an error, unless warnings-as-errors was on of course).

**Comment by edulpn** [comment]
> If the default behavior for frameworks is to embed dependencies then you would also need to explicitly NOT embed SPMDependencies in your frameworks. Only embed it in your app itself. Otherwise you'd have multiple copies of SPMDependencies embedded in each of these other frameworks, leading to the code duplication error. (If Stevia was a dynamic instead of static library, you'd get a warning instead of an error, unless warnings-as-errors was on of course).

I see, I haven't paid attention to how `Target1` and `Target2` were embedding `SPMDependencies`, maybe because I was expecting it to not embed frameworks by default because of how Carthage works and have been working through `carthage` dependencies on Xcodegen on my setup (this is all a proof of concept as I try to migrate from Carthage to SPM, actually).

```
targets:
  Target1:
    type: framework
    dependencies:
      - carthage: Stevia

  Target2:
    type: framework
    dependencies:
      - carthage: Stevia

  App:
    type: application
    dependencies:
      - target: Target1
      - target: Target2
```

Running this through Xcodegen will create a project where `Stevia` is not embedded on `Target1`, `Target2` and `App`, but both `Target1` and `Target2` will be embedded on `App`. So I guess I always took some stuff for granted and I'm a bit confused right now on how this should all be embedded/linked?
