### ISSUE TITLE
Scheme config variants wrong assignment for similar config names

### ISSUE THREAD

**Issue by stefanomondino** [yonaskolb/XcodeGen#975]
We've found out a strange bug when using multiple config names and generating schemes automatically. 
If config names are similar (example: `PROD` and `PREPROD`), the Prod scheme will be (wrongly) assigned to the `PREPROD` configuration.

#### Example `project.yml`:

```yml
name: Test
configs:
  DEV Debug: debug
  DEV Release: release
  PROD Debug: debug
  PROD Release: release
  PREPROD Debug: debug
  PREPROD Release: release    
settings:
      configs:
        DEV Debug:
           SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEV DEBUG
        DEV Release:
           SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEV
        PROD Debug:
           SWIFT_ACTIVE_COMPILATION_CONDITIONS: PROD DEBUG
        PROD Release:
           SWIFT_ACTIVE_COMPILATION_CONDITIONS: PROD
        PREPROD Debug:
           SWIFT_ACTIVE_COMPILATION_CONDITIONS: PREPRD DEBUG
        PREPROD Release:
           SWIFT_ACTIVE_COMPILATION_CONDITIONS: PREPRD
options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "12.0"
targets:
  Test:
    type: application
    platform: iOS
    sources:
      - path: "Sources"
    settings:
        base:
            CURRENT_PROJECT_VERSION: 1
            MARKETING_VERSION: 0.26.0
            INFOPLIST_FILE: Sources/Info.plist
    scheme:
      configVariants:
        - DEV
        - PROD
        - PREPROD
```
#### Result
Opening the generated `Test PROD` scheme, there will be the `PREPROD Debug` and `PREPROD Release` configurations assigned.
