### ISSUE TITLE
Test target from a Swift package cannot be added to a scheme

### ISSUE THREAD

**Issue by ralfebert** [yonaskolb/XcodeGen#983]
If I add a locally embedded Swift Package that comes with a unit test target, I'd like to be able to add the test target to the app scheme to be able to run all unit tests in one swoop. Like this:

```
packages:
  BarPackage:
    path: ../BarPackage
targets:
  FooApp:
    scheme:
      testTargets:
        - FooApp-Tests
        - BarPackageTests
```

Currently this results in an error:

```
Spec validation error: Target "FooApp" scheme has invalid test "BarPackageTests"
```
