### ISSUE TITLE
Allow for arrays as templateAttributes

### ISSUE THREAD

**Issue by honkmaster** [yonaskolb/XcodeGen#991]
Use case: We want to define a list of custom fonts per target within the generated Info.plist.

This is our template (simplified):
```
targetTemplates:
  App:
    info:
      UIAppFonts: ${fonts}
```

This is the target (automatically generated, based on a tenant configuration file and folder content):

```
targets:
  Tenant1:
    templates:
      - App
    templateAttributes:
      fonts:
        - MyFont-Italic.ttf
        - MyFontBlack.ttf
```

So, I would want the resulting Info.plist to contain:

```
<key>UIAppFonts</key>
<array>
  <string>MyFont-Italic.ttf</string>
  <string>MyFont Black.ttf</string>
</array>
```
However, in the current state of XcodeGen, the result is:
```
<key>UIAppFonts</key>
<string>${fonts}</string>
```

Could this be a useful addition?
