### ISSUE TITLE
templateAttributes not working

### ISSUE THREAD

**Issue by stherold** [yonaskolb/XcodeGen#996]
The following spec gives me the error `Spec validation error: Target "DBFFMTests" has invalid dependency: "${host_app}"` on project generation. 

Any idea why the `templateAttributes` are not working?

```yaml
name: Beiwagen
options:
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "12.0"

targetTemplates:
  App:
    platform: iOS
    type: application
    sources:
      - path: "Beiwagen/source/whitelabel/${target_name}"
      - path: "Bridges"
    settings:
      base:
        PRODUCT_DISPLAY_NAME: ${product_display_name}
        PRODUCT_BUNDLE_IDENTIFIER: ${product_bundle_id}
        X_APPSTORE_ID: ${app_store_id}
    info:
      path: Beiwagen/Info.plist

  Tests:
    platform: iOS
    type: bundle.unit-test
    dependencies:
      - target: ${host_app}
    sources:
      - path: "BeiwagenTests"
    settings: 
      base:
        TEST_HOST: ${host_app}
        X_APPSTORE_ID: ${app_store_id}
    info:
      path: BeiwagenTests/Info.plist

targets:
  DBFFM:
    templates: [App]
    templateAttributes:
      product_display_name: ioki
      product_bundle_id: com.any.id
      app_store_id:  1234

  DBFFMTests:
    templates: [Tests]
    templateAttributes:
      host_app: DBFFM
      app_store_id:  1234
```
