### ISSUE TITLE
Segmentation Fault when Build Phase Script file does not exist

### ISSUE THREAD

**Issue by rm98** [yonaskolb/XcodeGen#997]
When a build phase script file does not exist `XcodeGen` runs into a segfault:
```sh
$ swift run xcodegen --use-cache
Segmentation fault: 11
```

An example for a part of a `project.yml` needed to reproduce the segmentation fault:
```
targets:
  CustomFramework:
    sources:
      - Sources/CustomFramework
    preBuildScripts:
    - path: build_scripts/file-that-does-not-exist.sh
      name: Build Phase Name
```

Versions:
* `XcodeGen` was integrated via SPM, the relevant section from the `Package.resolved`:
```json
{
  "package": "XcodeGen",
  "repositoryURL": "https://github.com/yonaskolb/XcodeGen.git",
  "state": {
    "branch": null,
    "revision": "bb4a3fa2dd720594e47f33cd48cce84fcf9f7066",
    "version": "2.18.0"
  }
}
```
* macOS 11.1 (Big Sur)
* Swift 5.3.2
```sh
$ swift --version
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
```
