### ISSUE TITLE
postGenCommand pod install not working version 2.6.0

### ISSUE THREAD

**Issue by sassiwalid** [yonaskolb/XcodeGen#998]
Hi, I'm using the 2.6.0 version of XcodeGen and I'm try to install pods using the postGenCommand options like this

```
options:
  defaultConfig: Release
  deploymentTarget: 
    iOS: "11.0"
  postGenCommand: pod install
```
but the pod didn't launch, xcodeGenerate generate correctly my workspace!!!!
